[BE] [team-07 jerry & 선을로] todo-list 메모리 기반 카드 등록, 삭제 기능 구현
codesquad-members-2022/todo-list pull request #10
Opened 2022-04-06 07:33 UTC by jeremy0405

안녕하세요 Sigrid!! 7 팀의 Jerry, 선을로입니다. 😄

Todo List 미션에 대한 PR 리뷰요청드립니다!

저희는 아직 DB에 미숙하여 이번 주 금요일까지 메모리 기반으로 기능 구현을 후에 배포를 진행하려고 합니다.

다음 주에는 DB를 붙여서 배포하는 것을 목표로 하고 있습니다.

<br>

### 한 일

- Table 설계, API 설계, URL 설계
- 카드 등록 기능 구현
- 카드 삭제 기능 구현

[table 설계 링크](https://docs.google.com/spreadsheets/d/15igDQ9pR762uyXrQw5VY0_kJeVR5m9aKzoUwIaV67xw/edit#gid=0)

[API, URL 설계 링크](https://github.com/jeremy0405/todo-list/blob/team-07-BE/be/README.md)

<br>

### 할 일

- 카드 수정 구현
    - 카드 동일 status 상태에서 드래그 앤 드랍 수정 구현
    - 카드 다른 status 상태로 드래그 앤 드랍 수정 구현
    - 카드 제목, 내용 수정 구현
- 활동 로그 구현

<br>

### 궁금한 사항

- 카드 드래그 앤 드랍 수정 기능 구현에서 Repository 클래스에 저장되어 있는 카드를 Service클래스로 가져와서 POST로 들어온 카드의status를 비교하여 카드의 이동 유무를 판단하는 비즈니스 로직이 들어가도 되는지 궁금합니다.
현재 Service 클래스에서 Repository에 findById()를 통해 카드를 가져와 비교를 진행한 후 Repository의 적절한 메서드를 호출할 생각입니다.
- 현재 POST, DELETE, PATCH 요청 이후에 redirect로 /list로 이동하도록 하고 있는데 response로 200 OK 를 내려주는 것과 현재처럼 redirect를 하는 것 중에 어떻게 하는 것이 좋은지 궁금합니다.

*카드 수정 구현은 코드에 주석으로 어떻게 구현 할 지 러프하게 적어 놨습니다.

2022-04-06 23:27 UTC, jypthemiracle requested changes
### 인사

안녕하세요, 리뷰어 Sigrid Jin입니다.
첫 번째 리뷰요청 잘 보았습니다. 저와 많은 디스커션 나눌 수 있기를 소망합니다. :)
궁금하신 점이 있으면 언제나 슬랙 디엠 보내주세요. 감사합니다.

### 궁금한 사항에 대한 답변
문. 카드 드래그 앤 드랍 수정 기능 구현에서 Repository 클래스에 저장되어 있는 카드를 Service클래스로 가져와서 POST로 들어온 카드의status를 비교하여 카드의 이동 유무를 판단하는 비즈니스 로직이 들어가도 되는지 궁금합니다. 현재 Service 클래스에서 Repository에 findById()를 통해 카드를 가져와 비교를 진행한 후 Repository의 적절한 메서드를 호출할 생각입니다.

답. 해당 코드를 보았는데요. Service 클래스에서 직접 카드 객체 간의 상태를 비교하도록 구현하는 경우도 왕왕 있습니다. 아직 이야기될 단계는 아니지만, 결국에는 카드 객체 스스로 상태를 비교할 수 있도록 그 책임을 위임하도록 구현하는 것이 좋다는 의견도 있습니다. 스스로 고민해보세요. [읽어볼 거리](https://stackoverflow.com/questions/437067/domain-objects-and-services)

문. 현재 POST, DELETE, PATCH 요청 이후에 redirect로 /list로 이동하도록 하고 있는데 response로 200 OK 를 내려주는 것과 현재처럼 redirect를 하는 것 중에 어떻게 하는 것이 좋은지 궁금합니다.

답. 글쎄요, 선택하기 나름인데 저는 서버는 처리요청에 대한 답변을 회신하는 역할을 한다고 생각했을 때 200 OK code를 내려주고, 이 code에 대한 해석을 어떻게 가져갈 것인가는 프론트엔드 단에서 고민하는 것이 맞다고 생각합니다.

2022-04-06 23:27 UTC, realsigridjin commented on be/todolist/build.gradle
> +sourceCompatibility = '11'
오 자바 11을 사용하시나요?

2022-04-06 23:27 UTC, realsigridjin commented on be/todolist/gradlew.bat
> +@rem
불필요한 gradle dependency는 제외해주시면 좋을 것 같습니다. declare at `.gitignore` !

2022-04-06 23:27 UTC, realsigridjin commented on be/todolist/src/main/java/team07/todolist/domain/Card.java
> +	public Integer getStatus() {
Wrapper Class를 사용하신 이유가 있나요? Primitive Type이 아닌 이유에 대해 알고 싶네요. ^_^

2022-04-06 23:27 UTC, jypthemiracle commented on be/README.md
> +        "time": "2022-04-05T12:15:00.000+09:00"
Timestamp 객체를 내려준 것인가요? Response에서는 시간 문자열을 파싱해서 보내주는 것이 낫지 않을까요?

2022-04-06 23:27 UTC, jypthemiracle commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +	private static final Map<Long, Card> store = new ConcurrentHashMap<>();
```ConcurrentHashMap``` 이 등장했네요.. `HashMap` 을 사용하지 않으신 이유가 있나요? 해당 자료구조를 사용했을 때의 장, 단점이 무엇이 있을 지 고민해보세요.
참고: https://stackoverflow.com/questions/3951676/are-there-any-drawbacks-with-concurrenthashmap

2022-04-06 23:27 UTC, jypthemiracle commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +		switch (status) {
현재 요구사항과 같이 간단한 상황에서는 `switch` 문을 사용할 수도 있겠지만, 이는 1, 2, 3 이라고 하는 `code` 를 이해해야 한다는 부담감을 안겨주고, 장기적으로 유지보수에 도움이 되지 않습니다. 기능이 추가될 때마다 일일이 코드를 추가해야 한다면, 코드를 짜는 사람이나 읽는 사람 모두 정신이 나가지 않을까요?

하기 링크를 참고해보시고, 스스로 답변을 고민해보세요. switch 문을 사용하는 것 외에도, 다형성과 인터페이스를 활용할 수 있도록 고민해보시기를 추천드립니다.
https://stackoverflow.com/questions/550919/does-anyone-disagree-with-the-statement-using-switch-is-bad-oop-style

2022-04-06 23:27 UTC, jypthemiracle commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +	private static AtomicLong sequence = new AtomicLong();
AtomicInteger가 등장했군요. 하기 질문에 대한 답을 들어보고 싶네요.
1. 일반적인 Long type이 아니라 AtomicLong을 사용한 이유는?
2. 옆자리 친구에게 Atomic Operation을 가장 쉽게 설명해보세요. [참고](https://stackoverflow.com/questions/52196678/what-are-atomic-operations-for-newbies)

2022-04-06 23:27 UTC, jypthemiracle commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +			.filter(c -> c.getStatus().equals(status))
적극적인 `Stream` 사용은 추천할 만 합니다.
* 그런데요, 꼭 `Stream` 사용 만이 답일까요? for 문을 사용하지 않으신 이유가 있으실까요?

2022-04-06 23:27 UTC, jypthemiracle commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +	public Card updateStatusAndRow(Long id, Integer status) {
구현되지 않은 feature는 올려주지 않으시거나, 만약 올려야 한다면 주석처리 해주시는 것이 좋겠습니다.

2022-04-06 23:27 UTC, jypthemiracle commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +		return new ArrayList<>(store.values());
Question. 하기 두 선언에는 어떠한 차이가 있을까요? [링크](https://stackoverflow.com/questions/12321177/arraylist-or-list-declaration-in-java)

Declaration 1:
```
ArrayList<String> arrayList = new ArrayList<String>();
```
Declaration 2:
```
List<String> arrayList = new ArrayList<String>();
```

2022-04-06 23:27 UTC, jypthemiracle commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +		return new ArrayList<>(store.values());
Guava로 ```Lists.newArrayList()``` 를 활용하여 ArrayList를 만드는 방법도 있으니 한 번 참고해보세요. 무슨 차이가 있을까요? [참고](https://stackoverflow.com/questions/9980915/lists-newarraylist-vs-new-arraylist)

2022-04-06 23:27 UTC, jypthemiracle commented on be/todolist/src/main/java/team07/todolist/service/CardService.java
> +		Card newCard = new Card(requestCard.getUserId(), requestCard.getTitle(),
적극적인 `constructor` 사용은 칭찬할 만 합니다. Builder Pattern이 앞으로 종종 보일 지도 모르겠는데, 만약 고민하는 주제 중 하나라고 하시면 생성자 사용과 비교하여 어떠한 장, 단점이 있는 지도 생각해보세요.

2022-04-06 23:27 UTC, jypthemiracle commented on be/todolist/src/main/java/team07/todolist/service/CardService.java
> +		if (card.isDifferentStatus(requestCard.getStatus())) {
코드에 작성된 두 로직 (status가 다르다면 / row만 다르다면) 이 서로 분리되는 것이 나아 보입니다. 왜냐하면 `dragAndDrop()`이 두 경우 모두를 책임진다고 했을 때 하나의 함수에 대한 과도한 역할 부담인 것으로 보이거든요. 앞으로 해당 두 로직이 점점 기능 상으로 차이가 날 수도 있지 않을까 생각이 들어서요. 어떻게 보시나요?

2022-04-06 23:27 UTC, jypthemiracle commented on be/todolist/src/test/java/team07/todolist/TodoListApplicationTests.java
> +@SpringBootTest
테스트 작성이 지금은 어렵다면, 커밋에서 제외해주세요.

2022-04-07 01:43 UTC, fpzk5656 commented on be/todolist/build.gradle
> +sourceCompatibility = '11'
넵! 호눅스가 11버전을 권장하셧고,
현재 현업에서도 11버전을 많이 사용한다고 들어서 이렇게 하였습니다!

2022-04-07 01:49 UTC, jeremy0405 commented on be/todolist/gradlew.bat
> +@rem
현재 mac을 쓰는 팀원과 window를 쓰는 팀원이 같이 있어서 `gradlew.bat` 도 포함해서 윈도우 팀원도 build를 하기 위해서 같이 올렸습니다. 혹시 제외해야 하는 걸까요??

2022-04-07 01:52 UTC, fpzk5656 commented on be/todolist/src/main/java/team07/todolist/domain/Card.java
> +	public Integer getStatus() {
null인 상황이 있을 지도 모른다는 생각에 대비하기 위해 설정해봤는데,
코드 작성을 하다보니 null이 주입될 상황이 만들어지지 않아서 int로 바꿀 예정입니다.

2022-04-07 01:53 UTC, jeremy0405 commented on be/todolist/gradlew.bat
> +@rem
윈도우 쓰는 팀원과 mac을 쓰는 팀원이 같이 있어서 윈도우 팀원이 build를 하기 위해서 `gradlew.bat`을 포함했습니다. 이 파일을 내리면 윈도우 유저가 build를 못한다는 생각에 같이 올렸는데 파일을 제거해야 할까요??

2022-04-07 01:54 UTC, jeremy0405 commented on be/README.md
> +        "time": "2022-04-05T12:15:00.000+09:00"
참고해서 변경해보겠습니다!!

2022-04-07 01:58 UTC, jeremy0405 commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +	public Card updateStatusAndRow(Long id, Integer status) {
넵! 다음부터는 주석처리해서 올리겠습니다!!

2022-04-07 01:59 UTC, fpzk5656 commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +	private static final Map<Long, Card> store = new ConcurrentHashMap<>();
ConcurrentHashMap을 사용했을 때는 쓰레드 안정성이 확보되지만, 
자원에 락을 거는 작업으로 인해 성능이 HashMap에 비해 떨어진다는 단점이 있다고 알고 있습니다.

2022-04-07 02:20 UTC, jeremy0405 commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +		switch (status) {
넵! 고민해보겠습니다!!

2022-04-07 02:28 UTC, jeremy0405 commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +			.filter(c -> c.getStatus().equals(status))
`stream`이 for문보다 가독성이 좋고 사용하기 편해서 사용했습니다.

2022-04-07 02:31 UTC, jeremy0405 commented on be/todolist/src/main/java/team07/todolist/service/CardService.java
> +		Card newCard = new Card(requestCard.getUserId(), requestCard.getTitle(),
현재 Card Class에 빌더 패턴을 적용했습니다.
장점으로는 가독성이 개선된다는 것이고 단점으로는 코드의 양이 증가된다는 단점이 있다고 생각합니다.

2022-04-07 02:32 UTC, jeremy0405 commented on be/todolist/src/main/java/team07/todolist/service/CardService.java
> +		if (card.isDifferentStatus(requestCard.getStatus())) {
저희도 현재 메서드가 많은 역할을 분담하고 있다고 생각하고 있어서 분리에 대해 고민하고 있었습니다!
Sigrid의 말씀처럼 두 로직을 분리해보도록 하겠습니다. 😄

2022-04-07 02:41 UTC, jeremy0405 commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +	private static AtomicLong sequence = new AtomicLong();
1. 멀티쓰레드 상황에서도 안정적으로 사용하고 싶어서 AtomicLong을 사용했습니다 :)

<br>

2. Atomic Operation은 연산을 원자적으로 해서 스레드 세이프한 연산입니다.

자신이 직접 값에 접근해서 증가하는 것이 아니라 Atomic Operation을 구현한 객체에게 값을 증가해달라고 요청을 해서 스레드 세이프한 결과를 기대할 수 있습니다.

2022-04-07 02:45 UTC, fpzk5656 commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +		return new ArrayList<>(store.values());
1)  첫번째 선언은 ArrayList의 모든 메소드를 사용할 수 있다는 장점이 있고,
두번째 선언은 List가 여러 List종류를 다형성으로 활용할 수 있기에 확장성에서 차이가 있다고 봅니다.

2) 참고 링크의 내용을 읽어본 바. 구아바는 제네릭을 다양하게 오버로딩할 수 있는 장점이 있다고 읽었습니다.
그러나 자바7버전 이후부터의 방식은 제네릭을 명시할 필요가 없어져서 구아바의 사용 이유가 없어졌다고 생각합니다.

2022-04-07 08:02 UTC, jypthemiracle commented on be/todolist/build.gradle
> +sourceCompatibility = '11'
그렇군요. 자바 11로의 마이그레이션이 빠르게 이루어지나 봅니다. 코틀린의 사용이 실무에서 급격하게 빨라지고 있는 만큼, 자바 진영에서도 자바 8 이상의 변화가 계속해서 이루어지고 있는 것으로 보이네요.

2022-04-07 08:02 UTC, jypthemiracle commented on be/todolist/gradlew.bat
> +@rem
아.. 그렇군요.. 윈도우 사용하는 팀원을 배려하지 못했네요. 그렇다면 해당 파일은 포함하는 것이 좋겠습니다.

2022-04-07 08:04 UTC, jypthemiracle commented on be/todolist/src/main/java/team07/todolist/domain/Card.java
> +	public Integer getStatus() {
Effective Java에 하기와 같은 Item 5 사항이 수록되어 있습니다.
```
The lesson is clear: prefer primitives to boxed primitives, and watch out for unintentional autoboxing.
```
다음 링크를 참조하시고, 본인이 생각하기에 wrapped class와 primitive type의 장단점 및 사용처가 어디일 지 생각을 정리해보세요.
[참고할 만한 링크](https://softwareengineering.stackexchange.com/questions/203970/when-to-use-primitive-vs-class-in-java)

2022-04-07 08:32 UTC, jypthemiracle commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +	private static final Map<Long, Card> store = new ConcurrentHashMap<>();
그러면 이렇게 여쭤보겠습니다. 쓰레드-safe 하게 자료구조를 만드는 것이 꼭 thread-safe 하게 구현하는 것일까요? 생각해봅시다.

> If I were asking this question in an interview, what I would be testing is: does the candidate understand that using thread-safe data structures doesn't make his algorithm thread-safe?

[링크](https://stackoverflow.com/questions/52193939/when-to-use-concurrenthashmap-vs-hashmap-for-put-and-get)

2022-04-07 08:33 UTC, jypthemiracle commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +			.filter(c -> c.getStatus().equals(status))
그 이상을 생각해봅시다. Stream은 for 문에 비해 속도가 매우매우 느립니다.
하기 링크를 참고해보시고, 본인의 생각을 정리해보세요.

[참고할 만한 링크](https://jypthemiracle.medium.com/java-stream-api%EB%8A%94-%EC%99%9C-for-loop%EB%B3%B4%EB%8B%A4-%EB%8A%90%EB%A6%B4%EA%B9%8C-50dec4b9974b)

2022-04-07 08:37 UTC, jypthemiracle commented on be/todolist/src/main/java/team07/todolist/service/CardService.java
> +		Card newCard = new Card(requestCard.getUserId(), requestCard.getTitle(),
빌더 패턴은 안전한 객체 생성을 보장해주지 않다고 생각합니다. 코틀린을 학습하게 되면 Named Parameter를 사용하게 되므로 굳이 학습할 필요가 없다는 것이 저의 의견입니다.

https://code-held.com/2021/01/23/dont-use-builder-in-kotlin

2022-04-07 22:15 UTC, jeremy0405 commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +	private static final Map<Long, Card> store = new ConcurrentHashMap<>();
thread-safe한 자료구조를 사용하는 것이 thread-safe를 보장하지는 않습니다.

임계구역에 대한 코드 전체에 하나의 프로세스만 접근이 가느앻야 thread-safe 하게 구현하는 것입니다.
현재의 저희 코드에는 임계구역이라고 생각하는 로직이 map.put() 하나이기 때문에 thread-safe한 자료구조를 사용해 thread-safe를 보장하고 있다고 생각합니다.

2022-04-07 22:30 UTC, jeremy0405 commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +			.filter(c -> c.getStatus().equals(status))
상기의 Sigrid 블로그에 대한 저의 생각은 다음과 같습니다.

primitive type 배열에 대해서는 stream의 성능이 for문의 성능보다 많이 떨어지므로 stream을 사용하는 것이 좋지 않을 것 같으며 일반적으로도 stream의 성능이 for문보다 뒤쳐지므로 대용량 트래픽을 받는 서버라면 성능을 위해 가독성과 유지보수성을 희생하고 for문 사용을 고려해야 한다고 생각합니다! 좋은 인사이트 감사합니다!!

2022-04-08 05:35 UTC, merged