[Team-16] BE 2번째 PR입니다.
codesquad-members-2022/todo-list pull request #108
Opened 2022-04-08 08:23 UTC by street62

안녕하세요 리뷰어님! 16조 백엔드를 맡은 Heyho, Lee입니다.

2번째 PR 보내드립니다.
첫 번째 PR에서 남겨 주신 질문에 대해서 저희 나름대로 생각한 것들을 댓글로 달아 보았습니다. 확인해주시면 감사하겠습니다!
https://github.com/codesquad-members-2022/todo-list/pull/30

## 작업 내용
### 데이터베이스 연결
AWS EC2 서버의 MySQL 데이터베이스를 datasource로 하여 프로젝트와 연결했습니다.

### 투두리스트 태스크 추가 API 작성
TaskController.add() 메서드를 통해 유저가 투두리스트에 작성한 태스크를 DB에 추가하는 API를 작성했습니다.

### API 명세 공유를 위한 Swagger 연결
iOS 팀과 원활한 API 명세를 공유하기 위해 Swagger를 도입해 TaskController.add() API와 연결했습니다.

그럼 이번에도 잘 부탁드립니다.
감사합니다!

2022-04-10 05:14 UTC, wheejuni requested changes
수고 많으셨습니다. 💯 
몇 가지 코멘트 남겼으니 확인 부탁드립니다

2022-04-10 05:14 UTC, wheejuni commented on todo-list-server/build.gradle
> +group 'com.list'
group ID 정하는 방법은 혹시 알고 계시나요? 보통 도메인의 역순입니다.
코드스쿼드 프로젝트니까 `kr.codesquad` 이면 좋긴 하겠는데 이건 개인 취향이라 맘대로 하시면 되겠습니다.

2022-04-10 05:14 UTC, wheejuni commented on todo-list-server/src/main/java/com/list/todo/controller/TaskController.java
> +    public ResponseEntity<Object> add(@RequestBody Task task) {
`Task` 타입을 내려주는 거 같은데 왜 `ResponseEntity<Object>` 인지요?

2022-04-10 05:14 UTC, wheejuni commented on todo-list-server/src/main/java/com/list/todo/controller/TaskController.java
> +            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
서비스 클래스에서 캐치하고 결과를 내려야 할 로직으로 보입니다만.

2022-04-11 02:59 UTC, street62 commented on todo-list-server/src/main/java/com/list/todo/controller/TaskController.java
> +    public ResponseEntity<Object> add(@RequestBody Task task) {
리뷰 이후에 상태코드 200의 경우에도 body 없이 상태코드를 담은 헤더만 반환하는 방식으로 바꾸었는데요. 이 경우에 ResponseEntity의 제네릭 부분을 삭제(바디를 사용하는 응답이 없으므로)하면 인텔리제이에서 경고가 뜨는 것 같습니다. 그래서 우선은 Object로 두었는데 혹시 바디가 없는 경우에는 어떤 식으로 제네릭을 지정해주면 좋을까요?

2022-04-11 03:01 UTC, street62 commented on todo-list-server/src/main/java/com/list/todo/controller/TaskController.java
> +            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
말씀 주신 내용을 요청으로 들어온 Task 객체의 유효성을 체크하고 그에 맞는 responseEntity를 생성하는 역할이 컨트롤러가 아니라 서비스 단에서 이루어져야 한다는 의미로 이해했는데 맞을까요? 컨트롤러에서는 서비스에서 생성한 responseEntity를 전달받아 그대로 리턴하는 방식으로 변경했습니다.

2022-04-11 03:08 UTC, street62 commented on todo-list-server/build.gradle
> +group 'com.list'
참고해서 변경했습니다. 감사합니다!

2022-04-14 01:42 UTC, street62 commented
머지가 조금 늦어져서 2번째 PR을 닫고 3번째 PR에 2번째 PR 커밋까지 넣어서 진행하려 합니다. 3번째 PR(#184) 확인해 주시면 감사하겠습니다!-!

2022-04-14 01:42 UTC, closed without merging