[team24][FE][JS&S] 1주차 금요일 pr
codesquad-members-2022/todo-list pull request #123
Opened 2022-04-08 10:12 UTC by herrakam

늦어서 죄송합니다ㅠㅠ

### 구현내용
1. 등록 박스 생성
2. 등록 박스를 일반 박스 스타일로 변경
3. mvc 패턴(적용중)

### 물어볼 내용
1.  axios post, delete, put 메소드 실행시 페이지가 리랜더링 되고 있습니다. 그래서 구현한 대부분의 함수들이  이 영향을 받고 있습니다. 크롱께 여쭤보니, 서버의 응답을 확인해보라는 답변을 주셨는데, 응답을 확인해봤지만 문제를 해결하지 못했습니다. 이 문제에 대해서 어떤 주제를 검색해봐야 해결할 수 있을까요?
2. mvc 패턴을 적용중인데, 등록 버튼 클릭시 post 메소드가 실행되지 않는 반면 (내부에서 콘솔도 찍히지 않음) 같은 함수 내에 있는 스타일을 바꿔주는 함수는 잘 적용이 되고 있습니다.  뷰와 컨트롤러가 서로 상호참조하고 있어서 실행이 되지 않는 걸까요?

2022-04-08 14:18 UTC, hongbiii requested changes
오타가 있어 프로젝트 실행에 어려움이 있네요~
오타는 제가 임의로 수정해서 로컬에서 프로젝트 실행해보려 하는데 프로젝트 실행하려면 어떻게 해야 하는지 알려주시겠어요? 😭

```
json:server 스크립트 실행
npx webpack >> 여기서 실패
```

npx webpack 실행 시 에러가 나는데 JS, S는 에러 안 나나요..?

2022-04-08 14:18 UTC, hongbiii commented on server/package.json
> +    "json-sever": "^0.17.0"
오타가 있네요~ 혹시 수작업으로 작성하신 걸까요?
(오타가 있어서 npm i 했을 때 설치에 실패하네요)

패키지 설치 시 npm 커맨드라면 `--save-dev`, yarn 커맨드라면 `-D` 옵션을 붙여주면 알아서 package.json의 devDependencies에 들어간답니다!

```suggestion
    "json-server": "^0.17.0"
```

2022-04-08 16:14 UTC, herrakam commented
저희가 기존에 liveServer를 쓰다가 post 메서드 동작시 페이지 자체가 리랜더링 되서 급하게 express로 바꾸면서 웹팩을 신경을 못쓴 것 같습니다 죄송합니다 ㅠㅠ 확인해보니 저희도 npx webpack은 에러가 나고 있습니다.webpack 부분은 무시하시고 server 폴더에서 `npm run json:server` , build/frontServer에서 `node app.js` 를 통해 프로젝트를 실행 해주시면 될 것 같습니다. webpack부분은 최대한 빠르게 고쳐보겠습니다. 혼란을 드려서 죄송합니다 ㅠㅠㅠ

2022-04-08 16:46 UTC, soralee2821 commented
util 파일에서 axios를 import하는 첫번째 라인에서 에러가 나고 있어서 주석처리했습니다.
그리고 html에서 unpkg CDN script를 작성하여 axios를 사용할 수 있게 수정했습니다.
bulid 폴더 위치에서 'npx webpack' 명령어를 실행하시면 webpack이 실행됩니다.
혼란을 드려서 정말 죄송합니다ㅠㅠ

2022-04-08 16:59 UTC, soralee2821 commented
build/frontServer 폴더 위치에서 `node app.js`  명령어를 통해 express 서버를 실행하는 방법 이외에도, build 폴더 위치에서 `npm start` 명령어를 통해 express 서버가 실행되도록 package.json(build)의 경로를 수정했습니다.

2022-04-08 17:29 UTC, hongbiii reviewed
안녕하세요! 리뷰어 어텀입니다.
벌써 일주일이 지났네요~~
첫 팀프로젝트라 더 힘드셨을 것 같은데 고생 많으셨습니다. 😃
프로젝트를 하다 보면 공부해야할 것은 산더미고 자칫 잘못하면 길을 잃기 쉬운데요,
이번 프로젝트에서 이것만큼은 꼭 내것으로 만들겠다! 하는 목표를 설정해두시고 중간중간 점검하는 시간을 가져보세요 :)

아래 내용은 작성해주신 코드에서 전반적으로 느껴지는 것에 대한 피드백입니다!
더 궁금하신 것이 있으시면 코멘트 달아주세요. 주말동안 확인 후 답변 드리겠습니다~~!

---

### 1. html 태그 사용이 아직은 어색해보이는 면이 있네요.
  - 금방 익숙해지니 크게 걱정은 안 하셔도 되지만,
  - 태그를 작성하기 전에 적절한 태그인지 한번씩만 고민해보면 좋을 것 같아요.

### 2. 함수의 이름과 실제 역할이 다른 부분이 많아요.
- 변수명 함수명 짓는 건 항상 고민이 많이 되긴 합니다. ㅎㅎㅎ
- 일반적인 단어를 구체적인 단어로, 함수 이름은 동사+명사 형태로 만들어보는 연습을 의식적으로 해주세요.

### 3. MVC 패턴을 적용하실 때 각각의 역할에 대해서 많은 고민이 필요해보여요. 지금은 역할이 뒤섞인 듯한 모습이 보입니다! (적용중이라고 하신 걸 어느정도 감안하더라도요)
- 가령 View가 하는 역할을 생각해보면, 데이터를 받아서 화면에 그려주기만 하는 걸 코드로 어떻게 작성할까?
- 어떤 데이터가 들어오든 적절한 템플릿을 붙여 화면에 그려내야 하는데 View에서 데이터를 만들고 있지는 않는가? 혹은 외부의 데이터를 조작하고 있진 않은가?
- 남겨주신 아래 질문에 대한 답이 되었으면 좋겠네요. 😀

> 뷰에서 axios.post 메소드를 사용하고 있습니다. axios.post 메소드는 데이터를 추가하는 메소드인데, 이 메소드를 뷰에서 사용해도 될까요?

2022-04-08 17:29 UTC, deprecated-hongbiii commented on build/src/index.html
> +            <figure class="cross-button">
class에는 button이라고 써있는데 figure 태그가 사용된 점이 다소 어색하네요!

2022-04-08 17:29 UTC, deprecated-hongbiii commented on build/src/index.html
> +            e4c5ac880d6db3e571366beba27afead79e71199
충돌 코드가 덜 지워졌어요.
충돌 해결할 때 어떤 방법을 사용하셨는지 궁금하네요!
한땀한땀 지우는 방법은 실수 발생의 여지가 아주 높아요.
도구의 도움을 받으면 훨씬 더 간편하게 충돌을 해결할 수 있으니, 한번 찾아보셔도 좋을 것 같습니당

2022-04-08 17:29 UTC, deprecated-hongbiii commented on build/src/index.html
> +    <script type="module" src="./javascript/app.js"></script>
body의 마지막에 script를 넣는 것
async
defer

이 차이점을 공부해보셨으면 좋겠어요!

2022-04-08 17:29 UTC, deprecated-hongbiii commented on build/src/javascript/createRegister.js
> +    <div class="card"  id="card${todoCount + 1}">
id에는 말 그대로 고유한 값을 넣어야 하는데요!
어떤 값에 +1을 하는 방식은 고유하지 않을 뿐더러
`todoCount` 라는 변수는 const 여서 항상 같은 id를 가지게 될 것 같네요~
왜 하필 +1 을 했는지도 궁금하구요!

2022-04-08 17:29 UTC, deprecated-hongbiii commented on build/src/javascript/util/util.js
> +}
async/await과 then 체이닝을 함께 사용하는 게 불필요해보여요!
저도 이 개념이 참 어려웠는데요,
Promise부터 천천히 익혀나가시면 좋을 것 같아요.

2022-04-08 17:29 UTC, deprecated-hongbiii commented on build/src/javascript/util/util.js
> +}
API 요청하는 함수를 재사용할 수 있도록 노력하신 점이 좋네요!
여기서 파라미터로 쓰인 request, dataName, data에 대해 짚고 넘어가면 좋을 것 같아요.

1. get, post, put, delete라는 것을 묶어서 부르는 단어가 무엇일까?

- request라고 이름지으셨는데, get post put delete를 지칭하는 단어가 따로 있을 것 같아요.
- 잘 모르겠으니 무지성으로 get post put delete 라고 검색해보니 블로그 포스팅들이 많이 나오네요.
- axios를 사용하셨으니 axios를 기준으로 말씀드려보면, axios 한글 문서의 [Axios API 섹션](https://axios-http.com/kr/docs/api_intro)에 들어가보니, 아하! 요런 개념을 묶어서 뭐라고 부르는지 알 것 같아요.~~

2. dataName

- 어떤 데이터의 네임인지 변수명만 보고 알기가 어려워요
- 그런데 이 변수가 url의 `/` 뒤에 쓰였네요. 이것도 지칭하는 단어가 있을 것 같아요!

3. data

- 이것도 마찬가지로 너무 일반적인 네이밍이에요. 적절한 용어가 있는지 찾아보시면 좋을 것 같아요.

2022-04-08 17:29 UTC, deprecated-hongbiii commented on build/src/javascript/util/util.js
> +}
`$` 보다 더 적합한 이름이 없을지 고민해보시면 좋을 것 같아요. :)

2022-04-08 17:29 UTC, deprecated-hongbiii commented on build/src/javascript/view/cardView.js
> +}
이 함수가 하는 역할을 생각해봤을 때 돔요소를 인자로 받는 것보다는 텍스트 자체를 인자로 받는 게 더 자연스러울 것 같아요!
length라는 표현도 더 구체적이면 좋겠구요 :)

2022-04-08 17:29 UTC, deprecated-hongbiii commented on build/src/javascript/view/cardView.js
> +  });
`$card.style`이라는 객체에 `{ opacity: 1, border: "none" }`이라는 객체를 합치고 싶어서 Object.assign을 사용하신 게 맞을까요?
객체에 프로퍼티를 추가하는 방법에는 어떤 게 있는지,
객체를 복사하려면 어떻게 해야 하는지
학습해보시면 좋을 것 같습니당!

2022-04-08 17:29 UTC, hongbiii commented on build/src/javascript/view/cardView.js
> +  }
각각의 버튼들에 같은 이벤트를 등록해주고 있네요~
이 버튼들이 어떤 dom 구조를 가지는지는 모르겠지만
event deligation이라는 개념을 적용해볼 수 있을 것 같아요.

다른 이벤트 등록 코드에서는 target만 destructuring 잘 해오셨는데 여기는 적용이 안 되어 있네요!
통일성 있게 여기도 destructuring 해주시는 게 좋겠습니다.

2022-04-08 17:29 UTC, hongbiii commented on build/src/javascript/util/util.js
> +}
util에 데이터 fetching하는 함수들이 있는 게 어색해요.
util 이라는 단어의 뉘앙스가 잘 안 와닿으실 수 있는데
작성해주신 함수들 중에서는 글자수 체크하는 함수가 유틸에 더 가까워요.!

2022-04-08 17:29 UTC, hongbiii commented on build/src/javascript/view/cardView.js
> +}
함수의 이름은 init , 뭔가 초기화해주고 시작하는 역할을 할 것 같은데
내부 구현은 플러스버튼에 이벤트를 등록해주고 있네요.

함수의 이름과 역할이 매치되지가 않습니다!

2022-04-10 16:43 UTC, herrakam commented on build/src/index.html
> +            <figure class="cross-button">
버튼이기도 하면서 이미지를 감싸고 있는 테그라 button으로 할지 figure로 할지 고민을 했었는데, button으로 바꾸겠습니다!

2022-04-10 16:49 UTC, herrakam commented on build/src/javascript/createRegister.js
> +    <div class="card"  id="card${todoCount + 1}">
각 카드 마다 고유한 id 값을 주려고  했었고, 새로 생성되는 n번째 카드의 id값을 card + n(ex: 5번째 카드=>card5)로 생성 하고자 했습니다! let이 아니라 const로 구현한 게 실수였던 것 같습니다. let으로 바꾸겠습니다!

2022-04-10 17:00 UTC, herrakam commented on build/src/javascript/util/util.js
> +}
1. 찾아보니 request 보단 method 가 더 적합한 파라미터 명인 것 같습니다. method로 바꾸겠습니다!
2. dataName과 data도 좀더 구체적인 변수명으로 바꿔보겠습니다!

2022-04-10 17:06 UTC, merged

2022-04-11 01:27 UTC, soralee2821 commented on build/src/index.html
> +            e4c5ac880d6db3e571366beba27afead79e71199
VS Code에서 충돌난 부분 수정했습니다. html 파일은 VS Code의 충돌 수정 기능이 활성화되지 않아서 수동으로 수정하다보니 덜 지워졌습니다ㅠㅠ

2022-04-11 01:49 UTC, herrakam commented on build/src/javascript/view/cardView.js
> +  });
크롱이 js에서 인라인으로 여러 개의 스타일을 변경해야할 때,  사용할 때 마다 태그의 style에 접근 해야 하는 인라인 방식보다 태그 스타일에 접근 횟수를 줄일 수 있는 `Object.assgin()`을 활용하라고 말씀해주셔서 사용했습니다

2022-04-11 03:16 UTC, autumninflab commented on build/src/javascript/createRegister.js
> +    <div class="card"  id="card${todoCount + 1}">
아하 그런 의도로 작성하셨군요~~
그런데 length를 기준으로 id를 생성하게 되면,
가령 카드 2개를 만들었다가 card2를 삭제하고 새로 카드를 만드는 상황에서는 새로 만들어진 카드가 card2 라는 아이디를 갖게 될 것 같은데 맞을까요?

uuid라는 키워드가 있다는 것 정도만 알려드릴게용!!
(절대 이게 정답이라는 뜻은 아닙니다!)

2022-04-11 03:34 UTC, herrakam commented on build/src/javascript/view/cardView.js
> +  }
기존 카드 이벤트는  페이지가 렌더링 될 때, 등록카드 이벤트는 등록카드가 랜더링 될 때 등록하게 됩니다. 그런데 event Deligation 사용시, 등록카드의 등록버튼에 달린 이벤트와 상위 테그에 등록된 이벤트까지 실행되서 등록 이벤트가 2번 일어나게 됩니다.  결과적으로 post 메소드가 2번 실행되므로, 등록 이벤트 에서는 event Deligation은 사용할 수 없을 것 같습니다 ㅠ

2022-04-11 08:27 UTC, herrakam commented on build/src/index.html
> +    <script type="module" src="./javascript/app.js"></script>
async는  문서 내 순서와 상관없이 먼저 다운로드 된 script가 먼저 실행되고, defer는 모든 script가 다운로드 된 후, 문서에 추가된 순서대로 실행된다는 걸 공부했습니다.  script가 ui 이벤트와 관련 있어서, script를 다운 받은 후 순서대로 실행하는 defer를 사용해 보기로 했습니다

2022-04-11 08:52 UTC, herrakam commented on build/src/javascript/util/util.js
> +}
1. then을 사용하지 않고 async와 await만 사용하는 걸로 변경했습니다!
```javascript
  const response = await axios.get(URL);
  const data = response.data;
  return data;
```
2. 이 데이터를 fetching 하는 함수를 다른 컴포넌트에서도 사용할 것 같아 util에 뒀었는데, 이렇게 util 함수는  아니지만 재사용성이 높은 함수는 어디에 두는게 좋을까요?

2022-04-11 08:53 UTC, herrakam commented on build/src/javascript/util/util.js
> +}
element로 교체했습니다!

2022-04-11 09:00 UTC, herrakam commented on build/src/javascript/view/cardView.js
> +}
돔요소의 text를 인자로 받는 걸로 변경 했고, 
함수 명도 `isTextLengthExceeded`으로 좀 더 구체적으로 변경했습니다!

2022-04-11 09:13 UTC, herrakam commented on build/src/javascript/view/cardView.js
> +}
init함수가 초기화시 동작하는 역할이 맞는데, 아직 init에서 실행되야 될 기능을 다 구현하지 않은 상태입니다.  플러스버튼에 이벤트를 등록 하는 내용을 따로 함수로 뺀 뒤 해당 함수를 init에서 실행하는 구조로 바꿨습니다
```javascript
function init() {
  addPlusBtnEvent();
}
```

2022-04-11 11:08 UTC, hongbiii commented on build/src/javascript/util/util.js
> +}
방법은 다양하겠지만, 저라면 api 디렉토리를 만들어 모아둘 것 같아요!
다른 사람들은 어떻게 쓰고 있는지 그리고 해당 주제에 대해서 동료들과 이야기를 나눠보는 것도 좋아요!