[team15][BE]민지노&테리 - 1주차 2차 PR
codesquad-members-2022/todo-list pull request #124
Opened 2022-04-08 11:04 UTC by mybloom

안녕하세요 민지노,테리입니다.
이번 PR에는 1차 리뷰 내용을 포함해 보내드립니다. 
미리 리뷰 감사합니다. 😀

---

## 1차 리뷰내용 반영
- 그룹명과 버젼 수정
- 그룹명에 맞게 패키지명 수정 

## 1주차 2차 개발 사항
- 서버구조 추가
- DB 설치가이드 추가
- Todo 목록조회 API 간단히 개발 

## 다음주 예상 작업
- 스프링을 공부하면서 개발 중이라 API 실행을 확인하기 위해 간단히 개발해 보았습니다. 
- 도메인객체에 setter를 없애고 DTO등을 적용해볼 생각입니다.

2022-04-12 01:34 UTC, wheejuni requested changes
수고 많으셨고 너무 늦게까지 기다리게 하여 대단히 죄송합니다;; ㅠㅠㅠ
간단한 의견 몇 개 남겼으니 확인 부탁드려요

2022-04-12 01:34 UTC, wheejuni commented on backend/plan/sql/todo_table_create_20220407.sql
> +  `password` VARCHAR(50) NULL,
`password` 가 `NULL` 인 것이 맞는지... 조금 의문이 들기는 하는군요.

2022-04-12 01:34 UTC, wheejuni commented on backend/src/main/java/com/team15/todoapi/controller/CardController.java
> +	@GetMapping("")
빈 큰따옴표 생략하셔도 됩니다.

```suggestion
        @GetMapping

2022-04-12 01:34 UTC, wheejuni commented on backend/src/main/java/com/team15/todoapi/controller/CardController.java
> +	public List<Card> cards(){
도메인 엔티티일 `Card` 가 그대로 내려가는 형태로 이해하면 될까요?
해당 클래스가 갖고 있는 모든 정보에 유저가 관심을 가져야 하나요? 
유저가 관심가져야 할 정보만 정제해서 내리는 형태이면 어떨까요?

2022-04-12 01:34 UTC, wheejuni commented on backend/src/main/java/com/team15/todoapi/domain/Card.java
> +	private Long member_id;
언더스코어는 자바 네이밍 컨벤션에 맞지 않습니다;
이렇게 하지 않고도 JSON 응답에 언더스코어를 내리는 방법이 있습니다. 정확히 말하면 카멜 케이스를 스네이크 케이스 등으로 변환하는 어댑터가 존재합니다. 이걸 한번 찾아보시죠.

2022-04-12 01:34 UTC, wheejuni commented on backend/src/main/java/com/team15/todoapi/repository/CardRepository.java
> +	public List<Card> findAll();
인터페이스의 추상 메소드에 접근제어자를 부여하는 건 중복 코드에 해당한다는 의견도 있습니다.
IDE에서도 해당 경고 노출되지 않던가요?

2022-04-13 04:45 UTC, Minzino commented on backend/plan/sql/todo_table_create_20220407.sql
> +  `password` VARCHAR(50) NULL,
처음에 값을 잘못 넣었던 것 같습니다 NOT NULL로 수정하겠습니다ㅎㅎ

2022-04-13 04:46 UTC, mybloom commented on backend/src/main/java/com/team15/todoapi/controller/CardController.java
> +	@GetMapping("")
네, PR에 수정하여 반영하겠습니다.

2022-04-13 04:47 UTC, Minzino commented on backend/src/main/java/com/team15/todoapi/controller/CardController.java
> +	public List<Card> cards(){
다음 pr때 CardDto로 바꿔보려고 계획중이었습니다!

2022-04-13 04:48 UTC, mybloom commented on backend/src/main/java/com/team15/todoapi/domain/Card.java
> +	private Long member_id;
처음 Card클래스 생성 할 때 DB의 컬럼을 그대로 긁어와서 언더스코어로 작성하게 되었네요. 
현재 카멜케이스로 변경하여 작업하고 있습니다.

2022-04-13 04:49 UTC, Minzino commented on backend/src/main/java/com/team15/todoapi/repository/CardRepository.java
> +	public List<Card> findAll();
넵 다음부터는 잘 적용하도록 하겠습니다!

2022-04-13 04:54 UTC, Minzino commented
좋은 리뷰 감사합니다. 브라이언!
급하게 하려다보니 고려하지 못한 부분과 자잘한 실수가 있었던 것 같습니다!
이번 리뷰 사항은 다음 pr때 좀 더 신경써서 제출하도록 하겠습니다.
이번 pr은 머지 부탁 드려요!

2022-04-13 07:55 UTC, merged