[team-03][BackEnd] todo-list 1주차 #2
codesquad-members-2022/todo-list pull request #125
Opened 2022-04-08 12:32 UTC by nohriter

안녕하세요 3조의 백엔드 개발을 맡은 짱민과 노리입니다 !!

Git관련 문제가 발생하여 해결과정에서 시간이 많이 지연되었습니다. 

PR시간을 지키지 못한점 정말 죄송합니다. 

진행상황은 아래와 같습니다.!

## 1차 리뷰내용 반영
- DTO 패키지 분리
- CardsResponse -> CardResponse로 변경
- CardsResponse DTO 생성 후 멤버변수로 Map객체 선언
- MockController의 getCards() 메서드 반환타입 Map -> CardsResponse로 변경

## 1주차 2차 개발 사항
- Card insert, remove 기능 추가
- EC2 Mysql 연결

리뷰 감사합니다!! 🙇

2022-04-09 12:56 UTC, ksundong requested changes
안녕하세요. 짱민 & 노리, 리뷰어 dion입니다.
다행히 메일을 둘러보던 와중이라 빠르게 리뷰가 가능했네요.
연결 리스트 방식에 대한 고민이 많으셨을텐데 고생많으셨습니다.
조금 아쉬운 부분이 있어서 변경요청 드립니다. 일요일에도 코딩을 하셔야겠지만 하나하나 해결해보시면서 학습하시는 부분이 있길 바랍니다~

2022-04-09 12:56 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/controller/dto/CardAddFormRequest.java
> +    @NonNull
spring의 `@NonNull` 말고 JSR-380 Validation을 적용해주시는걸 더 추천드립니다.

2022-04-09 12:56 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/controller/dto/CardAddFormRequest.java
> +    }
기본 생성자는 왜 만들어주셨나요?

2022-04-09 12:56 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/controller/dto/CardAddFormRequest.java
> +                LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")),
왜 시간을 이렇게 넣어줘야 했나요?

2022-04-09 12:56 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/controller/dto/CardAddFormRequest.java
> +        return card;
굳이 변수로 추출해서 리턴할 필요는 없어보이긴 하네요~~

2022-04-09 12:56 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/controller/dto/CardAddFormRequest.java
> +                "0");
이 각각의 리터럴들은 변수로 추출하는 편이 가독성이 더 높겠네요.

2022-04-09 12:56 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/controller/dto/CardResponse.java
> +        this.cardId = cardId;
굳이 card라고 아는 상태라면 `card` 는 빼는편이 `nextId`와 합이 맞을 것 같네요.

2022-04-09 12:56 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/controller/dto/CardResponse.java
> +    private String uploadDate;
왜 `Date` 인데 `String` 타입을 사용해주셨나요?

2022-04-09 12:56 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/controller/dto/CardsResponse.java
> +    }
왜 하나하나 넣는 방식을 선택해주셨나요??
생성시점에 만들어진 상태여도 괜찮을 것 같은데요..!

2022-04-09 12:56 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/controller/CardController.java
> +    public Long addCard(@Validated @ModelAttribute CardAddFormRequest cardAddFormRequest) {
`@Validated`, `@ModelAttribute` 는 언제 사용하는 것인지 학습해보시고 공유해주세요!

2022-04-09 12:56 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/controller/CardController.java
> +    @DeleteMapping("/card/{card_id}")
굳이 `card_id`를 사용하지 않으셔도 괜찮습니다. path variable은 우리만 보니까 `cardId` 여도 됩니다.

2022-04-09 12:56 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/controller/MockController.java
> +//    }
굳이 사용하지 않을 코드라면 지워주세요.

2022-04-09 12:56 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/controller/MockController.java
> +        historiesResponse.addHistory(historyResponse21);
너무 지저분하게 add하는 것 같아요. 사용성이 떨어져 보이는데요. 생성자를 하나 정의해보시죠 ㅎㅎ

2022-04-09 12:56 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/domain/Card.java
> +    }
생성자는 일반적으로 메서드들 위에 위치하는 것이 자바 Convention 입니다.

2022-04-09 12:56 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/domain/Card.java
> +    private String uploadDate;
`Date`를 `String` 타입으로 핸들링 하는 이유가 있을까요?

2022-04-09 12:56 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/domain/Card.java
> +    private String deleted;
`deleted` 인데 `String` 타입인 이유는 무엇일까요?

2022-04-09 12:56 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/repository/CardRepository.java
> +    @Autowired
여기 `@Autowired` 는 생략가능해 보이는데, 추가해주신 이유는 무엇인가요?

2022-04-09 12:56 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/repository/CardRepository.java
> +    @Transactional
`@Repository` 에서 왜 `@Transactional` 이 필요했나 했더니, 연결리스트 형식의 연산을 수행해주기 위함이군요..

2022-04-09 12:56 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/repository/CardRepository.java
> +                + card.getCurrentLocation() + "'";
왜 `String` 의 `+` 연산을 사용해 쿼리를 만들어주셨나요?
SQL Injection에 대해서 공부해보시길 바랍니다.

2022-04-09 12:56 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/repository/CardRepository.java
> +        String updateNextCardOfLastCardSQL = "update card set next_id = ? where card_id = ?";
요건 굳이 로컬변수로 관리될 필요는 없어보이네요.

2022-04-09 12:56 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/repository/CardRepository.java
> +        }
이런 방식의 예외처리는 좋지 않습니다. 의도하고자 한 것이 무엇인가요?

2022-04-09 12:56 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/repository/CardRepository.java
> +        String SQL4 = "update card set next_id = ? where card_id= ?";
흠.. 변수명은 아직 다듬어지지 않았나보군요.

2022-04-09 12:56 UTC, ksundong commented on backend/todo-app/src/main/resources/application.properties
> +spring.profiles.include=mysqlAWS
이건 무슨 의미인가요??

2022-04-09 12:56 UTC, ksundong commented on backend/todo-app/src/test/java/team03/todoapp/repository/CardRepositoryTest.java
> +    }
직접 만들지 않아주셔도 됩니다.

2022-04-09 12:56 UTC, ksundong commented on backend/todo-app/src/test/java/team03/todoapp/repository/CardRepositoryTest.java
> +//    @Transactional
왜 주석처리 해주셨나요/

2022-04-09 12:56 UTC, ksundong commented on backend/todo-app/src/test/java/team03/todoapp/repository/CardRepositoryTest.java
> +        cardRepository.insert(card);
테스트에 assertion이 없네요.

2022-04-11 01:40 UTC, leezzangmin commented on backend/todo-app/src/main/java/team03/todoapp/controller/dto/CardAddFormRequest.java
> +    @NonNull
네 알겠습니다. @Notnull 으로 변경해보겠습니다

2022-04-11 01:46 UTC, nohriter commented on backend/todo-app/src/main/java/team03/todoapp/controller/dto/CardAddFormRequest.java
> +    }
여기서 기본생성자는 없어도 될 것 같습니다😅

2022-04-11 02:01 UTC, leezzangmin commented on backend/todo-app/src/main/java/team03/todoapp/controller/dto/CardAddFormRequest.java
> +                LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")),
시간을 String으로 관리하지 않고 LocalDateTime으로 관리한 후,
DB에 넣거나 Json으로 리턴할 떄만 format을 적용해 관리하는 식으로 가겠습니다

2022-04-11 02:02 UTC, leezzangmin commented on backend/todo-app/src/main/java/team03/todoapp/controller/dto/CardAddFormRequest.java
> +        return card;
생성한 후 바로 return 하도록 하겠습니다

2022-04-11 02:02 UTC, leezzangmin commented on backend/todo-app/src/main/java/team03/todoapp/controller/dto/CardAddFormRequest.java
> +                "0");
작은 부분이라 고민하지 않았는데 적용해보도록 하겠습니다.

2022-04-11 02:03 UTC, leezzangmin commented on backend/todo-app/src/main/java/team03/todoapp/controller/dto/CardResponse.java
> +        this.cardId = cardId;
cardId -> id로 변경하도록 하겠습니다

2022-04-11 02:03 UTC, leezzangmin commented on backend/todo-app/src/main/java/team03/todoapp/controller/dto/CardResponse.java
> +    private String uploadDate;
LocalDateTime으로 관리하도록 하겠습니다

2022-04-11 02:06 UTC, leezzangmin commented on backend/todo-app/src/main/java/team03/todoapp/domain/Card.java
> +    private String uploadDate;
LocalDateTime으로 관리하도록 하겠습니다

2022-04-11 02:08 UTC, leezzangmin commented on backend/todo-app/src/main/java/team03/todoapp/domain/Card.java
> +    private String deleted;
Mysql에 "0"을 넣어야 false로 간주되는데, boolean으로 하자니 여의치 않아 일단 String으로 선언했습니다.
이제는 boolean으로 관리하도록 하겠습니다.

2022-04-11 02:17 UTC, leezzangmin commented on backend/todo-app/src/main/java/team03/todoapp/repository/CardRepository.java
> +    @Autowired
학습 단계라 가독성을 위해 남겨 둔 부분이 있습니다. 추후 제거하도록 하겠습니다

2022-04-11 02:18 UTC, leezzangmin commented on backend/todo-app/src/main/java/team03/todoapp/repository/CardRepository.java
> +                + card.getCurrentLocation() + "'";
급하게 만드느라 박아 넣은 부분이 있네요.
SQL inject을 통해 수정하도록 하겠습니다

2022-04-11 02:41 UTC, leezzangmin commented on backend/todo-app/src/main/java/team03/todoapp/repository/CardRepository.java
> +        }
저희 작성 의도는 select 쿼리를 요청한 후 결과값의 행이 하나도 없으면 lastCardId에 null이 유지되는 것이었습니다. 예외가 터지면 null이 갱신되지 않고 남아있게 되는 코드입니다.

단순히 예외를 받기 위한 try-catch 문이었는데,
흐름상 무언가 코드가 있어야 읽기 편할 것 같습니다.

'''
        Integer lastCardId = null;

        try {
            lastCardId = jdbcTemplate.queryForObject(getLastCardIdSQL, Integer.class);
            log.debug("lastCardId: {}", lastCardId);
        } catch (EmptyResultDataAccessException e) {
            log.debug("e: {}", e);
        }
'''
에서

'''
        Integer lastCardId;

        try {
            lastCardId = jdbcTemplate.queryForObject(getLastCardIdSQL, Integer.class);
            log.debug("lastCardId: {}", lastCardId);
        } catch (EmptyResultDataAccessException e) {
            lastCardId = null;
            log.debug("e: {}", e);
        }

'''
이렇게 수정하면 괜찮을까요?

사실 질문의 의도를 정확히 파악하지 못해 임의대로 수정했는데
추가로 코멘트 달아주시면 감사하겠습니다!

2022-04-11 02:42 UTC, leezzangmin commented on backend/todo-app/src/main/java/team03/todoapp/repository/CardRepository.java
> +        String SQL4 = "update card set next_id = ? where card_id= ?";
좋은 변수명을 고민해보겠습니다

2022-04-11 02:43 UTC, leezzangmin commented on backend/todo-app/src/main/resources/application.properties
> +spring.profiles.include=mysqlAWS
DB 접속정보를 github에 올리지 않기 위해서
로컬 프로필 파일 application-mysqlAWS.properties를 생성하고 application.properties 에서 참조하는 부분입니다.
더 좋은 방법이 있을까요?

2022-04-11 02:44 UTC, leezzangmin commented on backend/todo-app/src/test/java/team03/todoapp/repository/CardRepositoryTest.java
> +    }
급하게 만드느라 이상한 코드가 있네요 지우겠습니다

2022-04-11 02:45 UTC, leezzangmin commented on backend/todo-app/src/test/java/team03/todoapp/repository/CardRepositoryTest.java
> +//    @Transactional
테스트 메서드가 더미 데이트를 넣는 용도로 잠깐 사용되어 주석처리 되었습니다. 테스트 완성 후 다시 넣도록 하겠습니다

2022-04-11 02:45 UTC, leezzangmin commented on backend/todo-app/src/test/java/team03/todoapp/repository/CardRepositoryTest.java
> +        cardRepository.insert(card);
아직 테스트가 불완전해서 잘 작동하는지 눈으로 확인하는 테스트입니다. 추후 완성도 높은 테스트를 완성하겠습니다

2022-04-11 08:19 UTC, nohriter commented on backend/todo-app/src/main/java/team03/todoapp/controller/CardController.java
> +    public Long addCard(@Validated @ModelAttribute CardAddFormRequest cardAddFormRequest) {
간단하게 정리해 보았습니다! 🙏

****`@ModelAttribute`****

: `@ModelAttribute`는 사용자가 요청(HTTP 파라미터)시 전달하는 값을 오브젝트 형태로 매핑해주는 어노테이션입니다. 값을 매핑해야하기 때문에 객체의 필드에 접근해 데이터를 바인딩할 수 있는 생성자 혹은 setter 메서드가 필요하며 Query String 및 Form 형식이 아닌 데이터는 처리할 수 없습니다.

**`@Validated`**

: `@Validated`는 서버측에서 request 데이터를 바인딩할때, 데이터가 유효한지(ex. 누락, 최대 크기 초과 등) 유효성 검사를 위해 사용됩니다. 주로 컨트롤러를 `@ModelAttribute` 모델에 바인딩하는 데 사용하며, `@Valid`의 기능을 포함합니다. `@Valid`와 달리 `@Validated` JSR 표준 기술이 아닌 Spring 프레임워크에서 제공하는 어노테이션이며 검증 항목을 그룹으로 나눠서 검증하는 Group Validation의 차이가 있습니다.

`질문`

학습과정에서 추가적으로  궁금한 부분이 생겼는데요!  스프링에서 제공하는 어노테이션과 자바표준 어노테이션중에서 어떤걸 쓰는게 좋은걸까? 라는 궁금점이 생겼습니다. 제 생각으로는 이미 스프링에 의존적인 코드가 많아서 스프링에서 제공하는 걸 써도 문제가 없을 것 같은데 어떤 기준으로 선택해야 하는지 궁금합니다!🙇

2022-04-11 14:12 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/controller/dto/CardAddFormRequest.java
> +                LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")),
DB에 넣을 때에는 왜 String으로 저장해야하나요??

2022-04-11 14:15 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/controller/CardController.java
> +    public Long addCard(@Validated @ModelAttribute CardAddFormRequest cardAddFormRequest) {
자 일단 modelattribute는 그러면 뻬야될까요? 남아있어도 될까요?
질문에 대한 답의 경우는 제가 생각하기엔 확장된 기능이 필요하면 스프링의 것을 쓰고 아니면 표준을 쓰시면 됩니다.
어찌 되었든 표준은 표준이니까요😊

2022-04-11 14:19 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/repository/CardRepository.java
> +        }
try catch 없이 처리하는 방법은 없던가요??
List로 조회해와서 Optional을 만들어주는 방법도 있을 것 같습니다.
의도된 예외무시라면 왜 그 예외를 무시했는지도 주석으로 남겨주는게 좋겠죠.

2022-04-11 14:20 UTC, ksundong commented on backend/todo-app/src/main/resources/application.properties
> +spring.profiles.include=mysqlAWS
제가 왜 이걸 리뷰를 남겼을까요 ㅋㅋㅋ
이름이 mysqlAWS라서 뭔가 aurora랑 헷갈렸나봅니다. 잘 처리해주셨네요👍

2022-04-11 14:25 UTC, nohriter commented on backend/todo-app/src/main/java/team03/todoapp/controller/CardController.java
> +    public Long addCard(@Validated @ModelAttribute CardAddFormRequest cardAddFormRequest) {
가장 중요한 결론적인 부분을 빠트려 뒤늦게 수정했는데 너무 늦었네요 😭
따라서 현재는 클라이언트와에게 파라미터가 아닌 JSON로 요청을 받기 때문에 `@ModelAttribute` 가 아니라 `@RequestBody` 를 사용하도록 수정하는 것이 맞다고 생각됩니다! 질문에 대한 답변 감사드립니다 !

2022-04-11 14:46 UTC, ksundong approved these changes
고생하셨습니다~ 이번주도 화이팅이에요~~

2022-04-11 14:46 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/controller/dto/CardResponse.java
> +    }
요거는 get이 안붙어도 되나요??

2022-04-11 14:46 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/domain/Card.java
> +    private Long cardId;
여기는 그대로 cardId군요?

2022-04-11 14:46 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/domain/Card.java
> +    private Boolean deleted;
일반적으로 `boolean` 타입에는 `is~`를 붙여주는 편입니다.
그리고 왜 `Boolean` 으로 설정해주셨나요?

2022-04-11 14:46 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/controller/MockController.java
> +    }
음 ㅋㅋㅋㅋ 이건 아닌 것 같아요...

2022-04-11 14:46 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/controller/MockController.java
> +    public void delete(@PathVariable int card_id) {
여기는 변수명도 컨벤션과 맞지 않네요.

2022-04-11 14:46 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/controller/dto/CardAddFormRequest.java
> +    public Card toCardEntity() {
`toEntity` 정도면 충분할 듯 합니다.

2022-04-11 14:46 UTC, merged

2022-04-11 14:50 UTC, leezzangmin commented on backend/todo-app/src/main/java/team03/todoapp/controller/dto/CardAddFormRequest.java
> +                LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")),
오호 생각해보니 DB에 넣을 때 파싱해서 String타입으로 넣게되면 
빼올때도 다시 파싱해서 처리를 해야한 후 데이터를 제공해야 했네요
그냥 바로 넣도록 하겠습니다.
뭔가 DB에는 String같은 데이터가 들어가야 할 것 같은 고정관념이 있었습니다...

2022-04-11 14:51 UTC, leezzangmin commented on backend/todo-app/src/main/java/team03/todoapp/controller/dto/CardsResponse.java
> +    }
최대한 빨리 mock API를 제공하려다 보니 익숙한 방법으로 구현했던 것 같습니다.
실제 api를 개발할 때 개선해보겠습니다.

2022-04-11 14:54 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/controller/dto/CardAddFormRequest.java
> +                LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")),
DB에 저장될 수 있는 데이터 타입을 알아보시는걸 추천드려요~

2022-04-11 14:54 UTC, leezzangmin commented on backend/todo-app/src/main/java/team03/todoapp/repository/CardRepository.java
> +    @Autowired
혹시 @Autowired를 생략한 경우에도 넣었을 경우의 단점이 있을까요?
현업에서는 어떻게 사용하는지도 궁금합니다.
개인적으로 학습을 막 시작한 입장에서 보면, @Autowired가 있으면 스프링이 명시적으로 관계를 맺어준다는 느낌이 한번에 들어서 좋은 것 같습니다.

2022-04-11 14:56 UTC, leezzangmin commented on backend/todo-app/src/main/java/team03/todoapp/controller/dto/CardResponse.java
> +    }
앗.... 생각없이 수작업으로 수정하다가 get이 빠졌네요 수정하도록 하겠습니다

2022-04-11 14:56 UTC, leezzangmin commented on backend/todo-app/src/main/java/team03/todoapp/domain/Card.java
> +    private Long cardId;
아이고 신경쓰지 못한 부분이 많네요 수정하겠습니다..

2022-04-11 14:57 UTC, leezzangmin commented on backend/todo-app/src/main/java/team03/todoapp/controller/MockController.java
> +    }
솔직히 구현하면서도 아닌 것 같다는 생각을 했습니다..
이건 최우선순위로 수정해보겠습니다..

2022-04-11 15:30 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/repository/CardRepository.java
> +    @Autowired
단점은 이제 `@Autowired`는 사실 애노테이션이기 때문에 코드에 영향을 주는 내용이 담긴다는 점이 문제라고 볼 수 있습니다.
보통 필요한 경우 아니면 제외하는 것이 최근의 추세입니다.
스프링을 먼저 배웠느냐, 객체지향을 먼저 배웠느냐의 차이라고 생각하시면 좋을 것 같아요.

2022-04-11 15:31 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/controller/dto/CardResponse.java
> +    }
가급적이면 getter setter 생성자 equals & hashCode는 인텔리제이에서 Mac 기준 Cmd + n 을 누르면 생성할 수 있으니 이걸 이용해보세요~~

2022-04-12 08:23 UTC, nohriter commented on backend/todo-app/src/main/java/team03/todoapp/domain/Card.java
> +    private Boolean deleted;
깊은고민없이 Null을 고려해서 Card 객체 변수들에 Wrapper 타입을 사용했는데 deleted의 경우 null 값이 들어올 경우는 없는 것 같습니다. 😇
deleted 외 다른 값들도 primitive으로 변경할 수 있는지 고민 해보겠습니다!!

2022-04-12 13:57 UTC, ksundong commented on backend/todo-app/src/main/java/team03/todoapp/domain/Card.java
> +    private Boolean deleted;
네 항상 Nullable 은 고민을 하고 넣어주세요~~