[Team-02][BE] 1주 - 3차 PR
codesquad-members-2022/todo-list pull request #126
Opened 2022-04-09 01:08 UTC by sally-ksh

POST 요청에 로직 추가와 개선해서 보내봅니다.

- PRG 패턴 적용
- insert 로직 실행시 order 값 DB 통한 실행으로 변경

2022-04-09 08:15 UTC, Hyune-c requested changes
수정 요청드릴 것이 꽤 많네요..
핵심 기능 구현을 우선하는 것을 고려해주세요.

- card의 order에 user과 관계 있나요? Dao에 코멘트를 달았습니다.
- 테스트 코드가 하나도 없어서 그런가 의도를 이해하는게 좀 힘드네요. 
아직 기능이 거의 없는 상태이니 테스트 코드 작성 바랍니다.
- 전체적으로 가독성을 위한 개행이 부족합니다.
    - 메서드도 10줄이 넘어가면 분리 또는 개행해야 된다고 생각해주세요.
    - given when then 으로 생각하시면 도움이 될 것 같습니다.
- 아직 핵심 기능이 충분하지 않은데 부가 기능을 고민해야될까요?
    - PRG 패턴의 경우 중복 생성을 막는 패턴으로 상당히 예외적입니다. 
    - 어설프게라도 핵심 기능을 먼저 만드시고, 테스트 케이스를 추가해가면서 예외를 처리하시면 좀 더 빠른 구현이 될 것 같습니다.

2022-04-09 08:15 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardApiController.java
> +	}
재미있는거 하시네요. 
동시성 처리와도 연결될 수 있고, 실무와 연관하면 더 많은 얘기를 할 수 있는 주제이네요.
단계별로 생각해볼 수 있는 키워드를 드릴테니 같이 얘기해보시죠.

참고로 저는 이런 흐름에 대해서는 익히 알고 있었지만, PRG 패턴이란 명칭은 처음 들었고 실무에서는 다른 방법으로 적용했었습니다.

1. 중복 생성 제한을 하는 다른 방법은 무엇이 있을까?
2. redirect 판단의 주체가 서버여야 하는가?
   1. 참고로 readme 에는 `GET /{user-id}/card/{id}` 로 쓰여있지만
   2. getRedirectUri에는 `/api/todo/%d/card/%d` 로 기록되어 있습니다.

2022-04-09 08:15 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardApiController.java
> +	private String getRedirectUri(CardDto.RedirectInfo response) {
Info라는 네이밍에 대해 좀 더 고민해봅시다.

https://velog.io/@dnr6054/Clean-Code-2-%EC%9D%98%EB%AF%B8-%EC%9E%88%EB%8A%94-%EC%9D%B4%EB%A6%84

2022-04-09 08:15 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/Card.java
> +		this.order = maxTodoOrder;
메소드는 next를 말하고 있는데, 매개변수는 명확하게 받고 있네요.

- next를 살리려면 매개변수가 없어야 되고
- max를 살리려면 setOrder로 되야지 않을까요?

2022-04-09 08:15 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardApiController.java
> +		return String.format("/api/todo/%d/card/%d", response.getUserId(), response.getTodoId());
redirect의 도착지는 새로 생긴 특정 card일 것으로 추정되는데, userId도 필요한건가요?

2022-04-09 08:15 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardService.java
> +		String errorMessage = String.format("error of card id: %dor user id: %d", id, userId);
매서드 호출마다 string을 만들지 않으려면 어떤 방법이 있을까요?

2022-04-09 08:15 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDao.java
> +	public static final String ERROR_OF_TODO_ID = "error of todoId";
상수 개수가 이 정도가 되면 좀 더 정리할 수 있는 방법을 생각해보는 것이 좋을 것 같습니다.
또는 비슷한 성격끼리 구분할 수 있도록 개행이라도 넣는 것이 가독성에 도움이 됩니다.

2022-04-09 08:15 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDao.java
> +	 */
적절한 주석 좋네요. 👍

`nit`
이왕 작성하는 것이라면 javadoc 형태는 어떤가요?
quick document에 보여서 좀 더 가독성에 도움을 줍니다.

2022-04-09 08:15 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDao.java
> +	public static final long ADDED_NEXT_ORDER = 1L;
이게 뭘까요.. 잘 이해가 안되서 그러는데 변수명 변경이 어려운 것이라면 한글 주석 정도는 있으면 좋겠습니다.

2022-04-09 08:15 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDao.java
> +	private long getMaxTodoOrder(Long userId, String todoStatus) {
order를 체크하는데 있어 userId가 왜 필요한 걸까요?

제가 분석한 업무 요건은 아래와 같습니다. 

- todoStatus 3종류를 카테고리로 간주한다.
- 카테고리별로 독립적인 order를 가진다.
- 따라서 userId와는 무관하다.

2022-04-09 09:43 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/Card.java
> +		this.order = maxTodoOrder;
네,
세션때 말씀주셨던 부분인것도 같아요.
저는 메시지로서 인터페이스(오퍼레이션..) 이라고 생각하면서 들었는데요.
문맥상 의미와 기능으로 가독성 등을 좀 더 확인하면서 작업하도록 하겠습니다.

setOrder() 로 변경 하겠습니다.

2022-04-09 09:47 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardApiController.java
> +		return String.format("/api/todo/%d/card/%d", response.getUserId(), response.getTodoId());
실제로는 todoId만으로 특정 card가 맞습니다.
사용자가 요청한 카드 데이터가 맞음을 확인 하는게 좋지 않을까... 생각이었습니다.
테이블에서 카드 생성은 기본키가 id 이지만 userId 별로 추가되게 되다보니...
그걸 맞춰줘야 하나 싶었는데요.

혹시, 이부분도 영속성 부분이  상위 레이어로 나온 예일까요?
개인적으로 너무 생각 간 것도 같은 부분이었습니다. ^^

2022-04-09 09:48 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/Card.java
> +		this.order = maxTodoOrder;
만약 setOrder()가 낫다고 판단하신거라면 매개변수 명도 수정해야될거 같아요.
set은 어디에나 들어갈 수 있는 것인데, 꼭 max일 이유는 없겠죠.

2022-04-09 09:48 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDao.java
> +	 */
넵, 감사합니다. ^^

2022-04-09 09:50 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDao.java
> +	public static final long ADDED_NEXT_ORDER = 1L;
위에 insert 시 default 1 의 값이 되거나, 다음 order를 위해  +1로 되어주는 상수입니다. 
저도 얘매하다 싶고, 어려울땐 주석을 달도록 하겠습니다.
감사합니다.

2022-04-09 09:51 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardApiController.java
> +		return String.format("/api/todo/%d/card/%d", response.getUserId(), response.getTodoId());
제가 샐리의 생각을 정확히 알지 못해서 그런데, card와 todo의 관계를 그림 등으로 설명 가능할까요.
관계가 모호하다보니 생각이 엇갈리는거 같네요.

번외지만 저라면 todo개념 없이 card라는 개념 하나로 모든 것을 했을 것 같아요.

2022-04-09 09:54 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDao.java
> +	private long getMaxTodoOrder(Long userId, String todoStatus) {
안드로이드 쪽에서 하드코딩한 사용자 값을 갖게 하는 걸로 알고 있습니다.
로그인이나 다른 사용자를 추가하는 것은 아니지만,
저희끼리는 하나의 사용자를 공통으로 쓰더라도 전달받아보자고 얘기가 돼서,
저는 todo_users_table 을 만들고, card 테이블에 FK 로 해놨습니다.

 order 추가시에는 userId별 todoStatus가 각각 가지는 order를 조회하게 작업했습니다.
.... 괜찮을까요? 요구사항을 크게 벗어나진 않는다고 생각했지만... ㅎㅎㅎㅎ

분석 예시 감사합니다 👍

2022-04-09 10:05 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardApiController.java
> +	private String getRedirectUri(CardDto.RedirectInfo response) {
Redirection 으로 수정하겠습니다.

보여주신 자료에서는 info 가 좋지 않다고 나오는데,
 서비스레이어에서 dto에 의해 반환된 Card 객체와 DB 조회해온 Card 객체의 네이밍 구분은 있으면 
좋을 것 같다는 생각이 들어서 
이번에 작업하면서 -info는 개인적으로 DB로부터 조회해온 객체에게 접두어로
공통으로 활용하는 방향으로 잡아보고자 생각인데 괜찮을까요?

2022-04-09 10:12 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardApiController.java
> +	private String getRedirectUri(CardDto.RedirectInfo response) {
네. dto 역시도 말씀하시는 개념에서 나온 접미사 중 하나입니다.
사실 저 글에서는 info를 쓰지 말라고 하지만 개인적으로는 내부적 합의를 전제로 어느정도는 써도 된다고 생각합니다.
실제로 info 정도는 실무에서도 쓰이긴 하구요.

다만 이런 경우에는 모호함을 명확하게 하기 의해 주석을 다는 것을 추천합니다.

---

혹자는 주석을 달바에는 명확한 네이밍을 하라고 하지만, 한글과 영문에서 나오는 미묘한 늬앙스 차이나 개인의 생각 차이에서 나오는 모호함은  합의의 대상이라고 생각합니다.

2022-04-09 10:13 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardService.java
> +		String errorMessage = String.format("error of card id: %dor user id: %d", id, userId);
일단.. 상수화 하겠습니다.....

2022-04-09 10:16 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardApiController.java
> +	private String getRedirectUri(CardDto.RedirectInfo response) {
네, 감사합니다 ^^

2022-04-09 10:17 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDao.java
> +	private long getMaxTodoOrder(Long userId, String todoStatus) {
구현 요건 중에 인증이 있는 것으로 아는데 인증 구현은 패스하시는 걸까요?

만약 인증을 구현하면.

- 내 카드는 인증 정보에서 userid를 가져올 수 있다.
- 타인의 카드를 위해서는 userid를 queryparam으로 방을 수 있다.
    - 즉 path에 들어갈 필요는 없다.

2022-04-09 10:18 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/Card.java
> +		this.order = maxTodoOrder;
아... 그렇네요.
감사합니다 🥇

2022-04-09 10:27 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDao.java
> +	private long getMaxTodoOrder(Long userId, String todoStatus) {
네. 조금 더 진행되는 것을 코멘트 드릴게요.
테스트 케이스가 있으면 흐름 이해가 좀 더 잘 될거 깉습니다.

2022-04-09 10:49 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardApiController.java
> +		return String.format("/api/todo/%d/card/%d", response.getUserId(), response.getTodoId());
네, 제 표현에도 애매한 부분이 있었네요.
DB의  todo와 스프링에서 Card로 분리하고자 생각한 부분이었는데요.

Dan 이 꼼꼼이 짚어주셔서, 
저번 리뷰에서 todo 붙은 애매한 부분들 많이 때어냇었는데,.
제가 남겨둔부분이 있는거 같아요. 
이번에 todoId도 cardId로 고치는게 좋겠다는 생각이 들었습니다.

또 저희가 스프링에서 작업시에는 잘 적용할 수 있게 해야겠다는 생각이 들어서
일단 README에 아래 표처럼 정리해서 추가해봤습니다. 

| server         | DB      |
|----------------|---------|
| cardId| todo_id |
| subject | subject |
| content | content |
| status | todo_status |
| order | todo_order |
| deleted | writing_date |
| createdAt | deleted |
| userId | todo_user_id |

2022-04-09 11:15 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardApiController.java
> +	}
음....😅

1번에 대해서
- 로그인 같은 경우는 unique 한 값을 조회 확인 후 중복이 없을시 저장 되도록 했던 방법일까요?
  - Card 생성시 담기는 제목, 내용으로는
    - 동일 내용의 중복 확인 결과가 일정 개수 이상인지 등 체크 일까요?
    - unique 범위를 todo_list_table 에서 subject, content 로 묶을까요?
  - 동일 사용자의 일정 시간내 요청 회수 확인 ? ㅎㅎ...
  - ajax에서 비동기적으로 요청이 일어나고, timeout 등의 예시들을 봤습니다.
    - [예시](https://coding-restaurant.tistory.com/227) 

2번에 대해서
- PRG 검색해보면서 ajax에서 redirect를 보내주는 예시를 본 적 있습니다. 
   - 클라이언트에서 POST 요청에 대한 서버의 응답 결과를 통해 redirect 판단 후
   - 서버가 리다이렉트로 올 요청 처리에 대한 응답을 해주도록, 
   - redirect 판단의 주체는 클라이언트 라고 생각하게 됐습니다.... (리다이렉트 걷어내나요? ㅎㅎㅎㅎ)

2022-04-09 14:59 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardApiController.java
> +	}
> 로그인 같은 경우는 unique 한 값을 조회 확인 후 중복이 없을시 저장 되도록 했던 방법일까요?
Card 생성시 담기는 제목, 내용으로는
동일 내용의 중복 확인 결과가 일정 개수 이상인지 등 체크 일까요?
unique 범위를 todo_list_table 에서 subject, content 로 묶을까요?
동일 사용자의 일정 시간내 요청 회수 확인 ? ㅎㅎ...
ajax에서 비동기적으로 요청이 일어나고, timeout 등의 예시들을 봤습니다.

- `중복 생성의 제한` 이라는 키워드는 결국 이 요청이 `중복 요청`이냐? 아니냐?를 걸러낼 수 있는 판단이라고 생각합니다.
- 이 관점에서 subject, content가 같은 카드는 생성되면 안될까요? 
    - 일반적이지는 않지만 사용자가 의도적으로 제목과 내용이 같은 카드를 생성할 수도 있지 않을까요?
- 동일 사용자의 일정 시간내 요청 회수 확인 ? ㅎㅎ...
    - 좋은 접근 입니다. `너무 짧은 시간의 연속 요청을 무시한다`라는 판단을 어디에서 하면 좋을까요?

> PRG 검색해보면서 ajax에서 redirect를 보내주는 예시를 본 적 있습니다.
클라이언트에서 POST 요청에 대한 서버의 응답 결과를 통해 redirect 판단 후
서버가 리다이렉트로 올 요청 처리에 대한 응답을 해주도록,
redirect 판단의 주체는 클라이언트 라고 생각하게 됐습니다.... (리다이렉트 걷어내나요? ㅎㅎㅎㅎ)

- `redirect 판단의 주체는 클라이언트 라고 생각하게 됐습니다` 
    - 근데 지금 redirect의 판단을 서버가 302로 주고, 리다이렉트 url도 주고있지 않나요?
    - 그렇다면 판단을 서버가 하고 있는 것이 아닐까요?

---

지금 이 주제는 정답이 없습니다.
하지만 저는 REST API라는 관점에서 조금 더 최신의 것을 말하고 있습니다.
결론적으로 두 가지 모두 아시는 것이 실무에서 부딪혔을 때 좀 더 좋은 판단을 하실 수 있을 것입니다.

2022-04-09 14:59 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardApiController.java
> +		return String.format("/api/todo/%d/card/%d", response.getUserId(), response.getTodoId());
네. 조금 더 진행되는 것을 코멘트 드릴게요.
테스트 케이스가 있으면 흐름 이해가 좀 더 잘 될거 깉습니다.

2022-04-09 15:00 UTC, Hyune-c approved these changes

2022-04-10 06:30 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardApiController.java
> +		return String.format("/api/todo/%d/card/%d", response.getUserId(), response.getTodoId());
여러생각 들을 코드로 그냥 넣었던거 같아요ㅎㅎ

로그인 경우든... interceptor 분리한다든가 그런식으로 나뉘어지면,
Conteroller에서 처리할거고, Service 까지 안 올거 같고..
그런 생각하다가 user-id 제거 했습니다.

2022-04-10 06:37 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardApiController.java
> +	}
`너무 짧은 시간의 연속 요청을 무시한다`

로그인 사용자 별로 처리한다면, interceptor로 처리하지 않을까.. 조심히 생각해봅니다. 

이번에 협업하면서, 제가 BE 라는걸 느끼기 시작한 거 같아요.
현재는 안드로이드만 있는데, 다른 클라이언트까지 있으면.... ㅎㅎㅎ
대답하긴 어렵지만 ㅠ
관련 정보나 경험은 많이 듣고 싶습니다. 
좋은 조언 감사합니다. 🥇

2022-04-10 06:52 UTC, Hyune-c approved these changes
고민해서 고치신 흔적이 보입니다.  👍 
핵심 기능 구현을 우선적으로 구현하며 테스트에 신경써주세요.
클린코드를 하고 네이밍을 고민하면 할수록 좀 더 좋은 구현이 나오실 수 있을 것입니다.

2022-04-10 06:52 UTC, Hyune-c commented on backend/todolist/src/test/java/kr/codesquad/todolist/card/CardServiceTest.java
> +	@DisplayName("카드 등록 요청시 전달받은 카드정보를 DB에 저장되고, 생성된 card-id를 확인한다.")
이렇게 흐름에 따른 테스트 의도를 한글로 적어주시는 건 아주 좋은 습관입니다. 
차후 리팩토링하거나 다른 개발자에게도 큰 도움이 될거에요. 👍

단점으로는 `DisplayName`의 한글 문장을 메서드명과 일치시키기 위해 영작해야 된다는 점인데..
개인적인 의견으로는 팀 합의하에 `테스트 코드의 메서드명은 크게 신경쓰지 않는다`로 했던 적이 있습니다.
별로 중요하지 않은 부분을 고민하고 싶지 않았었어요 ㅋㅋ

2022-04-10 06:52 UTC, Hyune-c commented on backend/todolist/README.md
> +| userId         | todo_user_id         |
card 생성 기능을 만드시면서 이제 erd에 대해 좀 더 명확한 그림이 생기셨을 거 같아요.
아마 실무를 가시면 erd를 자주 보게 되실텐데요. 지금부터 그려보시는 것을 추천합니다.
물론 entity를 만들고 intellij에서 지원해주는 diagram으로 추출하는 방법도 있긴 하지만, 설계부터 하기위해서는 어느정도 erd 툴에 익숙해지면 좋습니다.

https://www.erdcloud.com/

---

혹자는 도메인과 DB가 분리되는 설계를 해야한다고 말하지만, 아직 대부분의 회사들은 그 경계가 모호합니다.
이런 생각을 구현하려면 DDD나 아키텍처 분리까지도 알아야되는데 지금은 추천드리지 않습니다.

2022-04-10 06:52 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardService.java
> +		String errorMessage = String.format(ERROR_OF_CARD_ID, id);
`nit`
- 이것은 아마 lambda의 function을 이용하면 좀 더 용이하게 바꿔줄 수 있을 것 같아요.
- 개선은 하셨지만 여전히 errorMessage가 스택에 쌓이고 있네요.

지금은 이 부분이 문제가 있다는 것을 인지하시고 차후에 개선하셔도 좋습니다.

---

이런 것을 나아가 customException으로 분리할 수 있습니다.

2022-04-10 08:14 UTC, merged

2022-04-10 08:17 UTC, sally-ksh commented on backend/todolist/src/test/java/kr/codesquad/todolist/card/CardServiceTest.java
> +	@DisplayName("카드 등록 요청시 전달받은 카드정보를 DB에 저장되고, 생성된 card-id를 확인한다.")
아주 좋습니다 ㅋㅋㅋㅋ