[TEAM-02][BE] 2주차 1PR - 전체 목록 조회, 글쓰기 수정/삭제
codesquad-members-2022/todo-list pull request #128
Opened 2022-04-12 03:18 UTC by sally-ksh

안녕하세요 ~ 
리뷰와 여러 변경사항으로 꼼꼼히 체크하는게 부족했던 것 같습니다.
관련 부분하여 update 등 변경이 있었습니다.
제가 작성한 기존 기능과 로직을 sammy가 분석하면서 기능구현 하느라 고생이 많습니다.
이번에는 제 PR 만 보내지만, 곧  sammy 도 제출 할 거 같아요. 👍 

언제나 세세한 리뷰 리드와 세션 감사합니다. 👍 

sammy 
- 카드 이동 담당 (작업중)
  - Controller, Service, Dao (test)

sally
- 전체목록 조회
 - Controller, Service, Dao, test
- 글쓰기 수정
  - Controller, Service, Dao 
- 글쓰기 삭제  
  - Controller, Service, Dao

2022-04-12 05:22 UTC, Hyune-c requested changes
여러 dto를 만드시려는 시도는 좋은 방향입니다.
하지만 이런 경우 단점이 dto의 사용 경계가 모호해지는 것입니다. 

좋은 아키텍처의 기본은 `경계와 선 긋기`를 잘하는 것입니다.
만약 어렵다면 오히려 적은 경계에서 시작해서 (mvc로) 경계를 늘려나가는 훈련을 하시는 것을 추천합니다.

- 레이어별로 사용할 네이밍도 정해야 할것이고 굉장히 어려울 것입니다. 
- 따라서 한정된 기간에 하기 어려울 수도 있으니 단순화하시는 것을 추천합니다.
    - 이미 dto가 너무 많습니다.
    - dto의 생성 방향에 대해 고민해보세요.
    
---

생각보다 리뷰 거리가 많아서 부분적으로, 단계적으로 하고 있습니다.
혹시 코멘트하지 않은 부분이라도 필요한 부분이 있다면 별도로 질문바랍니다.

2022-04-12 05:22 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardApiController.java
> +	public void edit(@PathVariable("id") Long cardId, @RequestBody @Valid CardDto.EditRequest request) {
지금의 api를 보면 `/api/todo/{id}` 입니다.
즉 card라는 단어가 없네요.
즉 api 사용자의 입장에서는 todoId로만 인지하고, card의 개념을 모를 것 같습니다.

계속 얘기하는 것 중의 하나인 `card와 todo의 모호한 경계`에서 나오는 이슈 중 하나인 것 같습니다.

2022-04-12 05:22 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardApiController.java
> +	public ResponseEntity welcomePage(@RequestHeader HttpHeaders headers) {
`GET /api/todo` 는 api 해석상 조회아닌가요?

이후 welcomePage로 가는지 여부는 백엔드의 관심사가 아닌 것 같습니다.

2022-04-12 05:22 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDto.java
> +	public static class CardsResponse {
지금 프로젝트 구조를 보면 패키징이 안되어 있는데요.
패키징을 통해 dto의 사용 레이어를 구분해보면 어떨까요?
흐름을 볼 떄 request, response는 controller 영역에서 쓰이는 dto들인 것 같습니다.

최소한 controller에서 쓰이는 dto, service에서 쓰이는 dto 정도는 분리가 되어야 할 것 같습니다.
지금은 가독성이 꽤 헷갈립니다.

---

- `CardsResponse`가 맞을까요? `CardResponses`가 맞을까요?
    - 지금의 내부를 보면 Card정보가 아닌 status정보만 있습니다.
- 그렇다면 `CardStatusResponses`가 맞을까요?
    - status만 내려주는 것이 업무 요건에 적절한가요?

2022-04-12 05:22 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDto.java
> +				.forEach(card -> this.data.put(card.getStatus().getText(), new StatusResponse(card.getCount(), card.toResponse())));
`nit`
생성자에서 하는 것이면 foreach로 하지말고 만들어진 map을 넣을 수도 있지 않을까요?

2022-04-12 05:22 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardService.java
> +	public void updateOf(Long cardId, CardDto.EditRequest request) {
메서드 컨벤션상 public을 상단에 올리시는 것을 추천합니다.

2022-04-12 05:22 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardService.java
> +			.forEach(status -> cardsInfo.put(status, cardDao.findByUserIdAndTodoStatus(userId, status)));
`nit`
foreach보다는 collect로 하면 어떨까요.

2022-04-12 05:22 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardService.java
> +	private List<CardByStatus> toCardByStatuses(Map<Card.TodoStatus, List<Card>> cardsInfo,
`to`라는 접두어는 A객체가 B객체로 변한다는 의미로 A객체의 메서드로서 존재하는 것이 직관적입니다.
지금의 로직은 mapper와 같은 단어가 더 적합해 보입니다.

2022-04-12 08:47 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardApiController.java
> +	public void edit(@PathVariable("id") Long cardId, @RequestBody @Valid CardDto.EditRequest request) {
url 정의만 할 때는 POST 로 카드 생성시 /api/todo 와 연결 지어 생각하면서 카드 수정이 PATCH /api/todo/{id} 가야 한다고 생각했었습니다. ㅎㅎ
수정 하겠습니다.

2022-04-12 09:09 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardApiController.java
> +	public ResponseEntity welcomePage(@RequestHeader HttpHeaders headers) {
백앤드 관심사 ! 
네 반영해서 수정해놓겠습니다.

2022-04-12 14:03 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDto.java
> +				.forEach(card -> this.data.put(card.getStatus().getText(), new StatusResponse(card.getCount(), card.toResponse())));
``` java
this.data = cards.stream()
    .collect(Collectors.toMap(
	    key -> key.getStatus().getText(),
	    val -> new StatusResponse(val.getCount(), val.toResponse())
    ));
```

collect로 수정해봤는데요.
map() 으로는어떻게 할 수 있을까요? 😃

2022-04-12 14:04 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardService.java
> +			.forEach(status -> cardsInfo.put(status, cardDao.findByUserIdAndTodoStatus(userId, status)));
``` java
Arrays.stream(Card.TodoStatus.values())
.collect(Collectors.toMap(
      key -> key,
      status -> cardDao.findByUserIdAndTodoStatus(userId, status))
);
```

네, 수정했습니다. 
나쁜 습관 생길 뻔 한 것 같아요.
감사합니다. 👍

2022-04-12 14:09 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardService.java
> +	public void updateOf(Long cardId, CardDto.EditRequest request) {
네, 
저희 팀에서 충돌을 예상해서 몇 가지 규칙을 만들어봤습니다.
관련 메서드들은 모아 둔다든가,..
맨 아래에만 추가 한다든지. 
수정시 알아볼 수 있는 방법들로 적용해 봤는데요.
pr 시 같이 합쳐서 고친 후 보낼 걸 예상했는데,
시간상 먼저 리뷰 받는 게 좋을 것 같았습니다.

슬랙에서도 허용 해주셨는데, 아래에도 번복되면서 적어주셔서
좀더 설명해봅니다.
pr 메시지에라도 적어 두었으면 좋았을 텐데 싶습니다. 

수고하신점 감사드리고, 이해해 주셔서 감사합니다. 🙇‍♀️

다음 pr에 잊지 않고 반영하겠습니다 👍

2022-04-12 14:37 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardService.java
> +	private List<CardByStatus> toCardByStatuses(Map<Card.TodoStatus, List<Card>> cardsInfo,
to B 로 생각해왔었는데, .. 팩토리메서드명 처럼 B From 생각해보면 이해되는 것 같습니다.

mapper는 위의 to/from 과 비교해보면
여러인자들을  1:1 맵핑 시켜준다고 보면 될까요?
Dao에서 -Map, -Mapper 두 가지를 썼었는데 ( getCardMap(), cardRowMapper() )
 -Map 은 정말.. Map 자료구조 반환이라 썼는데.. 이것도 Mapper인지... 
 Mapper를 비교하면서 생각하니 어떤관점에서 봐야할지 여러 생각이 들어 여쭤봅니다. 

`cardByStatusesMapper` 로 변경해봤습니다.
forEach도 map으로 변경했습니다.

2022-04-12 14:53 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDto.java
> +	public static class CardsResponse {
status 별로 조회한 Card 정보를 CardResponse 에 담아
 (기존 WriteResponse 재사용으로 -> CardResponse 변경)

status 별로 개수와 List<CardResponse> 가 있다고 해서  =>  StatusResponse , 

그렇게 전체 card 목록을 status 별로 담았다고 생각해서 CardsResponse 라고 했습니다.

``` java
public CardsResponse(List<CardByStatus> cards) {
	this.data = cards.stream()
		.collect(Collectors.toMap(
			key -> key.getStatus().getText(),
			val -> new StatusResponse(val.getCount(), val.toResponse())
		));
}
```

근데 위 맵핑을 보면 정말 status 만 담기는 거 같이 보이네요 😅
제가 작업하면서 헷갈리다보니, 작업상 연결 과정을 정보로 담게 된 것 같습니다.

정리해보면.... 아래와 같이 수정할 것 같습니다.
- StatusResponse  -> CardOfCountsAndListsResponse
-  CardsResponse 유지

2022-04-12 14:56 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardService.java
> +	private List<CardByStatus> toCardByStatuses(Map<Card.TodoStatus, List<Card>> cardsInfo,
이건 정답이 없습니다.
지금의 방법도 네이밍의 문제일뿐 해결 방법에는 문제가 없습니다.
따라서 팀에서 협의하시길 기대합니다.

실무에서도 이런건 협의의 대상입니다!

2022-04-12 14:57 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDto.java
> +				.forEach(card -> this.data.put(card.getStatus().getText(), new StatusResponse(card.getCount(), card.toResponse())));
네. 제안해주신게 좋은거 같아요.

2022-04-12 14:57 UTC, Hyune-c approved these changes

2022-04-12 23:06 UTC, sally-ksh commented
저번에 알려주신 ERD 로 간단히 그려봤습니다.

https://www.erdcloud.com/d/MR5jNfSsokwxpxJ3Z

감사합니다 🥇

2022-04-13 02:40 UTC, Hyune-c commented
프로젝트 관련 자료는 직접 링크가 아닌 wiki나 readme에 기록 후 그 링크를 주시는 것이 좋습니다.
지금의 erd 링크는 wiki나 readme에 없는거 같아요.

2022-04-13 02:40 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDto.java
> +	public static class CardsResponse {
이것은 패키지를 나눈 후 조금 더 얘기해보죠.

2022-04-13 02:41 UTC, Hyune-c approved these changes

2022-04-13 06:22 UTC, astraum commented
안녕하세요 단, 

저희가 작업 내용을 dev-backend 브랜치에서 통합하던 중이었는데, 실수로 승인된 PR을 닫지 않고 진행했습니다. 

원래는 패키지 분할까지 완료한 후 새 PR을 생성할 생각이었는데, dev-backend에 merge시킨 내용이 아직 열려있는 이 PR에 반영되고 말았습니다. 

추가 내용에 대해서도 리뷰를 부탁드립니다. 혼란을 빚어 죄송합니다.

2022-04-13 07:14 UTC, Hyune-c approved these changes

2022-04-13 07:14 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardService.java
> +		}
`이미 그 위치면` 아무 행위를 하지 않고 끝내는군요.

나쁜 방법은 아니지만 아주 좋은 방법이라고 보이지도 않군요. 
동시성에 취약한 방법입니다.

하지만 지금은 괜찮을 것 같습니다.

---

order에 대한 테스트를 좀 더 많이 해주세요.

2022-04-13 07:31 UTC, astraum commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardService.java
> +		}
예 감사합니다. 동시성을 고려하여 좀 더 신뢰성 높은 방법을 연구해 보겠습니다.  

order에 대한 테스트도 보강하겠습니다.

2022-04-13 07:44 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardService.java
> +		}
ordering은 실무에서도 꽤 부딪히는 주제 중 하나입니다.
이제 order에 대해 어느정도 방향이 잡힌 것 같으니 좀 더 공부하실 키워드를 알려드립니다.

- LinkedList
- `@OrderColumn` <- 단점 있음!
- `@OrderBy`

2022-04-13 07:49 UTC, merged