[Team-05 BE nathan & 피오] Todolist 기능 구현 및 배포, api 문서화 진행
codesquad-members-2022/todo-list pull request #133
Opened 2022-04-13 07:16 UTC by NB993

# 22.04.13 PR

안녕하세요 로치, 5조 피오 & 나단입니다. 바쁘신 와중에도 PR 리뷰 맡아주셔서 감사합니다. 🙂
부족한 점이 많지만 이번 리뷰를 통해서 성장할 수 있도록 하겠습니다!

## 1. 지난 리뷰에 대한 feedback

- cardDTO를 공유하면서 생길 수 있는 문제점 방지
    - cardDTO의 속성들을 getter로 넘겨주었습니다.
- Logger 사용시 final을 붙여 사용하였습니다.
- 변수명 변경 : order_index → order
- Enum Class 최대한 활용(Section, Event)

## 2. 이번 PR 기능 구현 및 특이사항

- 카드 이동 기능 구현
    - DB order 인덱스 활용 방안
        - [관련 설명 이미지 링크](https://www.notion.so/d368745b9c70436dbf85bc181d017f21)
        - 카드 정보 갱신이 일어나는 경우, 인덱스의 변화를 매번 적용하기 보다, order를 1000씩 간격을 두어 이진탐색의 방식처럼 구현하였습니다.
        - 이 때 결국 사이에 카드를 넣게 되면 인덱스가 절반, 절반의 절반.. 으로 줄어들면서 끝을  볼 수 있게 되는데요, 이를 방지하기 위하여, 앱 종료 시점에 일괄 처리 API를 호출하게 하여, 전체 인덱스를 다시 1000단위로 갱신토록 하였습니다.
- 배포
    - 기능 구현 후 backend 브랜치로 머지가 완료된 시점마다 주기적으로 배포를 진행하였습니다. 버전은 0.0.x 단위로 증가시켰습니다.
- 문서화
    - Swagger를 이용하여 카드 전체조회, 등록, 수정, 이동, 삭제에 대한 api 문서를 작성하였습니다.
- AOP 활용해보기
    - CardController에서 똑같은 Logger 코드가 모든 메서드에서 나타나는 것을 발견하고, AOP를 통해 중복제거를 하면 좋겠다는 생각이 들어, 처음으로 적용을 해보았습니다.
- Log pagination 구현
    - 클라이언트에서 원하는 개수만큼 페이징을 하여 Log 정보를 Client 측에 줄 수 있도록 만들었습니다.
    - 각 섹션 별 카드에 대한 pagination은 아직 구현하지 못했습니다.

## 3. 미처 하지 못한 부분 + 막혔던 부분에 대한 고민

- 이번 미션을 진행하면서, 예외처리, 로깅, 테스트에 대해 진행하지 못했습니다.
- 어떻게 해야할지 막막하면서도, 안하자니 API에 대한 안정성을 보장할 수 없는 것 같고..
- 앞으로 남은 기간동안 이 부분에 대해서 고민해보고 적용해볼 수 있도록 해보려고 합니다.
- 새로운 버전 배포시 서버 디렉토리에 이전 버전의 jar파일을 보유하도록 하였습니다. 현업에서는 지난 버전의 jar파일을 어떻게 관리하고 계신지 궁금합니다.

감사합니다!

2022-04-13 23:22 UTC, tmdgusya commented
지금 Conflict 나 있는데 해결해주세요~

2022-04-13 23:50 UTC, tmdgusya requested changes
고생하셨습니다.

조금 만 더 수정하고 넘어가시죠

2022-04-13 23:50 UTC, tmdgusya commented on backend/src/main/java/com/team05/todolist/config/AopConfiguration.java
> +			logger.debug("[log-Time] {}", logDTO.getLogTime());
좋은 방법인지는 잘 모르겠어요
저는 Controller 에 로그가 있는게 좀 더 직관적이라고 생각해요.

2022-04-13 23:50 UTC, tmdgusya commented on backend/src/main/java/com/team05/todolist/controller/CardController.java
> +	public ResponseEntity<ResponseDTO> update(@RequestHeader(value = "user-agent") String userAgent,
userAgent 는 단순 로그 용인가요?

2022-04-13 23:50 UTC, tmdgusya commented on backend/src/main/java/com/team05/todolist/controller/HomeController.java
> +		List<LogDTO> logs = logService.findLogs(0, 10);
0, 10 은 어떤 의미인가요? 상수로 처리하면 좋을거 같아요~!

2022-04-13 23:50 UTC, tmdgusya commented on backend/src/main/java/com/team05/todolist/controller/HomeController.java
> +		@ApiImplicitParam(name = "number", value = "추가적으로 원하는 로그 개수")
보통 offset / size 로 많이 쓰긴하는데 nowNumberOfLogs 는 괜찮은데 `number` 보다는 `size` 가 나아보여요.
number 라는 단어가 의미를 뭔가 잘 드러낸다는 생각이 들진 않아서요.

2022-04-13 23:50 UTC, tmdgusya commented on backend/src/main/java/com/team05/todolist/domain/Card.java
> +		if (preOrder == -1 && nextOrder != -1) {	// 맨 처음으로 카드를 옮길 때
만약 주석을 달아야 하는 경우면 아래처럼 할 수도 있을꺼에ㅛ

```java
public Boolean 맨_처음으로_카드를_옮길_때() {
 return preOrder == -1 && nextOrder != -1
}
```

2022-04-13 23:50 UTC, tmdgusya commented on backend/src/main/java/com/team05/todolist/domain/Card.java
> +		if (preOrder == -1 && nextOrder != -1) {	// 맨 처음으로 카드를 옮길 때
주석을 달아야 하는 상황에 함수로 추출이 가능한지? 혹은 다른 좋은 표현이 없는지 생각해봐도 좋아요.
그리고 떠오르지 않는다면 주석을 달아주시면 좋습니다.

2022-04-13 23:50 UTC, tmdgusya commented on backend/src/main/java/com/team05/todolist/domain/Card.java
> +		if (preOrder == -1 && nextOrder != -1) {	// 맨 처음으로 카드를 옮길 때
그리고 -1 도 어떤의미를 지니고 있는거 같은데 어떤의미인지 모르겠어요. 매직넘버로 느껴지네요

2022-04-13 23:50 UTC, tmdgusya commented on backend/src/main/java/com/team05/todolist/domain/Log.java
> +	public Log(String event, LocalDateTime logTime, String title, String prevSection, String section) {
만약 롬복이 있으시다면 저는 생성자에 `@Builder` 를 붙이는 것 또한 선호해요.
왜냐면 파라미터가 3개이상 넘길 경우 순서를 맞춰주기도 힘들고 어려워질 수도 있어서 가독성 면에서 Builder Pattern 이 좋다고 생각해서요.

다만, 안 붙이셔도 됩니다. 개인적인 생각이에요

2022-04-13 23:50 UTC, tmdgusya commented on backend/src/main/java/com/team05/todolist/service/CardService.java
> +        if (cardDto.getNumber() != 0) {
cardDto.getNumber() 이 의미가 해당 섹션의 카드 수 인가요?
그러면 Section.getCountOfCard() 가 더 좋은 표현이지 않을까요?

2022-04-13 23:50 UTC, tmdgusya commented on backend/src/main/java/com/team05/todolist/service/CardService.java
> +    public Card findOne(int id) throws NoSuchElementException {
`throws NoSuchElementException` 작성하신 이유가 있을까요?

2022-04-13 23:50 UTC, tmdgusya commented on backend/src/main/java/com/team05/todolist/service/CardService.java
> +    }
List 에 있는 순서대로 원소들을 나열하기 위해서 사용하는 건가요?

2022-04-13 23:50 UTC, tmdgusya commented on backend/src/main/java/com/team05/todolist/service/LogService.java
> +    }
혹시 Paging 쿼리를 아시나요? 아시면 페이징 방식으로 하시면 좋고 모르시면 이대로 하셔도 좋습니다.
다만 나중에 시간되실때 학습은 하시는게 좋아요~!

2022-04-14 01:54 UTC, nathan29849 commented on backend/src/main/java/com/team05/todolist/config/AopConfiguration.java
> +			logger.debug("[log-Time] {}", logDTO.getLogTime());
CardController에 모든 메서드에서 똑같은 로그를 쓰고 있기에, 중복 제거를 위해 사용했습니다. 
이런 경우에도 그냥 직관성을 위해 CardController에 놓는게 맞을까요?

2022-04-14 01:56 UTC, nathan29849 commented on backend/src/main/java/com/team05/todolist/controller/CardController.java
> +	public ResponseEntity<ResponseDTO> update(@RequestHeader(value = "user-agent") String userAgent,
사실 원래는 Card와 CardDTO에 들어가야할 필드인데, 설계 과정에서 빠뜨렸습니다.
저건 잘되는지 일단 확인하는 과정에서 들어가졌던 것 같습니다.
개선하겠습니다!

2022-04-14 01:59 UTC, nathan29849 commented on backend/src/main/java/com/team05/todolist/controller/HomeController.java
> +		List<LogDTO> logs = logService.findLogs(0, 10);
매직넘버 처리하겠습니다!

2022-04-14 02:00 UTC, nathan29849 commented on backend/src/main/java/com/team05/todolist/controller/HomeController.java
> +		@ApiImplicitParam(name = "number", value = "추가적으로 원하는 로그 개수")
변수명을 지을 때 `offset`, `size`가 생각나지 않아 고민이 많이 됐는데, `offset` 또는 `size`로 한 번 해보겠습니다 감사합니다!

2022-04-14 02:02 UTC, nathan29849 commented on backend/src/main/java/com/team05/todolist/domain/Card.java
> +		if (preOrder == -1 && nextOrder != -1) {	// 맨 처음으로 카드를 옮길 때
주석을 마지막 수단으로 생각하도록 하겠습니다.
매직넘버도 제거하겠습니다!

2022-04-14 02:03 UTC, nathan29849 commented on backend/src/main/java/com/team05/todolist/domain/Card.java
> +		if (preOrder == -1 && nextOrder != -1) {	// 맨 처음으로 카드를 옮길 때
```
public Boolean 맨_처음으로_카드를_옮길_때() {
 return preOrder == -1 && nextOrder != -1
}
```
이 부분이 이해가 잘 안가는데, 한글로 작성을 해도 상관이 없는건가요??

2022-04-14 02:03 UTC, nathan29849 commented on backend/src/main/java/com/team05/todolist/domain/Log.java
> +	public Log(String event, LocalDateTime logTime, String title, String prevSection, String section) {
감사합니다! 참고해보겠습니다!!

2022-04-14 02:05 UTC, nathan29849 commented on backend/src/main/java/com/team05/todolist/service/CardService.java
> +        if (cardDto.getNumber() != 0) {
지금 보니 의미가 명확하지 않은 `number`를 너무 남발했다는 생각이 듭니다.
개선하겠습니다!

2022-04-14 02:06 UTC, nathan29849 commented on backend/src/main/java/com/team05/todolist/service/CardService.java
> +    public Card findOne(int id) throws NoSuchElementException {
예외 처리를 해보려고 일단 작성을 한 부분인데, 완성되지 않았습니다.

2022-04-14 02:13 UTC, NB993 commented on backend/src/main/java/com/team05/todolist/service/CardService.java
> +    }
최초 조회된 카드들의 order는 1000단위로 증가하게 되는데, 카드 이동시 중간에 삽입된 카드의 order는 앞 뒤 카드의 중간 값을 가지게 되어 카드의 order 간격이 1000보다 작아지게 됩니다. 이 메서드를 통해서 변경된 카드의 order 값들을 다시 1000단위로 재조정해주고 있습니다.

2022-04-14 02:13 UTC, NB993 commented on backend/src/main/java/com/team05/todolist/service/LogService.java
> +    }
쿼리 작성이 능숙하지 않아서 아직 페이징 쿼리를 작성하지 못했습니다. 추후에 공부하고 적용해보도록 하겠습니다! 🙂

2022-04-14 02:26 UTC, nathan29849 commented
컨플릭트 해겷했습니다!
리뷰 감사드립니다 ☺️

2022-04-14 03:42 UTC, tmdgusya commented on backend/src/main/java/com/team05/todolist/config/AopConfiguration.java
> +			logger.debug("[log-Time] {}", logDTO.getLogTime());
음 단순 개인차일수도 있어요 ㅎㅎ
맞고 틀린건 딱히 없는거 같고, 저는 AOP 를 사용하게 되면 특정 컨트롤러 보다는 컨트롤러 전체가 이런 로깅을 찍는다.. 라는 경우에만 분리를 해요.
보통 AOP 를 사용하는 경우가 횡단 관심사일 경우인데, Controller 전체가 아닌 특정 Controller 에서만 그렇게 쓰인다면 횡단관심사가 맞는지에 대한 생각이 들어서요

2022-04-14 04:52 UTC, nathan29849 commented on backend/src/main/java/com/team05/todolist/config/AopConfiguration.java
> +			logger.debug("[log-Time] {}", logDTO.getLogTime());
단순히 중복코드 제거에만 관심을 두고 있었던 것 같습니다.
말씀해주신대로 횡단 관심사가 맞냐고 의문을 던져보면, 저 또한 아니라고 생각이 들기는 합니다. 
리뷰 감사합니다.

2022-04-14 07:10 UTC, tmdgusya commented on backend/src/main/java/com/team05/todolist/domain/Card.java
> +		if (preOrder == -1 && nextOrder != -1) {	// 맨 처음으로 카드를 옮길 때
아뇨 ㅎㅎ 한글로 작성해도 되나 영어로 표현해주시면 더 좋을거 같아요 ㅎㅎ

2022-04-14 07:11 UTC, tmdgusya commented on backend/src/main/java/com/team05/todolist/service/CardService.java
> +    }
아하 그렇군요!

2022-04-14 08:57 UTC, nathan29849 commented on backend/src/main/java/com/team05/todolist/domain/Card.java
> +		if (preOrder == -1 && nextOrder != -1) {	// 맨 처음으로 카드를 옮길 때
앗 알겠습니다 감사합니다!!

2022-04-14 23:41 UTC, merged

2022-04-14 23:41 UTC, tmdgusya commented
머지 해드리겠습니다~ 고생하셨어요