[Team-06] BE 2022/04/06 1차 PR
codesquad-members-2022/todo-list pull request #14
Opened 2022-04-06 07:44 UTC by zbqmgldjfh

## 안녕하세요 리뷰어님! Team-06의 땃쥐, Shine입니다!

## 질문
#### Shine
팀원과 처음 Work라는 도메인 모델을 만들때 2가지 방식의 생성방법에 대하여 논의 하게 되었습니다.
1) 생성자 + setter 방식
2) 빌더패턴 

**1) 생성자 이용하기**
```java
public class Work {
    // 생략...

    public Work(String title, String content, String author) {
        this.title = title;
        this.content = content;
        this.author = author;
        this.workStatus = WorkStatus.TODO; // 초기값 자동 지정
        this.createDateTime = LocalDateTime.now(); // 초기값 자동 지정
        this.lastModifiedDateTime = createDateTime; // 초기값 자동 지정
    }
```
위 방식은 Controller로 request DTO가 전달 돠었을 때 필요한 값 3개만 뽑아서 생성하는 방식 입니다.
추가로 나중에 DB 에서 꺼내 올때는 위 생성자로 생성 한 후, 날짜는 setter를 통해 다음과 같이 호출할 생각 이였습니다.
```java
Work work = new Work();
work.setCreateTime();
work.setLastUpdateTime();
```
을 호출하여 DB에서 꺼내올 생각 이였습니다!

**2) 빌더 패턴 이용하기**
두번째로는 builder 패턴을 사용하는 방식 입니다. 해당 도메인이 field값이 많아져서 빌더로 메서드를 호출하면 가독성이 증가할거라 생각되었습니다.
나중에 DB에서 꺼내올때도 하나씩 인자를 다 지정할수도 있구요!

일단은 생성자 방식을 사용했는데... 음 리뷰어님이라면 어떤 방식을 선택하실것 같나요??

----

#### 땃쥐
1. URL 설계
- 어떤 글에 대하여 (예: /works/1)
- 글의 제목, 본문을 변경하는 이벤트도 수정에 해당하므로 PUT
- 글을 이동하는 이벤트도 수정에 해당하므로 PUT
- URL을 다르게 하여 만드는게 맞을 것인가, 아니면 한 메서드에서 분기처리하는게 맞을까?
2. 반환타입
- 응답으로 어떤 데이터를 담아서 보내야할 것인가? 어떤 타입으로 보내는 것이 적합할까?

----

## 기능 명세
- 보여주가(get)
- 등록(post)
- 수정(post)
- 삭제(delete)
- 이동(patch)

## Todo-List
### Work Domain
- [x] Work 
  - PK(id)
  - title
  - content
  - 작성자
  - 상태 Enum으로 관리
  - 작성 날짜
  - 마지막 수정 날짜
- [x] Repository 만들기 (memory)
  - [x] test 코드 작성하기

### Controller
- [x] 할 일 추가 컨트롤러 생성
- [x] Work 수정 컨트롤러 만들기
- [x] Service 계층 분리하기
- [x] Work 목록 API 응답 기능

### 흐름
- 생성 요청 post -> dto(title, content, 작성자)
- 수정 요청 put -> id(pathVariable), dto(title, content, 작성자) 
- 이동 요청 put -> id(pathVariable), dto(status) -> entity 찾아오고 -> updateStatus
- 삭제 요청 delete -> id(pathVariable) -> 삭제

2022-04-07 06:42 UTC, tmdgusya commented
개인적으로 저는 Kotlin 을 해서 NamedParameter 가 있어서 Kotlin 에서는 생성자를 많이 쓰는데요. (잡담입니다 ㅎㅎ 죄송..)
근데 Java 를 하게 됬을때 느낀점은 생성자가 3개 이상 정도 되면 생성자에 `@Builder` 어노테이션을 붙이는게 좋겠다는 생각이 들더라고요.
저도 일정 이상의 생성자에서는 Builder 를 사용하는것이 좋다고 생각해요~!

2022-04-07 06:53 UTC, tmdgusya requested changes
몇가지만 고치고 넘어가시면 좋을거 같아요 👍 

첫번째 팀 미션 고생하셨습니다 ㅎㅎ.
팀원과 잘 이야기하고 함께 공부하면서 다음 미션으로 가보시죠~!

2022-04-07 06:53 UTC, tmdgusya commented on BE/src/main/java/codesquad/todo/domain/work/MemoryWorkRepository.java
> +        this.store = new ConcurrentHashMap<>();
굳이 생성자에서 할 이유는 없어 보이기도 해요

2022-04-07 06:53 UTC, tmdgusya commented on BE/src/main/java/codesquad/todo/domain/work/MemoryWorkRepository.java
> +        work.initId(id);
`initId` 라는 표현보다 `setId` 가 좋아보이네요 저는

2022-04-07 06:53 UTC, tmdgusya commented on BE/src/main/java/codesquad/todo/domain/work/Work.java
> +@Getter
저는 개인적으로 도메인 객체에 Getter 를 붙이는건 별로라고 생각해요.
도메인 객체가 모든 속성을 열어야 할까요? 객체의 협력에 맞게 필요한 부분만 열어야 하지 않나 라는 생각이 듭니다.

제 기준 `@Getter` 가 붙으면 좋은 클래스는 Dto 정도라고 생각합니다.

2022-04-07 06:53 UTC, tmdgusya commented on BE/src/main/java/codesquad/todo/domain/work/Work.java
> +@Getter
어느 부분을 열어야 할지 곰곰히 생각해보시면 좋을거 같아요.

2022-04-07 06:53 UTC, tmdgusya commented on BE/src/main/java/codesquad/todo/service/WorkService.java
> +        log.debug("[SAVE AFTER] : {}", work);
로깅 좋네요. 근데 Debug 보다는 info 가 좋지 않나요? 이건 그냥 질문입니다 ㅎㅎ

2022-04-07 06:53 UTC, tmdgusya commented on BE/src/main/java/codesquad/todo/web/works/WorkController.java
> +        return new ResponseEntity<>(workUpdateResponse, HttpStatus.OK);
`ResponseEntity.ok().body(workSaveResponse);` 또는 `ResponseEntity<>(workUpdateResponse, HttpStatus.OK)` 둘 중 하나로 통일하면 어떨까 싶네요

2022-04-07 06:53 UTC, tmdgusya commented on BE/src/main/java/codesquad/todo/web/works/WorkController.java
> +        WorkSaveResponse workSaveResponse = workService.workSave(workSaveRequest);
저는 개인적으로 `WorkSaveResponse` 를 응답으로 주는게 더 좋아보여요. 
굳이 ResponseEntity 로 한번 더 감싸는 이유가 있을까요? 
`WorkSaveResponse` 자체만으로도 이미 충분히 Response Model 이라는 걸 나타내는 것 같아서요.

2022-04-07 06:53 UTC, tmdgusya commented on BE/src/main/java/codesquad/todo/web/works/dto/BaseResponse.java
> +public class BaseResponse {
이건 어떤 목적으로 있는건가요? EntityResponse 대용인가요?

2022-04-08 01:39 UTC, zbqmgldjfh commented on BE/src/main/java/codesquad/todo/domain/work/MemoryWorkRepository.java
> +        this.store = new ConcurrentHashMap<>();
필드에서 바로 생성되도록 하였습니다!!

2022-04-08 01:40 UTC, zbqmgldjfh commented on BE/src/main/java/codesquad/todo/domain/work/MemoryWorkRepository.java
> +        work.initId(id);
팀원이랑 "초기값"을 설정한다는 의미를 더 부여하고 싶어서 initId를 사용하도록 되었습니다 ㅎㅎ

2022-04-08 03:09 UTC, tmdgusya commented
흠 근데 궁금한게 꼭 Work 모든 속성을 Getter 로 열어야 하나요?

2022-04-08 03:11 UTC, merged

2022-04-08 03:11 UTC, tmdgusya commented
도메인 모델을 API Response 로 넘기는게 맞는지에 대한 생각이 필요해보여요
DTO 를 한번 공부해보시면 좋을거 같아요. ViewModel 이나