[iOS] MenuView, Model-View 연결, 카드 추가 모달 View 구현
codesquad-members-2022/todo-list pull request #145
Opened 2022-04-13 07:55 UTC by asqw887

바쁘신데도 항상 친절한 리뷰 감사합니다 :) 

### 작업사항 
- [x] `TableView` 관리 객체를 `TableViewCell` -> `ContentView` 로 변경 
    - [x] `TableHeader` 구현 위치 변경 
    - [x] `TableView` 구현 위치 변경
- [x] 활동 상태(`MenuView`) 구현 
    - [x] `ActivityMenuViewController` 구현
    - [x] `ContainerVC`에 `addChild`  
    - [x] `MenuView` 등장을 위한 `HeaderViewDelegate`, `ActivityViewDelegate` 델리게이트 구현 
- [x] 화면 회전시 레이아웃 무너짐 현상 해결  
- [x]  decoding, encoding 로직 분리  
- [x] 네트워크 GET 연결 후  모델, 뷰와 연결 
    - [x] `TableVC`에서 비동기로 view reload 및 view에 적절한 데이터 할당 구현
    - [x]  `ContentVC`에서 Layout 생성 완료된 시점에 네트워크 통신 호출
    - [x]  `didMove` 호출하여 `TableVC`가 관련 함수 호출할 수 있도록 완곡적 호출 형태로 구현  
- [x] UIColor Extension 
- [x] UnitTest  

### 고민과 해결
- GETrequest 를 요청하고 백엔드 측에서 넘겨준 Date 를 디코딩 하는 과정에서 시행착오가 있었습니다. iSO 표준으로 변환시키는 등 시도를 해보았지만 계속해서 nil 값이 넘어와, 백엔드 분들과 상의 끝에 String 값을 넘겨받도록 수정했습니다. 
- 공용 와이파이를 사용할때는 `info.plist`에서 `Allow Arbitrary Loads` 해야한다는 것을 알았습니다..  
-  `+` 버튼 터치시 `addCardViewController` 를 present 하는 기능을 시도 하는 중에 시행착오가 있었습니다. 상위 VC `addCardViewController` 를 소유하고 있지만 `addCardViewController` 의 하위 뷰에 대한 객체는 가지고 있지 않기 때문에 addChild로 부모-자식 관계를 갖게 해주어 기능을 구현되도록 하게 해주었습니다. 

### 실행 화면
![KakaoTalk_Photo_2022-04-13-16-54-11](https://user-images.githubusercontent.com/59790540/163127828-fbc292b2-5c8f-4109-9a36-54db30134266.gif)

2022-04-13 13:33 UTC, lenaios requested changes
리뷰가 늦었네요 죄송합니다ㅠㅠ 아직 조금 더 확인 중이니 조금만 기다려주세요! 🙏

2022-04-13 13:33 UTC, lenaios commented on TodoList/TodoList/Model/Board.swift
> +    }
subscript를 활용하셨네요! 👍 다만 내부에서 index 값이 하드하게 사용되는 점(0, 1, 2로 비교)이 조금 아쉬워요~ 이 부분을 개선할 수 있는 방법이 없을까요? 🤔

2022-04-13 13:33 UTC, lenaios commented on TodoList/TodoList/Model/Board.swift
> +        return date
dateFormatter가 Board 안에서만 사용되고 있어서 private extension 하신 것 같네요~
그렇지만 dateFormatter는 필요하다면 Board 외에 다른 곳에서도 사용될 수 있는 Util에 가까운 함수 같은데, 어떻게 생각하시나요? 🤔

2022-04-13 13:33 UTC, lenaios commented on TodoList/TodoList/Model/Card.swift
>      }
참고로, 첫 번째 rawValue만 정의해도 다른 case의 rawValue가 추론됩니다. 🙂

2022-04-13 13:33 UTC, lenaios commented on TodoList/TodoList/Util/ColorMaker.swift
> +}
이렇게 만드니 무슨 색인지 예측하기도 쉽고 사용하는 쪽에서도 조금 더 편리해진 것 같아요! 👏👏👏

2022-04-13 13:33 UTC, lenaios commented on TodoList/TodoList/Util/JsonConverter.swift
> +    static func decodeJson<T: Codable>(data: Data) -> [T]{
decode, encode를 담당하는 객체를 별도로 생성하신 것 좋습니다. 이 객체는 인, 디코딩의 책임만 갖게 되었네요~👍

2022-04-13 13:33 UTC, lenaios commented on TodoList/TodoList/ViewController/TableViewController.swift
> +    }
파라미터로 section을 넘겨받고 있지만 함수 내부에서 사용되지 않고 있군요! 🤔

2022-04-13 14:28 UTC, lenaios commented on TodoList/TodoList/Model/Board.swift
> +        var newCard = Card(section: section, title: title, content: content, userID: userID)
파라미터로 Card 타입을 받으면 어떨까요?

2022-04-13 14:28 UTC, lenaios commented on TodoList/TodoList/Util/JsonConverter.swift
> +    }
현재는 encoding에 실패하면 Data 객체를 생성해서 보내주고 있는데, 그럼 encodeJson()를 호출하는 곳에서 인코딩이 정상적으로 된 것인지 확신할 수 있는걸까요? 🧐

2022-04-13 14:28 UTC, lenaios commented on TodoList/TodoList/ViewController/ActivityMenuViewController.swift
> +        cell.setLabelText(author: data[0], content: data[1], time: data[2])
activityLog도 나중에 객체로 만들어질 예정일까요~?
`data[2]`와 같이 값을 가져오는 것은 index out of range 에러의 위험이 높기 때문에 지양하는 편이 좋습니다. 🙂

2022-04-13 14:28 UTC, lenaios commented on TodoList/TodoList/View/Header/HeaderView.swift
>      }
파라미터로 받은 button이 사용되고 있지 않네용~

2022-04-13 14:28 UTC, lenaios commented on TodoList/TodoList/View/ActivityMenu/ActivityMenuView.swift
> +    var delegate: ActivityViewDelegate?
순환참조, weak 키워드에 대해 알고계신가요? 읽어보시면 좋을 만한 링크 남깁니다. 😊
https://medium.com/macoclock/delegate-retain-cycle-in-swift-4d9c813d0544

2022-04-14 04:03 UTC, wnsxor1993 commented on TodoList/TodoList/Model/Board.swift
> +    }
해당 요소는 지정된 값만 가진 Enum 타입을 외부에 생성을 하고, 이를 매개변수로 받아와 잘못된 인자 값이 들어가지 않도록 수정하였습니다. 수정한 방향성이 올바른 방향인지 확인해주시면 감사하겠습니다😄

2022-04-14 04:05 UTC, wnsxor1993 commented on TodoList/TodoList/Model/Board.swift
> +        return date
차후에 String으로 받은 date를 Date 타입으로 변환하는 과정이 필요할 듯 하여 작성하였습니다만, 현재로서는 사용이 되지 않고 있어 이후에 작업을 진행하면서 말씀하신 부분을 함께 고려하여 방향성을 잡아보도록 하겠습니다!ㅎㅎ

2022-04-14 04:08 UTC, wnsxor1993 commented on TodoList/TodoList/ViewController/TableViewController.swift
> +    }
해당 함수는 작성 중에 PR을 올린 터라 파라미터를 사용하는 부분이 구현되지 않았습니다. 다음 작업을 진행하면서 파라미터를 활용한 로직을 추가하겠습니다😆

2022-04-14 04:09 UTC, wnsxor1993 commented on TodoList/TodoList/Model/Board.swift
> +        var newCard = Card(section: section, title: title, content: content, userID: userID)
받아오는 파라미터가 너무 많은 느낌이 있어서 Card 타입 하나만 받아오는 편이 더 나을 것 같습니다ㅎㅎ 파라미터 수정에 맞춰서 차후에 필요한 로직들의 구성 방향도 다시 생각해보겠습니다~

2022-04-14 04:11 UTC, wnsxor1993 commented on TodoList/TodoList/Util/JsonConverter.swift
> +    }
아직까지 Error 발생 시, 어떻게 처리해줘야 될 지에 대한 고민이 미흡한 것 같습니다ㅠㅠ 일단 옵셔널로 수정하여 Error 시에는 nil을 리턴하는 형태로 수정하고 이에 맞춰서 적절한 작업을 처리하도록 고민해보겠습니다!😭

2022-04-14 04:13 UTC, wnsxor1993 commented on TodoList/TodoList/View/ActivityMenu/ActivityMenuView.swift
> +    var delegate: ActivityViewDelegate?
delegate의 순환참조를 방지하기 위해 전체적으로 weak 키워드를 활용하였습니다. 좋은 자료 공유해주셔서 감사합니다!😁

2022-04-14 04:16 UTC, wnsxor1993 commented
> > GETrequest 를 요청하고 백엔드 측에서 넘겨준 Date 를 디코딩 하는 과정에서 시행착오가 있었습니다. iSO 표준으로 변환시키는 등 시도를 해보았지만 계속해서 nil 값이 넘어와, 백엔드 분들과 상의 끝에 String 값을 넘겨받도록 수정했습니다.
> 
> 저도 비슷한 문제를 경험한 적이 있었던 것 같은데요, 이 부분은 나중에라도 꼭 이유를 파악해보시는게 좋을 것 같습니다.
> 
> * encoding, decoding 로직을 분리하면서 제네릭을 활용하셨는데 이처럼 재사용이 쉬운, 결합도 낮은 함수를 만드는 것이 좋습니다. 👏
> * get 요청이 끝나고 뷰를 그리기 위해 Notification을 활용하셨는데, Notification을 선택하신 이유가 궁금합니다!
> 
> 몇 가지만이라도 수정되고 넘어가면 좋을 것 같아 request change로 남겨둡니다. 🙂 merge 필요하시면 코멘트 부탁드려요~

이전 과제들을 수행하면서 보통은 View - VC에서는 delegate를 Model - VC에서는 Notification을 활용하여 대화를 주고받을 수 있게 한다고 학습하였습니다. 현재 Board의 경우에는 Model이기에 작업이 완료되었으니 View를 reload 해달라는 요청을 Notification으로 사용하였습니다.

@lenaios 수정한 부분 확인 및 머지 잘 부탁드리겠습니다ㅎㅎ

2022-04-14 04:17 UTC, asqw887 commented on TodoList/TodoList/ViewController/ActivityMenuViewController.swift
> +        cell.setLabelText(author: data[0], content: data[1], time: data[2])
아직 activityLog 관련 모델을 만들지 않아서 indexPath 로 처리했습니다. 😣  코멘트 주신대로 다음 스텝에서 반영하도록 하겠습니다 감사합니다 :)

2022-04-14 04:17 UTC, asqw887 commented on TodoList/TodoList/View/Header/HeaderView.swift
>      }
앗.. 수정하도록 하겠습니다

2022-04-14 05:47 UTC, merged