[team-01][BE] API - Todo 삭제 기능
codesquad-members-2022/todo-list pull request #189
Opened 2022-04-14 06:08 UTC by donggi-lee-bit

안녕하세요 `Dan` `동기`와 `쿠킴`입니다!
Todo 삭제하기 기능 구현하여 리뷰 요청드립니다. 빠르고 흥미로운 리뷰에 항상 감사합니다 🤤

### 📝 Description

| 요청 | 기능 |
| --- | --- |
| `DELETE /api/todos/{id}` | 클라이언트가 특정 Todo를 삭제한다. (soft delete) |

### 💽 Commits

- DELETE /api/todos/{id} 요청 값을 받는다.
- DB 에서 해당 id todo 를 찾아온다.
- 해당 todo 를 simple delete 하기 위해 삭제 유무 상태를 변경한다.
- 상태 코드만 반환한다. (204 No Contents)
- DELETE /api/todos/{id} 에 대한 History 저장
- 삭제 기능에 대한 web 계층 테스트 코드

### 🖼 결과

<img width="422" alt="Screen Shot 2022-04-14 at 11 48 22 AM" src="https://user-images.githubusercontent.com/73376468/163303900-fce1f8c8-6a42-4784-90d4-78c886365cc1.png">

2022-04-14 10:03 UTC, Hyune-c requested changes
리뷰하기 적절한 길이의 PR이었습니다. 👍

- 성공 테스트 케이스는 시도만으로도 의도가 파악됩니다.
- 하지만 실패 케이스는 단순히 실패라고 네이밍 하기에는 모호합니다.
    - 의도한 실패를 명시하고, 가능한 많은 엣지 테스트를 찾으려고 해주세요.
- 성공 테스트는 1개여도 되지만 실패 테스트는 많으면 많을 수록 좋습니다.

2022-04-14 10:03 UTC, Hyune-c commented on BE/src/main/resources/db/schema.sql
> +    deleted      BIT NOT NULL DEFAULT 0         COMMENT 'Todo 삭제 여부',
지금의 soft delete는 boolean으로 표현 가능합니다.
하지만 더 좋은 soft delete의 방법에 대해서는 조금 더 생각해봅시다.

2022-04-14 10:03 UTC, Hyune-c commented on BE/src/main/resources/application.yml
> +#    password: Donggikukim!
`nit`
profile의 개념을 공부해보시는 것은 어떨까요

2022-04-14 10:03 UTC, Hyune-c commented on BE/src/main/java/codesquad/be/todoserver/service/TodoService.java
> +		historyRepository.saveHistory(History.of(saveTodo, Action.ADD));
`nit`
저는 기대되는 반환형이 repository에 명시되어 있다면 메서드 명에는 굳이 다시 기재하지 않는 편입니다.

2022-04-14 10:03 UTC, Hyune-c commented on BE/src/main/java/codesquad/be/todoserver/service/TodoService.java
> +			.orElseThrow(() -> new NoSuchTodoFoundException("id: " + id));
`nit`
CustomException의 매개변수를 id만으로 해보면 어떨까요?

2022-04-14 10:03 UTC, Hyune-c commented on BE/src/main/java/codesquad/be/todoserver/service/TodoService.java
> +		historyRepository.saveHistory(History.of(todo, Action.REMOVE));
`nit`
history는 모든 행위의 후처리로 보입니다.
관심사가 후처리라면 좀 더 좋은 구조를 가져갈 수 있지 않을까요.

2022-04-14 10:03 UTC, Hyune-c commented on BE/src/main/java/codesquad/be/todoserver/domain/History.java
> +		return null;
enum에 로직을 조금 더 모을 수 있을 것 같습니다.

2022-04-14 10:03 UTC, Hyune-c commented on BE/src/main/java/codesquad/be/todoserver/config/WebConfig.java
> +	public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
잘 적용하셨네요. 👍

`nit`
yml을 통한 적용 방법도 있으니 알아두시면 좋을 것 같아요.

2022-04-15 01:45 UTC, donggi-lee-bit commented on BE/src/main/java/codesquad/be/todoserver/service/TodoService.java
> +		historyRepository.saveHistory(History.of(saveTodo, Action.ADD));
말씀하신대로 `saveHistory()` 메서드에서 저장하고 있다는 의미가 있기 때문에 saveTodo 라는 의미 대신 그냥 todo 로 사용하는 게 나은 것 같습니다! 아래와 같은 코드로 수정하겠습니다!

```java
historyRepository.saveHistory(History.of(todo, Action.ADD));
```

2022-04-15 01:47 UTC, donggi-lee-bit commented on BE/src/main/java/codesquad/be/todoserver/service/TodoService.java
> +			.orElseThrow(() -> new NoSuchTodoFoundException("id: " + id));
```java
Todo todo = todoRepository.findById(id)
			.orElseThrow(() -> new NoSuchTodoFoundException(id));
```

이렇게 사용하라는 말씀하신 게 맞을까요?? 이렇게 하면 어떤 이점이 생길 지 머리로는 잘 그려지지가 않는데 어떤 이점이 생기는 지 알 수 있을까요?? 😵‍💫

2022-04-15 01:48 UTC, ku-kim commented on BE/src/main/resources/db/schema.sql
> +    deleted      BIT NOT NULL DEFAULT 0         COMMENT 'Todo 삭제 여부',
찾아보니 soft delete 하기 위한 컬럼을 boolean이 아닌 deleted_at와 같이 시간으로 두어, 삭제되지 않을 땐 null으로 가지고 있고, soft delete 되었을 때 해당 시간 기준 데이터를 넣어 `soft delete 된 시간` 의 추가 정보를 주어 추후에 언제 삭제 되었는지 조회하거나 e.g. 1년 된 자료는 hard delete 의 기능에 손쉽게 작업할 수 있어 보입니다.

더 좋은 soft delete 방법이 있을까요?

2022-04-15 01:54 UTC, Hyune-c commented on BE/src/main/java/codesquad/be/todoserver/service/TodoService.java
> +		historyRepository.saveHistory(History.of(saveTodo, Action.ADD));
어.. 제가 말한건 이런 형태에요. 
근데 지금도 좋습니다.

```java
historyRepository.save(History.of(todo, Action.ADD));
```

2022-04-15 01:56 UTC, Hyune-c commented on BE/src/main/java/codesquad/be/todoserver/service/TodoService.java
> +			.orElseThrow(() -> new NoSuchTodoFoundException("id: " + id));
아마 사전 정의된 Exception만 쓰시다보니 매기변수에 String으로 message를 넣는 것이 익숙하신 것 같은데요.

- CustomException이면 message format을 사전 정의 할 수 있다.
    - 즉 CustomException 안에 정의 가능.
- 매개변수의 type을 한정함으로서 생성 의도를 명확히 할 수 있음.

2022-04-15 01:59 UTC, donggi-lee-bit commented on BE/src/main/java/codesquad/be/todoserver/service/TodoService.java
> +		historyRepository.saveHistory(History.of(saveTodo, Action.ADD));
앗 ㅋㅋㅋㅋㅋ History 도 중복되고 있었네요.. 감사합니다 ㅎㅎ

2022-04-15 02:00 UTC, ku-kim commented on BE/src/main/resources/application.yml
> +#    password: Donggikukim!
안그래도 위 처럼 작성할 때 두 가지가 아쉬웠습니다.
1. application.yml에 mysql 서버 정보에 대한 보안 관리
2. 개발 환경과 배포 환경의 application 선택 사용 

`profile` 개념 알려주셔서 감사합니다.!

2022-04-15 02:03 UTC, donggi-lee-bit commented on BE/src/main/java/codesquad/be/todoserver/service/TodoService.java
> +			.orElseThrow(() -> new NoSuchTodoFoundException("id: " + id));
말씀하신 내용을 보면서 `CustomException` 을 잘 활용하지 못했다는 생각이 들었습니다! 

`CustomException` 내부에서 어떤 메시지를 출력해줄지 미리 정의하도록 수정하겠습니다!

2022-04-15 02:10 UTC, Hyune-c commented on BE/src/main/resources/db/schema.sql
> +    deleted      BIT NOT NULL DEFAULT 0         COMMENT 'Todo 삭제 여부',
> 방법 1. : 불린형이 아닌 날짜형으로 추가 정보 주기( is_deleted -> deleted_at)

방법 1은 권장하지 않습니다.

- null을 허용해야 합니다.
- 상대적으로 일어날 일이 적은 액션에 대한 명확한 컬럼을 두는 것은 비효율적이라고 생각합니다.

> 방법 2 : 삭제 테이블을 추가하여 보관 관리

질문 의도와는 조금 다르지만 좋은 접근 방법입니다.

-  모수가 충분히 많은 도메인이고, 정상 상태의 객체만 조회되어야 하는 니즈일 때 좋음.
- 비정상 상태의 객체는 어드민에서만 조회되면 됨으로 조인으로 해결함.

---

soft delete라고 하여 delete만 생각하고 있으신 것 같습니다.
업무 요건을 조금 다르게 생각해보시죠.

- todo는 누구나 작성할 수 있다.
- 하지만 작성된 todo는 admin의 승인이 필요합니다.
- 승인되지 않은 todo는 제목만 노출됩니다.
- 필요에 따라 글을 정지 시킬 수 있습니다. (삭제가 아님)

2022-04-15 02:10 UTC, donggi-lee-bit commented on BE/src/main/java/codesquad/be/todoserver/service/TodoService.java
> +		historyRepository.saveHistory(History.of(todo, Action.REMOVE));
`history` 를 후처리하기 위해서 유효한 `id` 인지 확인하는 등 전처리 작업이 `TodoService` 에서 일어나고 있습니다. 이러한 데이터를 `Repository` 에 넘겨주기 전에 `history` 를 저장하는 방법말곤 다른 구조가 떠오르지 않는데 후처리에 좋은 구조를 생각해볼만한 키워드가 있을까요??

2022-04-15 02:15 UTC, Hyune-c commented on BE/src/main/java/codesquad/be/todoserver/service/TodoService.java
> +		historyRepository.saveHistory(History.of(todo, Action.REMOVE));
`AOP` 개념에 대해 공부해보시면 좋을 것 같습니다.

2022-04-15 02:16 UTC, ku-kim commented on BE/src/main/java/codesquad/be/todoserver/config/WebConfig.java
> +	public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
감사합니다.!

혹시 yml와 config 중 더 선호하시는 방법이 있으신가요?
어떤 기능은 yml에서, config에서 구분해야할 지 감이 잘 오지 않습니다. :(

2022-04-15 02:18 UTC, donggi-lee-bit commented on BE/src/main/java/codesquad/be/todoserver/service/TodoService.java
> +		historyRepository.saveHistory(History.of(todo, Action.REMOVE));
감사합니다..!!! `AOP` 에 대해 학습해보겠습니다! 😄

2022-04-15 02:21 UTC, Hyune-c commented on BE/src/main/java/codesquad/be/todoserver/config/WebConfig.java
> +	public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
표현의 차이일 뿐 의도와 결과는 같습니다.
편하신 것으로 하시면 됩니다.

아래를 참고하셔요.

https://www.baeldung.com/spring-boot-formatting-json-dates

2022-04-15 02:30 UTC, ku-kim commented on BE/src/main/resources/db/schema.sql
> +    deleted      BIT NOT NULL DEFAULT 0         COMMENT 'Todo 삭제 여부',
아, delete 컬럼이 아닌 업무 요건을 다르게 보니
 관리자 승인, 관리에 따른 컬럼을 추가하여 (e.g. is_approved 컬럼, is_stoped 컬럼)
해당 Todo의 응답을 상황에 맞게 설정할 수 있겠다 생각했습니다.

혹시 다른 접근 방법일까요?

2022-04-15 08:11 UTC, ku-kim commented on BE/src/main/java/codesquad/be/todoserver/domain/Action.java
>  }
부족하게나마 enum 에 책음을 더해보았습니다.!

2022-04-15 08:20 UTC, ku-kim commented on BE/src/main/java/codesquad/be/todoserver/domain/History.java
> +		return action.createHistoryBy(todo);
History 팩토리 메서드의 History 생성 책임을 Action enum 으로 변경해보았습니다.2

2022-04-15 08:25 UTC, Hyune-c approved these changes
수고하셨습니다.

2022-04-15 08:25 UTC, Hyune-c commented on BE/src/main/java/codesquad/be/todoserver/domain/Action.java
>  }
리팩토링을 통해 Action의 종류가 간소화될 수 있었군요. 
변경 전과 후 중 어떤 것이 좋은지는 업무 성격에 따라 다르지만, 개발자로서 여러가지 방법을 아시는 것은 좋다고 생각합니다.

`nit`
- fun도 축약하지 않는 것이 좋습니다.
- 그냥 fun이라고 하기보다는 의도를 담으면 좋을 것 같네요.

2022-04-15 10:15 UTC, ku-kim commented
2주 동안 언제나 빠르고 신속 정확하게 리뷰 신경써주셔서 감사합니다.
리뷰, PR 보내는 것이 무척이나 즐겁고 기대되었습니다.

스스로 생각해볼 수 있는 질문에 고민하며 성장할 수 있었고, 잘 알지 못한다는 답변에 코드 예시까지 들어주셔서 어려움 없이 한 단계 더 성장할 수 있었습니다.  직접 화상 미팅까지 할 수 있어 더 자세한 이야기까지 들을 수 있어 좋았습니다.
적용하지 못한 리뷰들은 잊지 않고 앞으로 차근차근 적용하겠습니다. 말씀해주신 선택과 집중을 하고 전체적인 흐름을 이해하면 디테일한 특정 기술을 몰라도 문제를 발견하고 해결할 수 있다는 생각도 무척이나 인상 깊었습니다. 

다시한번 감사합니다. `Dan` 🙇‍♂️

2022-04-15 10:16 UTC, merged

2022-04-15 10:27 UTC, donggi-lee-bit commented
2주 동안 `Dan` 한테 리뷰 받으면서 정말 많은 걸 학습하고 배울 수 있었습니다!!

정해진 횟수만큼만 리뷰 받으셔도 되는데 더 좋은 리뷰를 받게 해주시려고 자주 리뷰 보낼 수 있게 해주셔서 감사합니다. 리뷰어로써의 역할만이 아닌 선배 개발자로써 많은 걸 알려주고 싶어하시는 느낌을 받았습니다. 리뷰해주신 내용 잊지 않고 다음 프로젝트에서도 더 좋은 코드를 작성할 수 있도록 노력하겠습니다!!

2주 동안 많은 가르침 주셔서 감사합니다 `Dan` !!! 다음에 또 뵐 수 있으면 좋겠습니다 ㅎㅎ