[team-04] 루이 & Hwi - 2주차 마지막 PR입니다.
codesquad-members-2022/todo-list pull request #204
Opened 2022-04-15 06:23 UTC by Louie-03

안녕하세요~ 디온! 루이 & Hwi 입니다.
- 시간이 부족해서 어제 추가로 리뷰해 주셨던 부분은 아직 반영하지 못했습니다.
  - 추후에 남겨주신 리뷰를 참고해서 학습하겠습니다.
- 2주 동안 고생 많으셨습니다. 감사합니다 디온~!

## 구현 사항
- 이전 PR 리뷰 반영
- 카드 삭제 & 카드 이동 기능 구현
- 안드로이드 팀과 의사소통하면서 API 변경 & 그에 따른 코드 수정
  - [API 명세서](https://www.notion.so/To-Do-List-API-3c09956db64a431ab506df91f5204cc0)

2022-04-16 07:41 UTC, ksundong requested changes
안녕하세요! 루이 & Hwi~ 리뷰어 dion입니다.

첫번째 협업 프로젝트를 마무리하셨네요. 2주간 고생많으셨습니다.

몇가지 아쉬운 점이 있어 변경요청 드립니다. 고생하셨습니다!

2022-04-16 07:41 UTC, ksundong commented on BackEnd/src/main/java/todo/list/controller/CardController.java
> +        return new CommandResultResponse(201, cardCommandResponse);
body에는 응답 데이터만 포함시켜주세요.
응답의 메타 정보를 포함하는 것은 REST API의 안티패턴입니다.

2022-04-16 07:41 UTC, ksundong commented on BackEnd/src/main/java/todo/list/domain/Action.java
> +    }
👍

2022-04-16 07:41 UTC, ksundong commented on BackEnd/src/main/java/todo/list/domain/ActivityLog.java
> +
이게 어떤 이유로 필요한 메서드인가요??

2022-04-16 07:41 UTC, ksundong commented on BackEnd/src/main/java/todo/list/domain/Author.java
> +    private String stringValue;
이게 필요한 이유는 무엇때문인가요?

2022-04-16 07:41 UTC, ksundong commented on BackEnd/src/main/java/todo/list/repository/ActivityLogRepository.java
> +                                        "values(:activity_log_action, :title, :now_status, :create_datetime)";
`String` 의 `+` 연산자를 사용해주신 이유는 무엇인가요?

2022-04-16 07:41 UTC, ksundong commented on BackEnd/src/main/java/todo/list/repository/CardRepository.java
> -        String updateSql = "UPDATE card SET title=:title, contents=:contents, author=:author, update_datetime=:update_datetime WHERE id=:id";
이건 지워지면 안되는 것 아닌가요??

2022-04-16 07:41 UTC, ksundong commented on BackEnd/src/main/java/todo/list/service/ActivityLogService.java
> +@Transactional
클래스 단위로 `@Transactional` 을 적용시켜주신 이유는 무엇인가요~?

2022-04-16 07:41 UTC, ksundong commented on BackEnd/src/main/java/todo/list/service/ActivityLogService.java
>          return activityLogs.stream()
변수를 그대로 inline 시켜도 되지 않을까요??

2022-04-16 07:41 UTC, ksundong commented on BackEnd/src/main/resources/schema.sql
> -set global time_zone = 'Asia/Seoul';
이건 왜 빠졌나용?

2022-04-17 08:02 UTC, hwicode commented on BackEnd/src/main/java/todo/list/controller/CardController.java
> +        return new CommandResultResponse(201, cardCommandResponse);
`CommandResultResponse`를 리턴하는 방식으로 수정하겠습니다!

2022-04-17 08:06 UTC, hwicode commented on BackEnd/src/main/java/todo/list/domain/ActivityLog.java
> +
`ActivityLog`의 필드인 `action`을 꺼내오지 않기 위해서 이렇게 구현했습니다.
아래와 같이 `action`을 꺼내오고 직접 `isMove` 메서드를 실행하는게 더 좋은 방법인지 여쭈어 봐도 될까요?

```java
//before 
if (activityLog.actionIsMove()) {

//after
if (activityLog.getAction().isMove()) { 
```

2022-04-17 08:09 UTC, hwicode commented on BackEnd/src/main/java/todo/list/domain/Author.java
> +    private String stringValue;
클라이언트에서 보여주는 문자열을 사용하는 그대로 `response`를 해주면 안드로이드 분들이 편할 것 같아서 이 필드를 만들었습니다.

하지만 이 부분은 안드로이드 분들의 역할인 것 같아서 이 부분을 삭제하겠습니다!

2022-04-17 08:14 UTC, hwicode commented on BackEnd/src/main/java/todo/list/repository/ActivityLogRepository.java
> +                                        "values(:activity_log_action, :title, :now_status, :create_datetime)";
가독성을 위해서 줄바꿈을 하다가 `+` 연산자를 사용하게 되었습니다.

`StringBuilder`는 `String`과 다르게 기존 데이터에 새로운 데이터를 더하는 방식을 취하기 때문에 속도가 더 빠르기 때문에
`StringBuilder`를 사용하는 방식으로 코드를 수정하겠습니다.

2022-04-17 08:16 UTC, hwicode commented on BackEnd/src/main/java/todo/list/repository/CardRepository.java
> -        String updateSql = "UPDATE card SET title=:title, contents=:contents, author=:author, update_datetime=:update_datetime WHERE id=:id";
안드로이드 분들께서 카드 수정할 때 시간이 갱신되지 않으면 좋겠다고 하셔서 카드 수정시 시간 갱신이 되지 않도록 수정했습니다.
추가적으로 카드 이동시에는 시간이 갱신되도록 구현하였습니다.

2022-04-17 08:21 UTC, hwicode commented on BackEnd/src/main/java/todo/list/service/ActivityLogService.java
> +@Transactional
별 다른 이유 없이 클래스 단위로 `@Transactional`를 지정했습니다.
그런데 `ActivityLogService` 클래스에서는 메소드가 2개밖에 존재하지 않기 때문에 메소드 단위로  `@Transactional`을 적용시켜주는 방식으로 수정하겠습니다.

2022-04-17 08:22 UTC, hwicode commented on BackEnd/src/main/java/todo/list/service/ActivityLogService.java
>          return activityLogs.stream()
가독성을 위해 변수를 지정해줬습니다.

2022-04-17 08:36 UTC, Louie-03 commented on BackEnd/src/main/resources/schema.sql
> -set global time_zone = 'Asia/Seoul';
`set global time_zone = 'Asia/Seoul'`를 사용했을 MySQL의 timezone이 System으로 설정되어 있었습니다.
MySQL의 timezone이 System으로 설정되어 있다면 MySQL이 설치되어 있는 서버의 운영체제인 ubuntu(EC2)의 timezone을 그대로 따라가게 되는걸로 알고 있습니다.
ubuntu(EC2)의 timezone은 UTC로 설정되어 있었기 때문에 `select now()`를 실행하거나 `default current_timestamp`를 통해 자동으로 시간이 입력될 때 UTC 기준으로 시간이 입력되어서 `set global time_zone = 'Asia/Seoul'`를 사용해줬습니다.

하지만 ubuntu(EC2)에서 스프링부트 프로젝트를 실행하고 LocalDateTime.now()를 실행했을 때 ubuntu(EC2)의 기본 timezone이 UTC로 설정되어 있어서 UTC로 저장되어 있었고 결국 ubuntu(EC2)의 기본 timezone을 한국 시간으로 설정했습니다.

ubuntu(EC2)의 기본 timezone을 한국 시간으로 설정한 다음에는 MySQL의 timezone이 System으로 되어 있어도 한국 시간으로 잘 입력되기 때문에 해당 옵션은 제거해줬습니다.

2022-04-17 08:39 UTC, Louie-03 commented
API 명세서 링크를 수정했습니다! 
마지막으로 2주간 정말 고생 많으셨습니다 디온! 감사합니다!

2022-04-17 14:45 UTC, ksundong commented on BackEnd/src/main/java/todo/list/domain/ActivityLog.java
> +
그렇다면 보다 괜찮은 이름을 고민해볼 필요가 있을 것 같아요.
그냥 `isMove` 면 안되었나요?
캡슐화가 잘 지켜졌는지 생각해보면 좋을 것 같습니다.
당연히 아래의 구현은 좋지 않습니다.(디미터 법칙 위반)

2022-04-17 14:46 UTC, ksundong commented on BackEnd/src/main/java/todo/list/repository/ActivityLogRepository.java
> +                                        "values(:activity_log_action, :title, :now_status, :create_datetime)";
속도가 더 빠르다 이런 점보다 더 중요한 점이 있습니다.
`+` 연산을 이용할 때 어떤 일이 일어나는지도 학습해보시길 바랍니다~

2022-04-17 14:46 UTC, ksundong commented on BackEnd/src/main/java/todo/list/repository/CardRepository.java
> -        String updateSql = "UPDATE card SET title=:title, contents=:contents, author=:author, update_datetime=:update_datetime WHERE id=:id";
아하 그런 이슈가 있었군요!

2022-04-17 14:48 UTC, ksundong commented on BackEnd/src/main/java/todo/list/service/ActivityLogService.java
> +@Transactional
메서드의 개수가 중요한건 아닙니다.
중요한건, '왜 그렇게 했는가?'가 중요한 거라고 생각해요.

2022-04-17 14:49 UTC, ksundong commented on BackEnd/src/main/resources/schema.sql
> -set global time_zone = 'Asia/Seoul';
타임존 이슈는 계속 프로젝트를 진행하시면서, 여러가지를 많이 시도해보시길 바랍니다.
저는 개인적으로 약속을 만들어두고 지키는걸 선호했었습니다.
이건 사람마다 다르고 회사마다 달라서, 여러가지를 많이 알면 좋습니다. ㅎㅎ

2022-04-17 14:51 UTC, ksundong approved these changes
고생하셨습니다. 😊

2022-04-17 14:51 UTC, merged