[team-01][BE] API - Todo를 특정 id로 조회 요청
codesquad-members-2022/todo-list pull request #67
Opened 2022-04-07 07:07 UTC by ku-kim

안녕하세요 @Hyune-c ! `donggi` 와 `쿠킴` 입니다!

Todo 를 특정 id 로 조회하는 요청 기능 구현이 완료되어 리뷰 요청 드립니다.

### 💽 Commits

| 요청 | 기능 |
| --- | --- |
| `GET /api/todos/{id}` | 해당 id의 Todo 보낸다. |

**성공**
• GET /api/todos/{id} 요청 값을 받는다.
• DB에 있는 해당 Todo를 보낸다
• 응답은 반드시 todo의 list 형태로 간다. (200 OK)

**실패**
• GET /api/todos/{id} 요청 값을 받는다.
• id에 해당하는 todo가 없는 경우 에러를 응답한다 (404 NOT FOUND)

### 🖼 결과

**테스트**

![Imgur](https://i.imgur.com/rFoHwzz.jpg)

2022-04-07 09:43 UTC, Hyune-c requested changes
수고하셨습니다~

저번 PR에서 질문하신 것 중에 `처음 Rest API를 설계했는데 올바르게 되었는지 궁금합니다.` 라는 것이 있었는데, `올바르게`라는 것에 대해서는 해석의 차이가 있습니다.  
좀 더 생각해보실만한 글을 공유 드립니다.

- REST - REST 좋아하시네
    - http://haah.kr/2017/06/12/rest-the-big-lie/
- 토스ㅣSLASH 21 - 결제 시스템의 SDK와 API 디자인
    - https://www.youtube.com/watch?v=E4_0WWqmF3M

---

테스트를 많이 만들려고 노력하시는 것은 좋습니다.
하지만 지금 만드신 테스트를 보면 거의 비슷한 성격의 것이 레이어별로 반복되고 있습니다.
테스트의 목적에 대해 좀 더 고민해보시면 좋을 것 같습니다.

2022-04-07 09:43 UTC, Hyune-c commented on BE/build.gradle
>  }
scope별로 나누고 적절한 주석을 달아주셨네요. 훌륭합니다. 👍

2022-04-07 09:43 UTC, Hyune-c commented on BE/src/test/java/codesquad/be/todoserver/repository/TodoRepositoryTest.java
> +		assertThat(todo.getStatus()).isEqualTo("todo");
`nit`

여러 개의 `assertThat`을 사용하는 경우 `assertAll`로 묶는 방법도 있습니다.

2022-04-07 09:43 UTC, Hyune-c commented on BE/src/test/java/codesquad/be/todoserver/repository/TodoRepositoryTest.java
> +		Optional<Todo> todo = todoRepository.findById(4444L);
새로 들어온 동료가 `data.sql`에 4444 id인 todo를 만들면 이 테스트는 어떻게 될까요?

2022-04-07 09:43 UTC, Hyune-c commented on BE/src/test/java/codesquad/be/todoserver/repository/TodoRepositoryTest.java
> +		assertThat(todo.isPresent()).isFalse();
assertJ의 API를 좀 더 잘 사용할 수 있지 않을까요?

2022-04-07 09:43 UTC, Hyune-c commented on BE/src/test/java/codesquad/be/todoserver/service/TodoServiceTest.java
> +				Optional.of(new Todo(1L, "Github 공부하기", "add, commit, push", "sam", "todo")));
title을 "DB 공부하기"로 수정하고 assertThat에서는 수정을 누락하면 어떻게 될까요?

2022-04-07 09:43 UTC, Hyune-c commented on BE/src/test/java/codesquad/be/todoserver/repository/TodoRepositoryTest.java
> +	}
지금 이 프로젝트에서 테스트 데이터를 위한 초기화는 어디에서 이루어지고 있을까요?

2022-04-07 09:43 UTC, Hyune-c commented on BE/src/main/java/codesquad/be/todoserver/controller/TodoController.java
> +	private TodoService todoService;
`Autowired`의 필요성에 대해 생각해봅시다.

2022-04-07 09:43 UTC, Hyune-c commented on BE/src/main/java/codesquad/be/todoserver/exception/NoSuchTodoFoundException.java
> +public class NoSuchTodoFoundException extends RuntimeException {
`nit`

CustomException을 만들고 responseCode까지 고려하고 계신다면 `ControllerAdvice`도 고려하시면 좋다고 생각합니다.

2022-04-07 09:43 UTC, Hyune-c commented on BE/src/main/java/codesquad/be/todoserver/domain/Todo.java
> +		this.user = userId;
user와 userId가 같다는건가요? 모호한 느낌이 듭니다..

2022-04-07 09:43 UTC, Hyune-c commented on BE/src/main/java/codesquad/be/todoserver/domain/Todo.java
> +	private LocalDateTime updatedTime;
`nit`

LocalDateTime이면 Date도 들어가는데 접미사가 Time인 것이 적절할까요?   
그러면 updateDateTime이면 적절할까요? 어떻게 생각하시나요?

2022-04-07 09:43 UTC, Hyune-c commented on BE/src/main/java/codesquad/be/todoserver/domain/Todo.java
> +	}
이 정도로 getter 사용이 필요하다면 lombok을 추천합니다.

2022-04-07 09:43 UTC, Hyune-c commented on BE/src/main/java/codesquad/be/todoserver/repository/TodoJdbcRepository.java
> +	}
sql에서 10row가 조회되어도 결론적으로는 findAny()를 통해 1row만 조회되긴 합니다. 
의도하신 로직일까요?

2022-04-07 09:43 UTC, Hyune-c commented on BE/src/main/java/codesquad/be/todoserver/repository/TodoJdbcRepository.java
> +			todo.setUpdatedTime(rs.getObject("updated_time", LocalDateTime.class));
getObject보다 좋은 방법이 있지 않을까요?

2022-04-07 09:43 UTC, Hyune-c commented on BE/src/test/java/codesquad/be/todoserver/service/TodoServiceTest.java
> +			.willThrow(new NoSuchTodoFoundException("조회할 수 없는 Todo 입니다. id : " + 4444));
CustomException을 대상을 아주 명확하게 Todo로 한정했는데, 매번 message String을 주어야 되고, 여기에 Todo라는 단어가 들어가야 할까요?

2022-04-08 01:54 UTC, ku-kim commented on BE/src/test/java/codesquad/be/todoserver/repository/TodoRepositoryTest.java
> +		assertThat(todo.getStatus()).isEqualTo("todo");
assertAll로 묶어서 테스트가 하나 실패하면 멈추는 것이 아닌 테스트 전체를 테스트할 수 있고 가독성을 높일 수 있겠군요!
아래와 같이 사용하려 하는데 어떠신가요?

```java
assertAll(
		() -> assertThat(todo.getId()).isEqualTo(1),
		() -> assertThat(todo.getTitle()).isEqualTo("Github 공부하기"),
		() -> assertThat(todo.getContents()).isEqualTo("add, commit, push"),
		() -> assertThat(todo.getUser()).isEqualTo("sam"),
		() ->assertThat(todo.getStatus()).isEqualTo("todo")
);
```

2022-04-08 01:56 UTC, Hyune-c commented on BE/src/test/java/codesquad/be/todoserver/repository/TodoRepositoryTest.java
> +		assertThat(todo.getStatus()).isEqualTo("todo");
보통은 묶는 것을 추천한다고 합니다.
근데 저는 묶는 거 자체도 보일러 플레이트 아닌가? 싶어서 안묶기도 합니다.

이건 스타일 차이인거 같으니 페어와 협의하시면 될거 같습니다.

2022-04-08 02:08 UTC, ku-kim commented on BE/src/test/java/codesquad/be/todoserver/repository/TodoRepositoryTest.java
> +		assertThat(todo.isPresent()).isFalse();
아래와 같이 사용해보려 합니다

```java
assertThat(todo.isPresent()).isFalse();
```

2022-04-08 02:18 UTC, donggi-lee-bit commented on BE/src/test/java/codesquad/be/todoserver/repository/TodoRepositoryTest.java
> +		Optional<Todo> todo = todoRepository.findById(4444L);
그런 경우 저희가 작성한 테스트 코드 목적과는 다르게 성공하는 케이스가 될 것 같습니다 😅 이 문제에 대해 생각해보다가 두 가지를 생각해보았습니다.

1. 유효하지 않은 id 값에 대한 테스트
`id` 를 `autoincrement` 로  1 씩 증가하게 만들어놓아서 실패 케이스로 -1 과 같은 음수 값을 넣어 실패할 수 밖에 없는 케이스로 만드는 게 해당 테스트가 올바로 작동하는 테스트가 될 수 있을지

2. 유효한 범위의 id 지만 데이터가 없는 경우 (이번에 작성했던 4444L 의 예)
4444L 는 말씀하신 것처럼 `data.sql` 에 4444 인 id 가 존재하게 된다면 테스트의 결과가 바뀌게 됩니다. 그렇다면 유효한 범위의 id 지만 데이터가 없는 테스트 케이스를 만들려면 저장할 수 있는 자료형의 최대값 정도의 수를 입력해서 테스트하면 될지

이 부분에 대한 고민이 있습니다. `Dan` 은 이 부분에 대해서 어떻게 생각하시나요..?? 😅

2022-04-08 02:24 UTC, donggi-lee-bit commented on BE/src/main/java/codesquad/be/todoserver/domain/Todo.java
> +		this.user = userId;
`userId` 로 사용하다가 `user` 가 더 적합하다고 생각하여 바꾸었는데 미처 수정하지 못하고 남아있었습니다 😓 `user` 로 수정하도록 하겠습니다!!

2022-04-08 02:25 UTC, ku-kim commented on BE/src/test/java/codesquad/be/todoserver/service/TodoServiceTest.java
> +				Optional.of(new Todo(1L, "Github 공부하기", "add, commit, push", "sam", "todo")));
실패하게 됩니다. :(
given 데이터와 assert 검증 데이터가 변수가 값으로 되어 있어 둘 다 수정해야하는 어려움이 있네요. 

이런 경우 테스트에 사용되는 값을 변수로 가지고 있으면 될까?란 생각과 검증 부분 데이터를 변수로 빼면 오히려 가독성이 떨어지지 않을까도 고려해보았습니다. 

어떻게 생각하시나요?

2022-04-08 02:30 UTC, donggi-lee-bit commented on BE/src/main/java/codesquad/be/todoserver/controller/TodoController.java
> +	private TodoService todoService;
생성자가 하나일 땐 `@Autowired` 를 명시하지 않아도 되는데 명시되어 있어서 언급하신 게 맞을까요?? `쿠킴`과 협업을 하면서 헷갈릴 수 있다 생각하여 명시하자라고 약속해놓고 써보았는데 언급하신 부분이 제가 이해한 게 맞다면 지우도록 하겠습니다!

2022-04-08 02:34 UTC, donggi-lee-bit commented on BE/src/main/java/codesquad/be/todoserver/repository/TodoJdbcRepository.java
> +	}
해당 `id` 를 가진 todo 의 데이터를 찾기 위해 사용해서 하나의 row 를 찾고자 사용한 게 맞습니다!

2022-04-08 02:36 UTC, donggi-lee-bit commented on BE/src/main/java/codesquad/be/todoserver/exception/NoSuchTodoFoundException.java
> +public class NoSuchTodoFoundException extends RuntimeException {
`ControllerAdvice` 키워드로 학습해보겠습니다. 감사합니다 😄

2022-04-08 02:38 UTC, Hyune-c commented on BE/src/test/java/codesquad/be/todoserver/service/TodoServiceTest.java
> +				Optional.of(new Todo(1L, "Github 공부하기", "add, commit, push", "sam", "todo")));
저는 이럴때 ParameterizedTest를 활용하는 편입니다.
하지만 이것도 학습이 필요한 것이기에 우선 순위를 판단하시어 학습하시면 될 것 같습니다.

- 테스트를 강화할지
- 메인 로직을 더 만들지

2022-04-08 02:40 UTC, Hyune-c commented on BE/src/main/java/codesquad/be/todoserver/domain/Todo.java
> +		this.user = userId;
네이밍은 해결되겠지만, 업무 관점에서 볼 때 user로 수정하기에는 이 필드에 들어가는 것은 userId인 것 같아 여전히 모호합니다. 
todo와 user의 경계에 대해 생각해보면 좋을 것 같습니다.

2022-04-08 02:42 UTC, ku-kim commented on BE/src/test/java/codesquad/be/todoserver/repository/TodoRepositoryTest.java
> +	}
테스트 데이터를 위한 초기화 작업을 하지 못한 문제가 있습니다. :(

@Sql 어노테이션을 추가하여 테스트에 사용될 .sql을 추가해줄 수 있을 거 같습니다.

2022-04-08 02:44 UTC, Hyune-c commented on BE/src/test/java/codesquad/be/todoserver/repository/TodoRepositoryTest.java
> +		Optional<Todo> todo = todoRepository.findById(4444L);
- 원칙적으로는 초기 데이터에서 없는 id를 동적으로 가져올 수 있는 로직을 given절에 만들 것 같습니다.
- 하지만 실무에서는 jpa를 쓰는 편이고 해당 메서드 정도는 보증된 메서드로 간주하기에 이정도의 단위 테스트 로직은 스킵하는 편입니다.

문제가 생길 수 있다는 점만 인지하셨다면 학습과정에서는 넘어가도 괜찮은 수준이라고 생각합니다.

2022-04-08 02:45 UTC, donggi-lee-bit commented on BE/src/main/java/codesquad/be/todoserver/domain/Todo.java
> +	private LocalDateTime updatedTime;
저희 의도와는 다르게 `LocalTime` 클래스를 사용하고 있다는 생각을 할 수도 있을 것 같습니다. 저희의 의도는 Time 이라는 단어에 Date 도 포함이 되어있다고 생각하여 사용했는데 이 경우 여러 사람이 코드를 본다는 가정을 하여 `LocalDateTime` 클래스를 사용하고 있기 때문에 `createdDateTime` 으로 명시해주는 게 더 좋을까요?? 🧐

2022-04-08 02:45 UTC, Hyune-c commented on BE/src/test/java/codesquad/be/todoserver/repository/TodoRepositoryTest.java
> +	}
네. 지금은 main 프로젝트의 sql이 디폴트로 읽혀지는 것 같은데요.
분리하시는 것을 추천드립니다.

2022-04-08 02:45 UTC, ku-kim commented on BE/src/main/java/codesquad/be/todoserver/domain/Todo.java
> +	}
이전 과제들에서 getter, setter 사용 범위 연습을 위해 lombok 사용이 제한되어있었는데 이번 기회를 통해 필요한 곳에 도입해보겠습니다 :)

2022-04-08 02:50 UTC, Hyune-c commented on BE/src/main/java/codesquad/be/todoserver/controller/TodoController.java
> +	private TodoService todoService;
네. 이미 `의존성 주입`이라는 키워드를 학습해보신 것 같지만, Bean 생성을 위한 의존성 주입에 있어 Autowired나 setter가 사용되고 있다면 강력하게 의심해보시는 것을 추천합니다.

2022-04-08 02:50 UTC, ku-kim commented on BE/src/main/java/codesquad/be/todoserver/domain/Todo.java
> +		this.user = userId;
네, 처음에 userId로 User를 User 테이블을 별도로 구분하고 사용하여 했지만 안드로이드 팀과 이야기 나눈 결과 User를 단순 문자열로 가지고 있기로 결정하여 user로 하게 되었습니다.

2022-04-08 02:54 UTC, Hyune-c commented on BE/src/main/java/codesquad/be/todoserver/repository/TodoJdbcRepository.java
> +	}
- 지금은 db에서 id가 unique함으로 1row만 조회될 것입니다.
- 만약 id가 unique하지 않다면  findAny()에서 복수개의 row중 무작위로 조회될 것입니다.
- 즉 매번 같은 결과가 나올 것이라고 확신할 수 없습니다.

조금 많이 나가는거 같아서, 위 내용을 이해하셨다면 넘어가셔도 좋을 것 같습니다.

2022-04-08 02:57 UTC, Hyune-c commented on BE/src/main/java/codesquad/be/todoserver/domain/Todo.java
> +	private LocalDateTime updatedTime;
Java Collection 선언에 빗대어 생각해보시면 조금 더 나은 네이밍이 나올 것 같습니다.
제 생각이 정답이라고 할 수는 없기에 한번 더 의논하신 결과를 듣고 제 생각도 공유하겠습니다.

2022-04-08 03:07 UTC, ku-kim commented on BE/src/test/java/codesquad/be/todoserver/service/TodoServiceTest.java
> +			.willThrow(new NoSuchTodoFoundException("조회할 수 없는 Todo 입니다. id : " + 4444));
message String을 사용하여 exception 때 클라이언트가 어떤 id를 조회하고 있는지 남기고 싶어 string 을 추가했습니다.
이미 명확한 CustomException 명이기에  `"조회할 수 없는 id : " + id`  또는 `"id" + id` 로 간결하게 만들 수 있습니다

2022-04-08 03:08 UTC, donggi-lee-bit commented on BE/src/main/java/codesquad/be/todoserver/repository/TodoJdbcRepository.java
> +			todo.setUpdatedTime(rs.getObject("updated_time", LocalDateTime.class));
생성시간, 수정시간을 `LocalDateTime` 로 저장하고 있어 getTimestamp("created_time").toLocalDateTime() 이렇게 사용하는 게 `getObject()` 보다 사용 목적에 맞아 보이는데 어떻게 생각하시나요?!

2022-04-08 03:17 UTC, Hyune-c commented on BE/src/main/java/codesquad/be/todoserver/repository/TodoJdbcRepository.java
> +			todo.setUpdatedTime(rs.getObject("updated_time", LocalDateTime.class));
네. Object 자체를 사용하는 것보다는 제공되는 api를 활용하는 것이 타입 세이프에 더 도움이 됩니다.

2022-04-08 03:19 UTC, Hyune-c commented on BE/src/test/java/codesquad/be/todoserver/service/TodoServiceTest.java
> +			.willThrow(new NoSuchTodoFoundException("조회할 수 없는 Todo 입니다. id : " + 4444));
네. CustomException을 사용하는 만큼 좀 더 간결한 알림을 할 수 있도록 해보세요. 
반대로 굳이 간결하게 할 필요가 없다면 CustomException을 사용할 이유도 없다고 생각합니다.

2022-04-08 03:23 UTC, donggi-lee-bit commented on BE/src/main/java/codesquad/be/todoserver/controller/TodoController.java
> +	private TodoService todoService;
먼저 모든 경우에 의존성 주입을 생성자로 주입을 하려고 한건데 `@Autowired` 를 필드에 사용하고 있었습니다... 😅 의존성 주입에 있어 `@Autowired` 나 `setter` 가 명시되어있는 경우를 조심하라는 의미가 맞을까요??

2022-04-08 03:25 UTC, ku-kim commented on BE/src/main/java/codesquad/be/todoserver/domain/Todo.java
> +	private LocalDateTime updatedTime;
Java Collection 선언에 빗댄다면  `List` 인터페이스 구현체인 `ArrayList` 또는 `LinkedList` 네이밍을 떠올렸고
LocalDateTime 변수명을 createdLocalDateTime , createdDateTime을 고려했고
좀 더 짧은 `createdDateTime` 이 적절하다고 생각했습니다.

2022-04-08 03:29 UTC, donggi-lee-bit commented on BE/src/main/java/codesquad/be/todoserver/repository/TodoJdbcRepository.java
> +	}
unique 한 id 가 생성되지 않는다면 `findAny()` 가 복수 개의 row 중 무작위로 조회할 여지가 있겠군요... 이 점 인지하고 더 좋은 방법이 있다면 수정하도록 하겠습니다!

2022-04-08 03:30 UTC, Hyune-c commented on BE/src/main/java/codesquad/be/todoserver/domain/Todo.java
> +	private LocalDateTime updatedTime;
구현체는 교체의 대상이기에 추상체로 선언하는 것이 권장됩니다.

- ArrayList 또는 LinkedList를 구현체로 쓰고 List로 선언

이 관점에서 보면 

- createdDateTime도 적절해보입니다.
- 하지만 저 같은 경우 조금 더 추상적으로 하기 위해 createdAt, updatedAt 과 같은 용어를 사용합니다.

2022-04-08 04:20 UTC, ku-kim commented on BE/src/main/java/codesquad/be/todoserver/domain/Todo.java
> +	private LocalDateTime updatedTime;
createdAt, updatedAt 👍

2022-04-09 15:01 UTC, Hyune-c approved these changes

2022-04-10 08:14 UTC, merged