[TEAM-02][BE] TodoList 카드 등록 기능
codesquad-members-2022/todo-list pull request #70
Opened 2022-04-07 14:52 UTC by sally-ksh

내일 배포에 맞춰 우선 등록기능 구현부터 진행했습니다.

저희팀 Sammy 는 배포를 맞고,
Sally 는 Post 요청 처리 부분을 맡았습니다.
Wiki에 json 키 값, RestApi 명세등 아주 일부 시작하면서 맞추기 시작했습니다.
배포후에나 josn 이 어떻게 받아질지 .. 확인할거 같아서 걱정이 됩니다. ㅎㅎ

오늘 그룹미팅을 오전 내내 하고, 오후에 시간 내다보니 늦어졌습니다.
각자 경험 하지 못한 것들로 맡아 작업을 했고,
추후에 작업한 것들을 같이 정리하는 시간을 갖도록 하면서
다소 급하게 진행하고 있습니다.
(Sammy의 내일 면담, 회의로 바쁠거 같아서 서둘렀는데, 면담 취소 됐네요 ㅎㅎ)

기능은 추가되는 대로 pr 보내겠습니다.
첨삭 정리를 하고 싶었는데, 정리되는 대로 보내겠습니다.ㅠ

예외 처리 로직이 아직 작업 되지 않았는데요.
로그 메시지와 예외 처리, 응답 코드 등 좋은 정보 부탁 드립니다.
감사합니다.

2022-04-07 16:12 UTC, Hyune-c requested changes
수고하셨습니다.
대부분 코드에 남겼지만 추가 코멘트를 정리해드립니다.

- lombok을 조금 더 보수적으로 사용해주세요.
- 코드 가독성을 조금 더 고려해주세요. 특히 개행이 잘못된 곳이 많습니다.
- todo와 card의 경계에 대해 좀 더 생각해주세요.
- 패키지 구분은 의도적으로 하지 않으신걸까요?
- 아직 ordering에 대해 개발되지 않았지만, request를 볼 때 우려되는 점이 있어 미리 알려드립니다.
    - 명시적인 order를 받는 경우, 동시에 2명의 사용자가 3의 order로 입력하면 어떻게 되나요?
- 예외처리에 대한 방법은 조금 천천히 생각하셔도 될 것 같습니다.
    - ControllerAdvice에 대해 찾아보시면 좋을 것 같습니다.
    - 테스트 케이스를 만드시면서 예외 처리에 대한 문제가 나올 것이니 이 때 추가 첨삭 드리겠습니다.

2022-04-07 16:12 UTC, Hyune-c commented on backend/todolist/README.md
> +| POST /api/todo     | 새 카드 등록 |
이것이 url convention인가요? 왠지 api 목록처럼 보입니다..

2022-04-07 16:12 UTC, Hyune-c commented on backend/todolist/build.gradle
> +	implementation "io.springfox:springfox-swagger-ui:3.0.0"
swagger를 도입하셨군요. 👍

2022-04-07 16:12 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDto.java
> +	@Data
inner class를 활용하시면서 `Data`를 활용하셨네요. 👍

2022-04-07 16:12 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardApiController.java
> +@RequestMapping("/api/todo")
`nit`

requestMapping을 class 레벨에 붙이는 것과 method 레벨 중 어디에 붙이는 것이 적절할까 생각해봅시다.

2022-04-07 16:12 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardApiController.java
> +	@PostMapping()
괄호가 꼭 필요할까요?

2022-04-07 16:12 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardApiController.java
> +		return ResponseEntity.ok().body(response);
ResponseEntity를 의도적으로 사용하신걸까요?
지금의 구조라면 필요 없어 보입니다.

만약 의도적으로 사용하신거라면 반환형이 모호해 보입니다.

2022-04-07 16:12 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardApiController.java
> +@Slf4j
습관성으로 붙이기 쉬운 어노테이션 중 하나입니다. lombok을 좀 더 보수적으로 사용해봅시다.

2022-04-07 16:12 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/Card.java
> +@Builder
너무 많은 lombok 어노테이션이 제한 없이 사용된 것이 아닐까요?

2022-04-07 16:12 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDao.java
> +				rs.getObject(CARD_WRITING_DATE, LocalDateTime.class),
혹시 getObject보다 명시적인 방법이 있지 않을까요?

2022-04-07 16:12 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDao.java
> +				rs.getString(CARD_SUBJECT),
```suggestion
			Card article = new Card(
			        rs.getLong(CARD_KEY_COLUMN_NAME),
				rs.getString(CARD_SUBJECT),
```

들여쓰기를 일관성있게 해주는 것이 가독성에 좋을 것 같습니다.

2022-04-07 16:12 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDao.java
> +				from(rs.getInt(CARD_TODO_STATUS)),
from을 대해 좀 더 명시적으로 보여줄 수 있지 않을까요?

2022-04-07 16:12 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/Card.java
> +	private Long todoOrder;
card와 todo를 구분하려는 시도는 좋습니다.
하지만 지금의 분리는 경계가 모호한 것 같습니다.

- content 필드는 todo를 명시하지 않은 것을 볼 때 card의 content를 의도하신 것 같습니다.
- 반면 todoOrder는 card의 order와 분리해서 생각하려고 명시하신 것 같습니다.

하나의 예로 지금 card가 가진 필드에서 todo라는 단어를 모두 제거해도 이해하는데 무리가 없을 것 같아요.

2022-04-07 16:12 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/Card.java
> +		private final int number;
db에 저장되는 코드를 고려한 값으로 보입니다.
맞다면 좀 더 명시적인 네이밍을 해주세요.

저는 이 구조를 보면서 `ordinal()`이 떠올랐는데요.
이 부분을 좀 더 공부해보시면 좋을 것 같습니다.

2022-04-07 16:12 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDao.java
> +				rs.getBoolean("deleted"),
왜 이것만 string일까요..?

2022-04-08 00:34 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardApiController.java
> +@RequestMapping("/api/todo")
크랠스 공통이라 class 레벨에 붙였습니다.
무언가 공통으로 처리할때만 사용한다고 생각해서
method 레벨에 이용하는 경우는 어떤 경우일지는 모르겠네요...

2022-04-08 00:35 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardApiController.java
> +		return ResponseEntity.ok().body(response);
추후, 변경이 있을 거 같아요
첫페이지 반환 json에 리스트들이 들어가는데,
그때 다른 객체 타입을 넣드닞 할거 같아서 
일단 응답코드랑 ResponseEntity랑 눈으로 직접 봐두려고 사용했습니다.

2022-04-08 00:35 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardApiController.java
> +@Slf4j
네 그렇습니다

2022-04-08 00:38 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/Card.java
> +@Builder
처음에는 필요해보이는 애들만 getter, setter 했었는데
Dao에서 getter 통해 데이터들을 모두 불러오다보니 
차라리 코드라도 깔끔해지자는 생각이 들었습니다.
저도 최대한 체크하면서 해보고자 @Data 안 쓰고 부분부분 적어놨습니다.....
괜찮을까요?

2022-04-08 00:38 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDao.java
> +				rs.getObject(CARD_WRITING_DATE, LocalDateTime.class),
흐음... 알아보겠습니다.

2022-04-08 00:41 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDao.java
> +				from(rs.getInt(CARD_TODO_STATUS)),
스태틱 클래스명을 보여주는걸 말씀하시는 걸까요..
아니면 메서드명을 말씀하시는 걸까요?

저는 메서드명으로 하면 클래스명하고 중복되는게 저는 편치는 않고,
클래스명도 IDE로 바로 확인가능하고, 상수명으로 TODO_STATUS도 언급되어서
표현할수록 중복으로 보여지기도 해서, 생략하는게 좋다고 생각했습니다.

더 좋은 방법이나 제가 좀 더 다른 시야를 볼 수 있는 게 있을 까요?

2022-04-08 00:42 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/Card.java
> +	private Long todoOrder;
네! 좋습니다. 👍

2022-04-08 00:43 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/Card.java
> +		private final int number;
그렇다면...statusNumber?  .... ㅋㅋ 고민해보겠습니다ㅠ

2022-04-08 00:44 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDao.java
> +				rs.getBoolean("deleted"),
제목과 내용 부분인데요.... 뭔가 다른 점이 있으신가요?

2022-04-08 00:45 UTC, sally-ksh commented on backend/todolist/README.md
> +| POST /api/todo     | 새 카드 등록 |
이전 미션에서 url convention 예제를 따라서 작업했습니다.
명칭 수정 하겠습니다.

2022-04-08 02:00 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/Card.java
> +@Builder
Data는 가장 많은 역할을 해주기에 매우 보수적으로 쓰여야 합니다.  
보통 value object나 dto에만 제한적으로 쓰이는거 같아요.

getter, setter보다는 아래의 관점에서 생각해주시기 바랍니다.

- AllArgsConstructor, Builder 가 둘다 존재해야 될까요?
- 접근 제한자를 두지 않아도 될까요?

2022-04-08 02:06 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDao.java
> +				rs.getObject(CARD_WRITING_DATE, LocalDateTime.class),
```java
rs.getTimestamp("CARD_WRITING_DATE").toLocalDateTime());
```

jdbc에서의 코딩은 오랜만이네요.
혹시 이런 방식을 검색해보실 수 있을까요?

2022-04-08 02:10 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDao.java
> +				from(rs.getInt(CARD_TODO_STATUS)),
이 코드를 따라가기 위해서는 from의 반환형을 알아야합니다.
물론 ide에서는 추적이 쉬워 알 수 있지만, pr에서는 알기 쉽지 않습니다.
즉 가독성을 위해서는 TodoStatus를 붙여서 `TodoStatus.from()` 으로 하면 좋다고 생각합니다.

`상수명으로 TODO_STATUS도 언급되어서` 라고 말하셨는데, 매개변수에서 반환형을 추론하는 것은 일반적이지 않다고 생각합니다.

2022-04-08 02:11 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDao.java
> +				rs.getBoolean("deleted"),
```java
rs.getBoolean("deleted"),
```

다른 필드는 매개변수에 상수를 넣으셨는데, delete만 string 으로 넣으셔서 질문드렸어요.

2022-04-08 02:30 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/Card.java
> +		private final int number;
지금 db에 저장되는 값은 1,2,3 으로 보입니다.
만약 내가 신입 dba라면 1,2,3이라는 값에서 3이 completed라는 것을 유추할 수 있을까요?
현재대로라면 소스단을 보아야만 알 수 있을텐데 불편하지 않을까요?

2022-04-08 02:34 UTC, Hyune-c commented
수정 커밋을 확인했습니다.
Card 객체의 code에 대해서 남긴 코멘트를 추가로 봐주세요.

2022-04-08 02:35 UTC, Hyune-c requested changes
수정 커밋을 확인했습니다.
Card 객체의 code에 대해서 남긴 코멘트를 추가로 봐주세요.

2022-04-08 03:46 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/Card.java
> +		private final int number;
테이블 생성시 description에 적어주는 걸 본적이 있습니다.
저같은 경우는 그런 값들은 테이블 정보 확인을 통해 바로 확인할 수는 있었는데요....

2022-04-08 03:47 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDao.java
> +				rs.getBoolean("deleted"),
한번만 쓰여서, 상수로 하기 아쉽다 생각도 있었고,
delete 애플리케이션 객체에서 제외 시켜야 되나 고민이 있었습니다.
DB에서 조회시에 확인용으로만 쓰이고 해서 .. 남겨뒀었습니다.

애플리케이션에서 쓰이지 않는다면 멤버 변수로 제외하는게 맞을까요?

2022-04-08 03:50 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/Card.java
> +		private final int number;
네. 보완책을 생각하고 계신다면 일단 지금으로 유지해보셔도 좋을 것 같습니다.
아래의 글도 한번 읽어주세요.

https://techblog.woowahan.com/2527/

2022-04-08 03:51 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDao.java
> +				rs.getBoolean("deleted"),
현대의 개발은 하드웨어의 발달로 메모리보다는 협업을 위한 가독성을 우선하는 경우가 많습니다.
이 관점에서 코딩의 일관성이 더 중요하다고 생각합니다.

2022-04-08 05:15 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDao.java
> +				rs.getBoolean("deleted"),
네, 상수로 변경 해놓겠습니다.
감사합니다 👍

2022-04-08 05:17 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/Card.java
> +		private final int number;
변경해 놓도록 하겠습니다. 
여기와서 JPA 사용을 멈췄더니,.. 기억이 안 났던거 같아요.ㅎㅎ
JPA도 String으로 "1" 이라고 했던거 같았고. 그부분들도 언급해주신거 같습니다.
글도 몇 번 더 읽어보면서 잘 정리하겠습니다.
감사합니다.

2022-04-08 05:17 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDao.java
> +				from(rs.getInt(CARD_TODO_STATUS)),
넵! 감사합니다 ^^

2022-04-08 05:21 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDao.java
> +				rs.getObject(CARD_WRITING_DATE, LocalDateTime.class),
아 첫번째 수정에서 적용했는데, 메시지를 바꾸지 않았네요.
이번에 다시 보내면서 상수처리로도 변경했습니다.
조언 감사합니다. 👍 

``` java 
rs.getTimestamp(COLUMN_INDEX_DELETED).toLocalDateTime()
```

2022-04-08 05:46 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/Card.java
> +@Builder
네, 생각지 못한 점들을 집어 주셔서 감사합니다. 🙇‍♀️

단순하게 Dao에서 다 받아온다고 생각했었는데, 그렇지 않은 점을 찾아서 수정했습니다.
Builder 패턴은 Dto에서 쓰는데, 가독성이 좋아보여서 남겨뒀습니다. 괜찮을까요?
``` java
public Card toEntity() {
	return Card.builder()
		.subject(subject)
		.content(content)
		.status(Card.TodoStatus.from(status))
		.order(order)
		.createdAt(LocalDateTime.now())
		.userId(userId)
		.build();
}
```

접근제한자를 proteected로 해서 getter, setter 롬복도 없앴습니다.
이전까지 미션에서는 롬복 제한이 있었는데,
이번에 롬복 쓰면서 Dan이 잘 봐주신 덕에
새롭게 알게된점들이 좋습니다.
감사합니다. 🥇

2022-04-08 05:57 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/Card.java
> +@Builder
builder는 매우 편리하지만 nullsafe하지 못한 위험성이 있기에 보수적으로 사용해야 합니다.
이 점을 알고 계신다면 builder를 어느 경우에 쓰면 되겠다. 라는 생각이 정리 되실거 같아요.

생성자, 빌더, 정적 팩토리 메서드를 공부해보시기를 추천합니다.

2022-04-08 06:06 UTC, sally-ksh commented
> 수정 커밋을 확인했습니다. Card 객체의 code에 대해서 남긴 코멘트를 추가로 봐주세요.

네, 수정해서 커밋 보냈습니다.
상세히 알려주셔서 감사합니다.

2022-04-08 06:19 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDao.java
> +	public static final int COLUMN_INDEX_DELETED = 5;
컬럼의 순서를 가지고 쿼리를 만드는 것은 위험할 것 같은데, 굳이 이렇게 하신 이유가 있을까요?
컬럼 이름으로 할 수 있는 부분이라고 생각되서요.

2022-04-08 06:20 UTC, Hyune-c commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDao.java
> +	public static final int COLUMN_INDEX_DELETED = 5;
그리고 이 컬럼은 Deleted time 으로 보이는데 DELETED boolean과는 다른 값으로 보입니다.

2022-04-08 08:15 UTC, sally-ksh commented on backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDao.java
> +	public static final int COLUMN_INDEX_DELETED = 5;
네 수정했습니다

2022-04-08 08:19 UTC, Hyune-c approved these changes
수고하셨습니다.

2022-04-09 00:07 UTC, merged