[team-07][BE][Jerry & 선을로] 메모리기반으로 기능구현 완료
codesquad-members-2022/todo-list pull request #75
Opened 2022-04-08 05:50 UTC by jeremy0405

안녕하세요 Sigrid!! Jerry, 선을로입니다. 🙇🏻‍♂️🙇🏻‍♂️

첫 주차 2번 째 PR드립니다.

주말 전까지 모든 기능을 구현한 이후에 서버를 배포하기 위해서 빠르게 작업을 하다보니 테스트코드를 작성하지 못했습니다. 😭
다음주 수요일 전까지 db로 변경 및 테스트코드 추가, 코드 리팩토링을 진행해보려고 합니다.

### 한 일

- 카드 수정 구현
  - 카드 동일 status 상태에서 드래그 앤 드랍 수정 구현
  - 카드 다른 status 상태로 드래그 앤 드랍 수정 구현
  - 카드 제목, 내용 수정 구현
- 활동 로그 구현
- API 수정
- AWS 배포

[API 수정 링크](https://github.com/jeremy0405/todo-list/tree/deploy/be)

### 할 일

- 메모리 기반 DB로 서버 변경
- 리팩토링
- 테스트 코드 작성

2022-04-09 06:38 UTC, jypthemiracle requested changes
안녕하세요, 리뷰어 Sigrid Jin입니다. 이번 주도 수고 많으셨습니다.
더 나은 코드의 방향을 위해 같이 논의할 만한 내용을 여러 관점에서 적어두었습니다.
다음 스텝으로 넘어가기 전에 함께 이야기할 수 있기를 희망합니다. 그럼, 답변 기다리겠습니다. 감사합니다.

2022-04-09 06:38 UTC, realsigridjin commented on be/todolist/src/main/java/team07/todolist/controller/CardController.java
> +	public CardController(CardService cardService, ActivityLogRepository activityLogRepository) {
field injection과 constructor injection의 차이는 무엇인가요? 그리고 각각의 장단점에 대해 설명해주세요. [참고할 만한 링크](https://yaboong.github.io/spring/2019/08/29/why-field-injection-is-bad/)

2022-04-09 06:38 UTC, realsigridjin commented on be/todolist/src/main/java/team07/todolist/controller/CardController.java
> +	public void modifyCard(@PathVariable Long id, @RequestBody PatchCard patchCard, HttpServletResponse response) {
`@RequestParam` 과 `@PathVariable` 의 차이는 무엇일까요? 어떤 경우에 사용을 달리하면 좋을까요?

2022-04-09 06:38 UTC, realsigridjin commented on be/todolist/src/main/java/team07/todolist/controller/CardController.java
> +		return activityLogRepository.findAll();
Controller 메소드가 Service 레이어를 거치지 않고 바로 Repository에 접근하도록 구현하신 이유가 있을까요?

2022-04-09 06:38 UTC, realsigridjin commented on be/todolist/src/main/java/team07/todolist/domain/ActivityLog.java
> +		this.time = LocalDateTime.now();
`LocalDateTime` 이 등장했네요. Calendar와 Date 클래스의 차이점, 그리고 각각의 문제점은 무엇일 지 본인만의 답변을 고민해보세요.
[참고할 만한 링크](https://d2.naver.com/helloworld/645609)

2022-04-09 06:38 UTC, realsigridjin commented on be/todolist/src/main/java/team07/todolist/domain/Card.java
> +	public static class Builder {
개인적으로 빌더 패턴을 좋아하지 않기에 한 번 더 딴지를 걸어보겠습니다. 파라미터가 2개 밖에 늘지 않았는데, 생성자에서 빌더 패턴으로 바꾸신 이유가 궁금합니다.

2022-04-09 06:38 UTC, realsigridjin commented on be/todolist/src/main/java/team07/todolist/domain/ActivityLog.java
> +	private Integer type;
불필요한 Wrapper Type이 아닌지, primitive type을 사용할 수는 없을 지 고민해보세요.

2022-04-09 06:38 UTC, realsigridjin commented on be/todolist/src/main/java/team07/todolist/service/ActivityLogService.java
> +	private static final int MOVE = 4;
매직 넘버의 사용은 지양하는 것이 좋다고 생각합니다. 이전 리뷰에도 비슷한 내용을 달아드렸던 것으로 기억하는데요, 최대한 학습 과정에서는 객체지향의 입장에서 고민해보는 것이 맞다고 생각합니다. 매직넘버처럼 절차적으로 구현하지 않고, 인터페이스와 클래스의 개념을 활용하여 리팩토링할 수 있는 방법은 없을까요?

2022-04-09 06:38 UTC, realsigridjin commented on be/README.md
> +| POST | /list/vertical/{id}   | 상 하 드래그 앤 드랍 |
`vertical` 과 `horizon` 을 나누는 것이 맞을 지 잘 모르겠습니다. 카드를 **옮긴다** 는 행위를 API POST를 할 때부터 명시적으로 비즈니스 로직을 분기하는 것이 과연 옳을 지 고민해보시면 좋겠습니다.
설령 컨트롤러 단에서 분기처리하는 것이 필요하다고 결정하시더라도, 같은 섹션 내에서 카드를 이동하는 것인지, 세션 간에 카드를 이동하는 것인지 구분할 수 있는 단어를 선택해야 한다고 생각합니다.
API 단어를 선택하는 측면에서의 이슈가 될 수도 있고, 아니면 컨트롤러에서 유저가 보낼 때 비즈니스 분기를 이 레이어에서 하는 것이 맞는 지에 대한 고민이 될 수도 있습니다.

2022-04-09 06:38 UTC, realsigridjin commented on be/todolist/src/main/java/team07/todolist/controller/CardController.java
> +	@PostMapping("/move/horizon/{id}")
위 API 명세에 상세한 것과 같은 리뷰입니다.

2022-04-09 06:38 UTC, realsigridjin commented on be/todolist/src/main/java/team07/todolist/controller/CardController.java
> +		cardService.dragAndDropHorizon(id, requestCard);
`cardService` 에서 바로 `dragAndDropHorizon` 으로 처리하고 있습니다.
만약 상하 방향과 수직 방향 외에 다른 방향으로 이동할 수 있는 요구사항이 추가된다면, 새로운 함수를 매번 만들어야 하는 상황이 됩니다. `dragAndDrop` 이라는 공통요소를 함께 갖고 있는 함수인데, 매번 요구사항이 추가될 때마다 새로운 함수를 만드는 것이 유지보수의 측면에서 도움이 되지 않는다고 생각합니다. 조금 더 다른 객체지향적인 방법을 고민할 수는 없을까요?

2022-04-09 06:38 UTC, realsigridjin commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +		Integer originStatus = originCard.getStatus();
과도한 Wrapper Class 사용은 아닌지 고민해야 합니다. Primitive Type을 적용하지 않는 이유가 있으실까요?

2022-04-09 06:38 UTC, realsigridjin commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +			.forEach(Card::decreaseRow);
Repository가 직접 비즈니스 로직을 처리하고 있습니다. 다시 말해, 카드를 모두 꺼내서 일일이 row를 줄이거나 늘리고 있습니다. 데이터베이스 레이어와 소통하는 Repository 클래스가 직접 카드의 상태를 저장하는 것을 넘어 적극적으로 카드를 만들고 빌더 패턴을 활용하여 인스턴스를 생성하고 row를 조작하고 있습니다. Repository 레이어의 역할과 책임이라기에는 너무 나간 것이 아닐까 생각합니다.

2022-04-09 06:38 UTC, realsigridjin commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +		Card updateCard = new Card.Builder(originCard).id(id).row(row).status(status).build();
빌더 패턴을 사용하는데 프로퍼티 수가 이 정도밖에 되지 않는다면, 직접 생성자를 사용하여 객체를 생성하는 것이 객체 생성의 안정성 측면에서 좋은 접근이 아닐까 생각합니다.

2022-04-09 06:38 UTC, realsigridjin commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +			.forEach(Card::decreaseRow);
아키텍처의 측면에서, Repository 레이어와 Service 레이어의 차이는 무엇일까요?
[참고할 만한 링크](https://stackoverflow.com/questions/1440096/difference-between-repository-and-service)

2022-04-09 06:38 UTC, realsigridjin commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +				.filter(c -> c.getRow() > oldRow && c.getRow() <= newRow)
store 내부에 있는 카드를 일일이 꺼내서, 비교하고, 조건에 따라 처리하고, 그렇지 않은 경우에는 또 다른 처리까지 모두 한 함수에서 진행하고 있습니다. 더 나은 방법은 없을까요. 하나의 함수에는 하나의 책임과 역할이 있어야 합니다. 하기 링크를 참고해보고, 더 좋은 설계를 고민해보신 후 생각하시게 된 바를 답글로 남겨주실 수 있으실까요?

[참고할 만한 링크](https://jaeyeong951.medium.com/%EA%B0%9D%EC%B2%B4%EC%A7%80%ED%96%A5-5%EC%9B%90%EC%B9%99-solid-ac7d4d660f4d)

2022-04-09 06:38 UTC, realsigridjin commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +		} else {
else를 사용하지 않고, 바로 early return 할 수 있는 방법을 고민해봅시다.
[참고할 만한 링크](https://quinngil.com/2018/09/16/uobjects-switch-and-else-always-evil/)

2022-04-09 06:38 UTC, realsigridjin commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +		store.put(9L, new Card.Builder().id(9L).userId("iOS").title("제목9").content("내용9").row(3).status(3).build());
오우야.. 깜짝 놀랐습니다. 초기 migration할 때 데이터베이스를 초기화할 수 있는 `data.sql` 를 사용하시는 것은 어떨까요?
[참고할 만한 링크](https://www.baeldung.com/spring-boot-data-sql-and-schema-sql)

2022-04-09 06:38 UTC, realsigridjin commented on be/todolist/src/main/java/team07/todolist/service/ActivityLogService.java
> +		ActivityLog activityLog = new ActivityLog(requestCard.getTitle(), ADD, null, requestCard.getStatus());
`null` 타입을 직접 다루는 것은 위험하다고 생각합니다. Null Object Pattern 등을 이용할 수 있는 방법에 대해서 고민해보세요. 혹은, 생성자 차원에서 여러 경우의 생성자를 만들어 null 처리는 ActivityLog 내부적으로 처리할 수 있도록 리팩토링 하시는 것을 고민해보시는 것은 어떨까요?

[참고할 만한 링크](https://johngrib.github.io/wiki/pattern/null-object/)

2022-04-09 06:38 UTC, jypthemiracle commented on be/todolist/src/main/java/team07/todolist/service/CardService.java
> +		activityLogService.saveLog(requestCard);
ActivityLogService를 통해, Logging 기능을 구현하려고 하시는 것 같은데요. Interceptor에 대해 알고 계시나요? Interceptor 개념을 학습해보고, 이 방식으로 ActivityLog 기능을 구현해보시면 어떨까요?

학습 키워드: **Spring AOP 및 Interceptor**

[참고할 만한 링크](https://goodgid.github.io/Spring-HandlerInterceptor/)

2022-04-09 06:38 UTC, realsigridjin commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +		Card cardWithId = new Card.Builder(card).id(id).build();
지난 리뷰에서 지적했듯이, 매직넘버와 switch 문 사용은 지양하는 것이 좋습니다.
[switch와 else는 언제나 악의 축이다](https://quinngil.com/2018/09/16/uobjects-switch-and-else-always-evil/)
[매직넘버를 피해야 하는 이유](https://velog.io/@conficker77/Java-Java-%EB%A6%AC%ED%8C%A9%ED%86%A0%EB%A7%81-%EB%A7%A4%EC%A7%81%EB%84%98%EB%B2%84)

어떻게 리팩토링 할 수 있을 지 고민하는 것은 어떨까요?

2022-04-09 06:38 UTC, realsigridjin commented on be/todolist/src/main/java/team07/todolist/repository/MemoryActivityLogRepository.java
> +	public ActivityLog save(ActivityLog activityLog) {
요구사항에 하기와 같은 내용이 명시되어 있습니다.
```
데이터베이스는 Spring JDBC를 통해 연동하고 필요한 SQL문을 직접 작성한다.
```
직접 SQL 문을 구현해보시는 것은 어떨까요?

2022-04-09 06:38 UTC, jypthemiracle commented on be/todolist/src/main/java/team07/todolist/service/CardService.java
> +		Card updateCard = cardRepository.updateStatusAndRow(id, requestCard.getRow(),
프로퍼티를 직접 꺼내서 쓰기 보다는, 프로퍼티를 받아서 어떻게 가공할 지는 넘겨받는 함수에게 역할을 위임하도록 구현할 수 있을 것입니다. 왜냐하면 넘겨받는 함수의 책임과 역할에 따라 스스로 기능을 어떻게 구현할 것인가를 고민해야 하지, 외부에서 이런 프로퍼티를 사용하라고 강제하는 것은 객체의 자율성을 해치는 일이라고 생각합니다. 제가 남겨드린 리뷰에 대해 생각해보시고 답변을 남겨주세요. 기다리겠습니다.

이러한 측면에서 `requestCard` 를 가지고 있는 프로퍼티를 강제로 꺼내서 사용하는 것이 아니라, DTO 객체 그 자체를 넘겨주기만 하는 것이 유지보수 측면에서 유리한 코드라고 생각합니다.

2022-04-09 17:47 UTC, jeremy0405 commented on be/todolist/src/main/java/team07/todolist/controller/CardController.java
> +	public CardController(CardService cardService, ActivityLogRepository activityLogRepository) {
### field injection

외부에서 주입할 수 있는 방법이 없어서 구현체를 마음대로 바꿔 낄 수 없습니다. 이러한 특징 때문에 테스트코드 작성하도 어려워지게 됩니다. 또한 구현체를 변경할 시 클래스에서 직접 구현체를 변경해야 합니다.
객체 생성시점에 순환참조가 일어나는지 아닌지 발견할 수 있는 방법이 없습니다.
테스트 클래스에서는 간단히 주입을 하기 위해서 field injection을 통해 구현체를 정하는 경우가 많은 것으로 알고 있습니다.

### constructor injection

밖에서 주입을 받기 때문에 주입 로직을 한 군데에서 관리하도록 설계할 수 있습니다. 또한 생성자 주입을 통해 구현체를 정하기 때문에 mock이나 stub을 통한 테스트코드 작성이 쉬워집니다.

2022-04-09 17:47 UTC, fpzk5656 commented on be/todolist/src/main/java/team07/todolist/controller/CardController.java
> +	public CardController(CardService cardService, ActivityLogRepository activityLogRepository) {
필드 주입은 setter로 인스턴스를 주입 받는 방식이고,
생성자 주입은 생성자로 인스턴스 주입 받는 방식입니다.
필드 주입은 편하다는 장점이 있지만, final 사용이 안되서 불변성 보장도 어렵고, 객체 생성 시점에 순환참조가 일어나는지 발견할 수 있는 방법이 없어서 순환참조 방지가 어렵습니다.
반면, 생성자 주입은 의존관계 설정이 되지 않으면 객체생성이 불가하다는 불편함이 있지만,
필요한 필드를 final로 선언해서 불변성 보장이 가능하고, 순환 참조시 앱구동이 실패하기 때문에 순환참조를 예방할 수 있습니다.

2022-04-09 17:47 UTC, fpzk5656 commented on be/todolist/src/main/java/team07/todolist/controller/CardController.java
> +	public CardController(CardService cardService, ActivityLogRepository activityLogRepository) {
필드 주입은 setter로 인스턴스를 주입 받는 방식이고,
생성자 주입은 생성자로 인스턴스 주입 받는 방식입니다.
필드 주입은 편하다는 장점이 있지만, final 사용이 안되서 불변성 보장도 어렵고, 객체 생성 시점에 순환참조가 일어나는지 발견할 수 있는 방법이 없어서 순환참조 방지가 어렵습니다.
반면, 생성자 주입은 의존관계 설정이 되지 않으면 객체생성이 불가하다는 불편함이 있지만,
필요한 필드를 final로 선언해서 불변성 보장이 가능하고, 순환 참조시 앱구동이 실패하기 때문에 순환참조를 예방할 수 있습니다.

2022-04-09 17:49 UTC, fpzk5656 commented on be/todolist/src/main/java/team07/todolist/controller/CardController.java
> +	public void modifyCard(@PathVariable Long id, @RequestBody PatchCard patchCard, HttpServletResponse response) {
uri를 통해 전달된 값을 파라미터로 받아오는 역할 인데
uri에 그냥 값만 표기하는 RESTful방식에는 @PathVariable을 사용하고,
key를 표기하는 쿼리 스트링 방식에는 @RequestParam입니다.
@PathVariable은 Rest 통신할 때 많이 쓰이고,
@RequestParam은 Get 방식 통신할 때 많이 쓰인다고 배웠습니다. NULL 값 허용이랑, 키:밸류 값으로 보낼 수 있으며
또한 꼭 uri를 통해 전달된 값이 아니더라도, ajax 요청을 통해 body에 담아온 데이터를 여러 타입으로 받는게 가능하다고 배웠습니다.
때문에 각자 상황에 맞게 사용하면 될 것 같습니다.

2022-04-09 17:49 UTC, jeremy0405 commented on be/todolist/src/main/java/team07/todolist/controller/CardController.java
> +		return activityLogRepository.findAll();
빠르게 구현 후 서버를 열기 위해서 코드의 품질에 많은 신경을 못썼습니다 😭

바로 Repository에 접근하도록 한 다른 이유는 없으며 서비스 레이어를 거치도록 변경하겠습니다!

2022-04-09 17:49 UTC, jeremy0405 commented on be/todolist/src/main/java/team07/todolist/domain/ActivityLog.java
> +		this.time = LocalDateTime.now();
Calendar와 Date 클래스는 불변 객체가 아니라서 날짜를 지정을 다시 하는 것이 가능합니다. 이 때문에 사용하는 쪽에서 Calendar와 Date 변수가 이전과 동일한 정보를 갖고있다고 확신할 수 없습니다. 또한 Calendar와 Date는 개발자들이 실수하기 쉽다는 단점이 있습니다.

따라서 현재 java에서는 불변 객체인 LocalDateTime, LocalDate, LocalTime Class 사용을 권장하고 있습니다. 위의 클래스들은 불변 객체이며 다양한 메서드들과 일관된 상수들을 제공하여 개발자들의 실수를 예방하고 있습니다.

2022-04-09 17:50 UTC, jeremy0405 commented on be/todolist/src/main/java/team07/todolist/domain/Card.java
> +	public static class Builder {
한 번도 써본적 없는 패턴이라서 한 번 적용해보고 싶은 마음에 바꾸게 되었습니다.

현재는 빌더 패턴과 적합하지 않은 것 같아 제거한 후에 생성자로 변경하겠습니다!

2022-04-09 17:51 UTC, jeremy0405 commented on be/todolist/src/main/java/team07/todolist/domain/ActivityLog.java
> +	private Integer type;
id와 type은 int로 사용이 가능 할 것 같습니다. 반영해보겠습니다.

2022-04-09 17:53 UTC, jeremy0405 commented on be/README.md
> +| POST | /list/vertical/{id}   | 상 하 드래그 앤 드랍 |
카드의 이동 요청이 들어올 시 카드가 상하 또는 좌우로 이동했는지 판단하기 위해서는 클라이언트가 가장 잘 알고 있다고 생각해서 API POST 할 때부터 다른 URL을 매칭했습니다. 만약 동일하게 POST /list/move/{id} 로 URL을 매칭한다면 서버에서는 request body에 들어온 카드 데이터와 repository에서 id에 해당하는 카드 데이터를 비교하여 상하, 좌우 이동을 판단해야 합니다. 이 때문에 두개의 상이한 로직이 하나의 service 메소드가 담당하게 되는 것 같아 아예 API POST부터 분기하여 다른 컨트롤러로 받는 것이 좋다고 판단해서 현재처럼 진행하게 되었습니다.

2022-04-09 17:54 UTC, fpzk5656 commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +		Card cardWithId = new Card.Builder(card).id(id).build();
Enum클래스를 활용하라는 말씀으로 이해했는데, 제가 맞게 이해한건지에 대해서 여쭤봐도 되겠습니까?

2022-04-09 17:55 UTC, jeremy0405 commented on be/todolist/src/main/java/team07/todolist/controller/CardController.java
> +		cardService.dragAndDropHorizon(id, requestCard);
`CardService` class 추상클래스로 만든 후 `dragAndDrop()` 을 추상메서드로 정의한 이후에 `CardService` 를 구현하며 Horizon 을 지원하는 클래스와 Vertical 을 지원하는 클래스를 만들어서 다형성을 사용하여 `dragAndDrop()` 을 호출하는 방법이 떠오릅니다.

위와 같은 방법도 좋은 방법이 될 수 있을까요??

2022-04-09 17:55 UTC, fpzk5656 commented on be/todolist/src/main/java/team07/todolist/service/ActivityLogService.java
> +	private static final int MOVE = 4;
Enum클래스를 활용하라는 말씀으로 이해했는데, 제가 맞게 이해한건지에 대해서 여쭤봐도 되겠습니까?

2022-04-09 17:55 UTC, jeremy0405 commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +		Integer originStatus = originCard.getStatus();
빠르게 구현을 진행하다보니 null에 대해 생각을 하지 않도록 모든 변수들을 다 Wrapper로 만든 것 같습니다.

Primitive type이 가능한 변수들은 Primitive Type으로 리팩토링해보겠습니다.

2022-04-09 17:57 UTC, jeremy0405 commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +			.forEach(Card::decreaseRow);
1. Repository의 역할과 책임이 서비스의 영역까지 침범했다고 느껴지네요. 위와 로직을 서비스쪽으로 어떻게 옮길 수 있을지 생각해본 후 리팩토링 진행해보겠습니다!!


2. Repository 레이어는 데이터를 저장하는 레이어이고 Service 레이어는 컨트롤러에서 받은 데이터를 가공 한 후 가공된 데이터를 Repository에 저장하도록 메시지를 보내는 레이어입니다.

2022-04-09 17:57 UTC, jeremy0405 commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +				.filter(c -> c.getRow() > oldRow && c.getRow() <= newRow)
SRP 단일 책임 원칙에 위배되고 있습니다. 메서드에 하나의 책임과 역할을 부여한 이후에 재사용을 하는 것이 바람직해 보입니다.

먼저 카드를 꺼내서 비교해서 boolean 값을 판별하는 메소드 분리, filter 이후 카드의 내부 row값을 증감하는 로직 분리 정도로 나눌 수 있을 것 같습니다.

2022-04-09 17:58 UTC, jeremy0405 commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +		} else {
else 전에 return 을 통해서 early return으로 변경하겠습니다!!

2022-04-09 17:58 UTC, jeremy0405 commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +		store.put(9L, new Card.Builder().id(9L).userId("iOS").title("제목9").content("내용9").row(3).status(3).build());
현재 데이터베이스를 연결하지 않고 JVM 메모리 기반으로만 서비스를 하고 있어서 위와 같이 하게 되었습니다. 다음주에 데이터베이스를 연결해서 작업을 할 때는 data.sql을 통해 초기화를 해보겠습니다!

2022-04-09 17:59 UTC, jeremy0405 commented on be/todolist/src/main/java/team07/todolist/service/ActivityLogService.java
> +		ActivityLog activityLog = new ActivityLog(requestCard.getTitle(), ADD, null, requestCard.getStatus());
Optional 사용을 고려해보겠습니다!

2022-04-09 17:59 UTC, jeremy0405 commented on be/todolist/src/main/java/team07/todolist/service/CardService.java
> +		activityLogService.saveLog(requestCard);
다음 주에 db를 연동시키면서 Interceptor 를 이용해서 Logging 기능을 구현해보려고 시도해보겠습니다!

2022-04-09 18:00 UTC, jeremy0405 commented on be/todolist/src/main/java/team07/todolist/repository/MemoryActivityLogRepository.java
> +	public ActivityLog save(ActivityLog activityLog) {
이것 또한 다음 주에 db를 연동시키면서 SQL문을 구현해보겠습니다!

2022-04-09 18:04 UTC, jeremy0405 commented on be/todolist/src/main/java/team07/todolist/service/CardService.java
> +		Card updateCard = cardRepository.updateStatusAndRow(id, requestCard.getRow(),
지금 다시 생각해보니 `cardRepository.updateStatusAndRow()`에 위임할 수 있는 일을 너무 강제했다는 생각이 드네요. updateStatusAndRow에서 사용하는 DTO에 변경이 생긴다면 현재 서비스까지 변경이 강제되는 단점도 있을 것 같습니다.

DTO 객체 자체를 넘겨주도록 변경하겠습니다.

2022-04-09 19:15 UTC, fpzk5656 commented on be/todolist/src/main/java/team07/todolist/domain/ActivityLog.java
> +		this.time = LocalDateTime.now();
Date와 Calendar를 많이 사용해보지 않아서 체감해서 얻은 결론은 아니지만
위에 알려주신 링크 블로거의 내용으로 보건데 크게
- 불변 객체가 아니다.
- 상수 필드를 남용하게 한다.
- 월 지정이 헷갈리게 되어있다.
- 요일 상수가 일관성이 없다.
- Date와 Calendar 객체의 역할 분담
- 하위클래스 timestamp의 대칭 문제
등의 문제점이 있으며
차이점으로는 Date 클래스만으로 수행하기 어려운 년/월/일 같은 날짜 단위 계산과 특정시간대의 날짜 생성을 수행하기 위해 Calendar클래스가 존재한다 볼 수 있는데...

문제는 날짜 연산할 때 Calendar만으로 안되고, Calendar 클래스안에서 다시 Date를 클래스를 생성하는 등 불필요해 보이는 과정이 있기에 그다지 의미 있는 차이점이 맞나?싶습니다.
위 클래스들의 단점을 극복하기 위해 자바8에 time패키지가 나온 것 같고,
국내서비스는 LocalDateTime, 글로벌 서비스는 timezone이 추가된 ZonedDateTime을 사용하는게 좋다는 점을 학습 할 수 있었습니다.

2022-04-09 21:32 UTC, jypthemiracle commented on be/todolist/src/main/java/team07/todolist/controller/CardController.java
> +	public CardController(CardService cardService, ActivityLogRepository activityLogRepository) {
말씀하신 바 mock 등의 구현체를 생성자 시점에서 지정하는 것은 개발자에게 아주 강력한 자유도를 부여합니다. 앞으로 과정을 진행하면서 강점의 맛을 느껴보시죠.

2022-04-09 21:33 UTC, jypthemiracle commented on be/todolist/src/main/java/team07/todolist/domain/ActivityLog.java
> +	private Integer type;
왜 Wrapper Type 사용을 남발하지 마라고 하는 것일지 본인만의 생각을 적어보세요.

2022-04-09 21:33 UTC, jypthemiracle commented on be/todolist/src/main/java/team07/todolist/domain/ActivityLog.java
> +	private Integer type;
왜 Wrapped Type의 사용을 남발하지 마라고 하는 걸까요? 본인만의 생각을 적어보세요.

2022-04-09 21:34 UTC, jypthemiracle commented on be/todolist/src/main/java/team07/todolist/domain/ActivityLog.java
> +	private Integer type;
왜 Wrapped Class의 사용을 남발하지 마라고 하는 것일지 본인만의 생각을 적어보세요. Primitive Type에는 어떤 장점과 단점이 있을까요? 언제 Wrapped Class와 Primitive Type의 사용을 달리 해야 할까요?

2022-04-09 21:36 UTC, jypthemiracle commented on be/todolist/src/main/java/team07/todolist/service/ActivityLogService.java
> +	private static final int MOVE = 4;
Enum을 사용하라는 특정한 방법에 대한 지시는 아니었는데요. 하지만 현 시점에서 Enum을 적용해보고, 어떻게 매직넘버의 사용과 비교하여 달라졌는지 본인의 경험을 적어주세요.

[참고할 만한 링크](https://techblog.woowahan.com/2527/)

2022-04-09 21:42 UTC, jypthemiracle commented on be/README.md
> +| POST | /list/vertical/{id}   | 상 하 드래그 앤 드랍 |
그렇다면 POST 내부에 move URL로 요청을 보낼 때 DTO의 내용에 vertical인지 horizon인지 명시한 후, 컨트롤러는 이를 읽어 컨트롤러 단에서 어느 서비스 메소드로 분기처리 할지 결정하도록 구현하면 어떨까요? 만약 그렇게 구현하겠다고 결정하신다면, 컨트롤러에 불필요한 비즈니스 로직을 최소한으로 추가하면서도 구현할 수 있는 방법은 또 없을까요?

개인적으로는 vertical이나 horizon은 비즈니스 로직 상의 문제라고 생각하고, API를 사용하는 클라이언트 입장에서는 움직인다(move) 라는 것이 하나의 행위(behaviour)로 받아들일 것 같으므로 하나의 URL로 통합하는 것이 좋다는 의견입니다.

2022-04-09 21:44 UTC, jypthemiracle commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +				.filter(c -> c.getRow() > oldRow && c.getRow() <= newRow)
객체지향 생활체조 원칙 중 하나인 디미터 법칟(The law of Demeter)를 학습하고 적용해보세요. 어떻게 리팩토링이 가능할까요?

[참고할 만한 링크](https://tecoble.techcourse.co.kr/post/2020-06-02-law-of-demeter/)

2022-04-09 21:46 UTC, jypthemiracle commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +		} else {
왜 else를 쓰지 말고 early return을 해야 하는 것일까요? 본인의 생각을 들려주세요.

2022-04-09 22:20 UTC, fpzk5656 commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +			.forEach(Card::decreaseRow);
Repository의 역할이 Service로 넘어오지 않도록,
저장소의 역할에 한정 시키고,
데이터의 가공은 Service쪽에서 처리할 수 있도록 수정해보겠습니다

2022-04-09 22:22 UTC, fpzk5656 commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +		Card updateCard = new Card.Builder(originCard).id(id).row(row).status(status).build();
굳이 쓰지 않아도 되는 부분에 대한 지적 감사합니다.
하마터면 그냥 넘어갈뻔한 부분이었네요

2022-04-09 22:34 UTC, fpzk5656 commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +		} else {
else는 조건 범위의 한정을 특정한 것보다 더 나아갈 우려가 있는데다가
코드를 보는 입장에서도 읽기 편하지 않기 때문에라는 생각이 들었습니다.
즉 조건이 명시적이지가 않아서
else는 코드를 읽는 사람 입장에서도 많은 생각을 할 여지를 남기기 때문이라고 생각합니다.

2022-04-09 23:04 UTC, fpzk5656 commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +				.filter(c -> c.getRow() > oldRow && c.getRow() <= newRow)
예를 들어 `Card` 클래스에 `checkRowIsHeight(int oldRow, int newRow)` 같은 메소드를 만들어서(매개인자를 int가 아니라 Card로 해도 될런지는 따로 고민해보겠습니다)
`filter`에 있는 `c -> c.getRow() > oldRow && c.getRow() <= newRow` 이러한 코드를 위에서 만든 메소드로 대체하면
필터에서 Card가 일일이 getRow()로 꺼내서 비교하는 행위를 할 필요가 없어집니다.

2022-04-09 23:52 UTC, jypthemiracle commented on be/todolist/src/main/java/team07/todolist/controller/CardController.java
> +		cardService.dragAndDropHorizon(id, requestCard);
한 번 그렇게 진행해보시죠.

2022-04-10 02:15 UTC, jeremy0405 commented on be/README.md
> +| POST | /list/vertical/{id}   | 상 하 드래그 앤 드랍 |
클라이언트에서 API에 vertical과 horizon에 대한 정보를 같이 보내달라고 하면 더 좋은 설계가 될 수 있겠네요!! 이처럼 하면 컨트롤러에서 분기 후에 알맞은 서비스를 호출하는 것도 가능하겠어요. 아직 컨트롤러에 불필요한 비즈니스 로직을 최소한으로 추가하는 방법은 잘 떠오르지 않지만 리팩토링하면서 생각해보겠습니다! 클라이언트 측과 상의 후에 변경하도록 해보겠습니다. 😄

좋은 인사이트 감사합니다!!

2022-04-10 02:21 UTC, jeremy0405 commented on be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
> +		Card cardWithId = new Card.Builder(card).id(id).build();
질문의 의도를 잘 파악하지 못했습니다.

현재 `Card cardWithId = new Card.Builder(card).id(id).build();` 부분은 매직넘버가 들어가 있지 않다고 생각이 되는데 조금 더 힌트를 주실 수 있을까요? 🥹

2022-04-10 02:30 UTC, jeremy0405 commented on be/todolist/src/main/java/team07/todolist/domain/ActivityLog.java
> +	private Integer type;
Wrapper Class를 사용하게 되면 객체이기 때문에 객체 헤더가 필요하고 이는 필연적으로 primitive type에 비해 더 많은 메모리 용량을 요구한다는 단점이 있습니다. 장점으로는 객체이기 때문에 Null값이 가능하다는 것 입니다.

기본적으로는 비용이 싼 primitive type을 쓰는 것이 좋지만 Collection 자료구조에는 제네릭스만이 들어갈 수 있으므로 primitive type을 넣게 된다면 boxing으로 인해 비용이 증가하는 경우도 있습니다. 

그러므로 변수를 어떻게 사용할 지 생각한 후에 만약 null이 할당될 가능성이 없고 Collection 자료구조에 담을 필요가 없다면 비용적인 측면에서 primitive type을 쓰는 것이 좋다고 생각합니다.

2022-04-10 03:11 UTC, fpzk5656 commented on be/todolist/src/main/java/team07/todolist/domain/ActivityLog.java
> +	private Integer type;
Wrapper Class는 DB와 연결시 view와 주고받는 객체에 null을 받아야할 경우나 제네릭이 쓰이는 경우(예를 들면 Collection 자료구조 같은..)에 쓰입니다.
Primitive Type은 사용시 언박싱 과정이 없기에 메모리 측면에서 훨씬 효율적입니다.
단점은 null로 초기화 할 수 없으며, 제네릭에 쓰일 수 없다는 문제가 있습니다.

두 타입을 만약 같은 인자를 넘겨받는 상황에서 혼용해서 쓰면 자동박싱과 자동언박싱으로 인해 많은 메모리 낭비로 속도저하가 발생할 수 있습니다.
때문에 null이 할당될 가능성이 있고, Collection 자료구조에 담을 필요가  있다면Wrapper Class
그외의 경우엔 Primitive Type을 쓰는 것이 효율적이기에 DTO와 컨트롤러 설계할 때 잘 구분해주어야 합니다.

2022-04-11 11:09 UTC, jypthemiracle commented
이번 주도 힘차게 보내시길 바랍니다. 그럼 이번 리뷰가 돌아오는 주차의 리뷰에 어떻게 반영될 지 기대하겠습니다. 화이팅!

2022-04-11 11:09 UTC, merged