[Team26 - BE] 히스토리 API 구현 및 카드 API 구현 중
codesquad-members-2022/todo-list pull request #82
Opened 2022-04-08 07:36 UTC by ak2j38

안녕하세요! `데이먼`과 `아더`입니다.
항상 고생하시는 리뷰어님 감사합니다!

## 구현사항
- [x] mysql에 연결하기 전 h2를 통해 개발 및 테스트 진행
- [x] 히스토리 API 작업 중
- [x] 카드 API 작업 중
- [x] `schema.sql`, `data.sql`을 통해 데이터베이스 테이블 생성 및 초기 데이터 셋팅

## 고민사항
  1. 수요일 PR에 비해 많은 부분을 진행하지 못했는데 진행을 못한 부분에 대해서도 PR을 보내는 것이 맞을까요...?!
  2. 현재 `history 테이블`에 데이터를 추가할 때 `card`에서 `getter`를 통해 정보를 가져와서 저장하게 되는데 이 부분이 맞는 로직인지, 테이블 설계가 잘 되어있는지 궁금합니다!

감사합니다 🤗

2022-04-08 15:14 UTC, Min-92 requested changes
안녕하세요 왕민입니다.

코멘트 남겨 드린부분 고민해보시고 반영해주세요 :)

PR은 시간약속이 정해져 있으니, 많은 구현이 되지 않았더라도 작업한 만큼 시간 맞춰서 올려주세요 :)
history는 코멘트 변경점과 그 외에도 변경사항이 필요해보이니 좀 더 지켜보겠습니다 .

2022-04-08 15:14 UTC, Min-92 commented on BE/src/main/java/com/team26/todolist/controller/CardController.java
> +
👍

2022-04-08 15:14 UTC, Min-92 commented on BE/src/main/java/com/team26/todolist/controller/CardController.java
> +
생성자 주입으로 의존성 주입을 해주셨네요 👍
다른 DI 방식과 장단점에 대해서도 학습해보세요 :)

2022-04-08 15:14 UTC, Min-92 commented on BE/src/main/java/com/team26/todolist/controller/CardController.java
> +
모든 cardStatus에 대해서 조회할 필요는 없을까요?

2022-04-08 15:14 UTC, Min-92 commented on BE/src/main/java/com/team26/todolist/controller/CardController.java
> +
직접 구현하는 validation 말고 어노테이션을 활용한 다른 방식이 없는지 찾아보세요 :)

2022-04-08 15:14 UTC, Min-92 commented on BE/src/main/java/com/team26/todolist/controller/CardController.java
> +
별개로 String 관련 많은 기능을 제공하는 [apache의 StringUtils ](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html)라이브러리가 있습니다.
String 관련 편한 기능을 많이 제공하니 참고하세요.

2022-04-08 15:14 UTC, Min-92 commented on BE/src/main/java/com/team26/todolist/controller/CardController.java
> +    @PutMapping
PUT으로 변경해주셨는데 리뷰 때문에 변경하신게 아니고 의도한 동작이 바뀐거겠죠?
저번에 드린 리뷰는 참고차 드린거였습니다 :)

2022-04-08 15:14 UTC, Min-92 commented on BE/src/main/java/com/team26/todolist/controller/CardController.java
> +        CardResponse movedCard = cardService.moveCard(cardMoveRequest);
클라이언트 입장에서는 카드가 이동(move)하는 동작이겠지만, 서버 입장에서 동작이 이동(move)일까요? 한번 고민해보세요:)

2022-04-08 15:14 UTC, Min-92 commented on BE/src/main/java/com/team26/todolist/controller/HistoryController.java
> +    @ResponseStatus(HttpStatus.OK)
response status를 200으로 고정한 이유가 있을까요?

2022-04-08 15:14 UTC, Min-92 commented on BE/src/main/java/com/team26/todolist/dto/request/CardDeleteRequest.java
>  }
Java는 생성자가 없는경우 기본생성자를 만들어줍니다.
Request DTO에 다른 생성자가 추가되면 어떤 일이 생길까요?
ex. public CardDeleteRequest(Long id) {
// ...
}

또 기본생성자가 없으면 @Requestbody는 어떻게 동작할까요?
[관련 글 하나](https://velog.io/@conatuseus/RequestBody%EC%97%90-%EC%99%9C-%EA%B8%B0%EB%B3%B8-%EC%83%9D%EC%A0%95%EC%9E%90%EB%8A%94-%ED%95%84%EC%9A%94%ED%95%98%EA%B3%A0-Setter%EB%8A%94-%ED%95%84%EC%9A%94-%EC%97%86%EC%9D%84%EA%B9%8C-2-ejk5siejhh) 첨부 드려요

2022-04-08 15:14 UTC, Min-92 commented on BE/src/main/java/com/team26/todolist/dto/request/CardRegistrationRequest.java
>      private String cardStatus;
cardStatus를 enum클래스 대신 String을 사용하는 이유가 있을까요?

2022-04-08 15:14 UTC, Min-92 commented on BE/src/main/java/com/team26/todolist/dto/response/CardResponse.java
> +    }
도메인 객체 -> dto 쉽게 변경할수 있도록 했네요👍
static메소드 외에도 생성자를 이용한 방식도 있으니 참고하세요

2022-04-08 15:14 UTC, Min-92 commented on BE/src/main/java/com/team26/todolist/dto/response/CardResponse.java
>      private String cardStatusName;
여기도 String을 사용한 특별한 이유가 있을까요?

2022-04-08 15:14 UTC, Min-92 commented on BE/src/main/java/com/team26/todolist/exception/EmptyCardStatusException.java
> +public class EmptyCardStatusException extends Exception {
Exception과 RuntimeException 차이에대해서 알고있으면 좋을듯합니다.

2022-04-08 15:14 UTC, Min-92 commented on BE/src/main/java/com/team26/todolist/repository/CardRepository.java
> +    }
namedParameter 사용하신부분 좋네요 👍

2022-04-08 15:14 UTC, Min-92 commented on BE/src/main/java/com/team26/todolist/repository/CardRepository.java
> +                "WHERE isDeleted = :isDeleted AND card_status = :card_status";
SQL은 대소문자 구분이 되지 않습니다. isDeleted도 컨벤션을 맞추는게 좋아보여요

2022-04-08 15:14 UTC, Min-92 commented on BE/src/main/java/com/team26/todolist/repository/CardRepository.java
> +    }
요청이 들어올때마다 cardRowMapper가 생성될것같네요. 
어떤 문제가 발생할까요?
더 나은방법이 있을지 찾아보세요 :)

2022-04-08 15:14 UTC, Min-92 commented on BE/src/main/java/com/team26/todolist/service/CardServiceJdbc.java
> +public class CardServiceJdbc {
CardServiceJdbc 는 CardService를 상속받고 있지 않네요,
또 Primary 어노테이션이 mock, jdbc 두군데 사용되고 있는데 어떤 문제가 발생할까요?

2022-04-08 15:14 UTC, Min-92 commented on BE/src/test/java/com/team26/todolist/repository/HistoryRepositoryImplTest.java
> +class HistoryRepositoryImplTest {
test 작성해주신부분 좋습니다 👍

2022-04-08 15:14 UTC, Min-92 commented on BE/src/test/java/com/team26/todolist/repository/HistoryRepositoryImplTest.java
> +    private final HistoryRepositoryImpl historyRepository = new HistoryRepositoryImpl(jdbcTemplate);
repository를 직접 생성해서 선언해주셨는데요, 필드주입방법에 대해서 알아보세요.

2022-04-08 15:14 UTC, Min-92 commented on BE/src/test/java/com/team26/todolist/repository/HistoryRepositoryImplTest.java
> +    void 전체_History_목록_조회() {
한글로 메소드 동작에 대해서 명확하게 설명해주셨네요.
아래 다른 테스트에도 반영되면 좋을것같습니다.

2022-04-08 15:14 UTC, Min-92 commented on BE/src/test/java/com/team26/todolist/repository/HistoryRepositoryImplTest.java
> +    }
save 테스트의 경우 실제 db에 테스트 데이터가 저장된다면 어떤일이 생길까요?
방지할 방법은?

2022-04-08 15:14 UTC, Min-92 commented on BE/src/main/resources/sql/schema.sql
> +);
테이블 생성하는 쿼리는 같은형식을 가지면 좋을것 같아요

2022-04-08 15:14 UTC, Min-92 commented on BE/src/main/java/com/team26/todolist/service/HistoryServiceImpl.java
> +        if (cardAction == CardAction.ADD) {
history 생성에 관련된 동작인것 같네요.
해당 동작의 책임이 어떤 객체에 있으면 좋을지 다시 생각해보면 좋을거같아요

2022-04-08 15:14 UTC, Min-92 commented on BE/src/main/java/com/team26/todolist/service/HistoryServiceImpl.java
> +                    .cardTitleBefore(cardBefore.getCardTitle())
card.getCardTitle()의 경우 없는 메소드로 오류가 발생하네요.
commit할때는 정상동작 하는상태로 commit을 해야 합니다. 특정 지점으로 롤백시 동작 안되는 이슈가 발생할 수 있어요.

PR 요청때도 당연히 정상 동작하는 상태로 요청 주셔야 합니다.

2022-04-08 15:14 UTC, Min-92 commented on BE/src/main/java/com/team26/todolist/service/HistoryServiceImpl.java
> +                    .cardTitleBefore(cardBefore.getCardTitle())
메소드 명 변경하면서 발생한 오류같은데요,
intellij 사용한다면 shift + f6 단축키를 사용해보세요

2022-04-08 15:14 UTC, Min-92 commented on BE/src/main/java/com/team26/todolist/repository/HistoryRepositoryImpl.java
> +    private RowMapper<History> historyRowMapper() {
cardRowMapper와 동일

2022-04-08 15:14 UTC, Min-92 commented on BE/src/main/java/com/team26/todolist/domain/History.java
> +    private String cardTitleBefore;
history는 카드가 변경(생석,삭제 포함)될때 마다 기록되겠죠.
그렇다면 이전상태가 필요할까요?

2022-04-08 15:14 UTC, Min-92 commented on BE/src/main/java/com/team26/todolist/domain/History.java
> +    private CardAction cardAction;  // 필수
필수값 주석으로 표현이 아닌 validation 방식을 찾아보세요

2022-04-08 15:14 UTC, Min-92 commented on BE/src/main/java/com/team26/todolist/repository/HistoryRepositoryImpl.java
> +    }
pagination에대해서 고려해보세요

2022-04-10 06:13 UTC, Min-92 commented
리뷰드린 내용 반영하고 머지하기에 시간이 안될듯 하여 머지합니다.
다음 PR에 피드백 드린부분 고려해보세요.

2022-04-10 06:14 UTC, merged

2022-04-10 09:04 UTC, ak2j38 commented on BE/src/main/java/com/team26/todolist/controller/CardController.java
> +    @PutMapping
팀원과 상의하며 REST API에 대해 더 학습을 진행했고 개념상으로는 여전히 `PATCH`가 더 맞다고 생각하지만
url을 동일하게 가져가고 HTTP METHOD `PUT`으로 구별하는 방식으로 협의되었습니다 :)

2022-04-10 09:05 UTC, ak2j38 commented on BE/src/main/java/com/team26/todolist/repository/CardRepository.java
> +                "WHERE isDeleted = :isDeleted AND card_status = :card_status";
다른 컬럼들과 같이 컨벤션을 맞추도록 하겠습니다! 감사합니다 🙇‍♂️

2022-04-10 09:09 UTC, ak2j38 commented on BE/src/main/java/com/team26/todolist/service/CardServiceJdbc.java
> +public class CardServiceJdbc {
급하게 머지하는 과정에서 `@Primary` 어노테이션이 양쪽에 있는지 확인하지 못했습니다. 죄송합니다 😂
두군데 동일하게 `@Primary` 어노테이션이 사용된다면 `NoUniqueBeanDefinitionException` 이 발생하게 될 것 같습니다!

2022-04-10 09:12 UTC, ak2j38 commented on BE/src/main/resources/sql/schema.sql
> +);
같은 형식으로 통일 할 수 있도록 수정하겠습니다 😄

2022-04-10 09:14 UTC, ak2j38 commented
남겨주신 피드백 적용해서 수요일 PR에 포함해서 올리겠습니다.
상세한 피드백 감사합니다 왕민! 🙏

2022-04-10 09:41 UTC, ak2j38 commented on BE/src/main/java/com/team26/todolist/controller/CardController.java
> +
Q1. `모든 cardStatus에 대해서 조회할 필요는 없을까요?`
 -> 아직 그런 케이스가 떠오르지 않지만 팀원과 함께 의견을 나눠보겠습니다!

Q2. `직접 구현하는 validation 말고 어노테이션을 활용한 다른 방식이 없는지 찾아보세요 :)`
 -> `@Valid` 키워드에 대해 학습해보겠습니다.

Q3. `별개로 String 관련 많은 기능을 제공하는 apache의 StringUtils 라이브러리가 있습니다.
String 관련 편한 기능을 많이 제공하니 참고하세요.`
 -> 감사합니다. String 관련 클래스를 직접 구현해야하나 고민이었는데 활용하겠습니다 👍

2022-04-10 16:38 UTC, dukcode commented on BE/src/main/java/com/team26/todolist/controller/HistoryController.java
> +    @ResponseStatus(HttpStatus.OK)
HTTP status에 대해서 조금 더 공부를 해보니 해당 정보를 요청했을 때, Data가 없으면 204(콘텐츠 없음) 코드를 보내주는게 더 적절한 응답 일 것 같습니다. 요청에 대한 Data의 유무에 따라 200, 204코드를 동적으로 결정하여 응답하는것이 적절할 것 같습니다.

2022-04-11 02:45 UTC, ak2j38 commented on BE/src/main/java/com/team26/todolist/controller/CardController.java
> +        CardResponse movedCard = cardService.moveCard(cardMoveRequest);
요구사항을 그대로 받아들이다보니 move라는 단어만 생각났던 것 같네요 ㅠㅠ
서버입장에서 다시 생각해보니 cardStatus를 change해주는 것이 더 맞다는 생각이 들어 `changeCardStatus`로 변경했습니다!

2022-04-11 02:54 UTC, ak2j38 commented on BE/src/main/java/com/team26/todolist/dto/request/CardRegistrationRequest.java
>      private String cardStatus;
프론트에서 요청을 보낼 때 `TODO`, `ONGOING`과 같은 형식으로 넘어올 것이라고 생각했는데 이를 Enum과 쉽게 매핑하기 위해 문자열을 사용했었습니다.

하지만 더 검색을 해보니 스프링 내부에 `StringToEnumConverterFactory`을 사용해 자동으로 매핑을 해준다는 것을 알게 되었습니다. 해당 내용을 적용해보겠습니다!

2022-04-11 03:10 UTC, dukcode commented on BE/src/main/java/com/team26/todolist/service/HistoryServiceImpl.java
> +                    .cardTitleBefore(cardBefore.getCardTitle())
넵 커밋전에 꼭 오류를 확인하는 습관을 가지겠습니다!

2022-04-11 03:11 UTC, dukcode commented on BE/src/main/java/com/team26/todolist/repository/HistoryRepositoryImpl.java
> +    private RowMapper<History> historyRowMapper() {
HistoryRepositoryImpl이 멤버변수로 RowMapper를 클래스 초기화시에 초기화 하도록 하여 재활용하는 방법을 찾아보았습니다

2022-04-11 03:51 UTC, dukcode commented on BE/src/main/java/com/team26/todolist/domain/History.java
> +    private String cardTitleBefore;
클라이언트에 표현되는 History의 예시로 [**HTML/CSS 공부하기**를 **해야할 일**에서 **하고 있는 일**로 **이동**하였습니다] 와 같은 형식으로 표현되어야 해서 이전상태의 일부분을 기록이 필요할 것 같아 이전 상태를 기록해 놓았는데. 

위의 예시처럼 표현할 수 있음과 동시에 이전상태를 저장하지 않는 방법이 떠오르면 좋겠지만 잘 생각이 나지않아서 혹시 다른 방법이 있을까 질문 드립니다.!

2022-04-11 03:53 UTC, dukcode commented on BE/src/main/java/com/team26/todolist/domain/History.java
> +    private CardAction cardAction;  // 필수
해당 주석은 Builder클래스로 객체를 생성할 때 필수여야 하는 값을 임시로 메모해놓은 것인데 삭제를 미처 하지 못했습니다.

또한, 추후 프로젝트를 진행하면서 validation 방식을 사용하도록 추가하겠습니다.

2022-04-11 04:24 UTC, Min-92 commented on BE/src/main/java/com/team26/todolist/domain/History.java
> +    private String cardTitleBefore;
상태가 변경될때마다 히스토리가 저장된다면, 이전 히스토리에 이전 상태값이 저장 돼있을거에요.
이전 히스토리 조회가 가능하다면 최신 히스토리에 이전 히스토리를 기록할 필요가 없겠죠?

2022-04-11 04:26 UTC, Min-92 commented on BE/src/main/java/com/team26/todolist/domain/History.java
> +    private String cardTitleBefore;
아 히스토리를 클라이언트에서 보여주는군요. 서버단에서 히스토리 확인용인줄 알았네요. 잊어주시죠

2022-04-11 04:27 UTC, dukcode commented on BE/src/main/java/com/team26/todolist/domain/History.java
> +    private String cardTitleBefore;
넵 답변 감사합니다!

2022-04-11 04:32 UTC, dukcode commented on BE/src/main/java/com/team26/todolist/service/HistoryServiceImpl.java
> +        if (cardAction == CardAction.ADD) {
History entity 클래스 내부에 CardAction, userId,  Card들을 파라미터를 받는 팩터리 메서드를 생성한다고 생각했을 때, History라는 Entity가 Card에 의존하게되는 문제가 생길 것 같아 해당 메서드를 생성하지 않고 서비스 계층에 놓았습니다.  

History클래스에 팩터리 메서드를 생성한다면 의존성 문제를 해결할 수 있는 방법이 있을까요..?