[team-8][BE] todo-list 1주차 #2
codesquad-members-2022/todo-list pull request #85
Opened 2022-04-08 07:45 UTC by Seokho-Ham

안녕하세요 시그리드!
두번째 리뷰를 위해 pr을 날립니다. 수요일에 해주신 리뷰가 학습하는데 정말 많은 도움이 되었습니다.(궁서체입니다)🙇🏻‍♂️

### 구현사항
- [x] findById, findAll 메서드 구현 
- [x] 카드 업데이트 기능
- [x] 카드 삭제 기능

### 리뷰
- [x] 'grade-wrapper.properties'와 'be/gradlew' gitignore에 추가
- [x] RequestDto와 ResponseDto 작성
- [x] 롬복 제거
- [x] AtomicLong에 대한 의견
 - 일반 long타입의 변수에 여러 스레드에서 동시에 접근하게 되면 동시성 문제가 발생할 수 있다고 생각되어서 AtomicLong을 사용했습니다.
- [ ] 테스트 코드 assertAll 사용
- [ ] Optional을 언제 사용하는게 좋을지 고민해보기

### 참고사항
- Optional에 대한 부분은 현재 Card 타입을 반환하도록 변경했고, 데이터가 없을 경우 예외를 던지도록 했습니다. 하지만 질문해주셨던 "어떤 경우에 Optional로 기존의 객체를 wrapping하는 것이 필요할까요?" 에 대한 내용은 Optional에 대한 충분한 학습을 하지 못해서 주말동안 학습 후 현재 pr에 커멘트로 추가하겠습니다.
- 이번 미션 진행에서는 테스트코드를 손대지 못했습니다.😭 assertAll은 학습 후 테스트코드에 적용하겠습니다.
- 컨트롤러, 서비스 내의 생성자에 @autowired를 붙여줬는데, 한개일 경우 생략이 가능한건 알지만 학습단계에서는 구체적으로 명시해주는게 좋다고 생각되어 생략하지 않았습니다.😊

### 질문

- 기존에 존재하는 Card 도메인 객체를 찾아와서 필드값을 변경하는 방식
- 새로운 Card 객체를 만들어서 기존의 카드 객체를 대체하는 방식 

위의 2가지 방식 중 어떤것이 update요청에 더 알맞을까요?
도메인 객체의 필드값을 변경하는것은 거부감이 들고, 새로운 객체로 대체하는것은 update 요청으로 바라보기가 애매하다는 생각이 들어서 질문합니다.

2022-04-08 07:48 UTC, seokho-ham commented on be/src/main/java/todolist/dto/RequestCardDto.java
> +    public RequestCardDto() {
ObjectMapper가 요청으로 넘어온 데이터를 객체에 매핑할 때, default 생성자와 getter 혹은 setter를 사용해서 매핑해준다는 사실을 알게되어 추가하였습니다.

2022-04-09 08:13 UTC, Seokho-Ham commented on be/src/main/java/todolist/dto/RequestCardDto.java
> +    public RequestCardDto() {
이 부분은 해결되어서 무시해주시면 될거같습니다.👀

2022-04-11 23:59 UTC, jypthemiracle requested changes
안녕하세요, 리뷰어 Sigrid Jin입니다.
현생이 바빠 3일 만에 리뷰를 드리네요. 아직 구현 사항에 대해서는 진척이 많이 보이지 않아서, 직접적인 코드 리뷰 보다는 여러 가지 생각할 지점을 남겼으니 토의해보시고 답변 남겨주세요.
그럼, 즐거운 미션 2주차가 되기 바랍니다.

2022-04-11 23:59 UTC, jypthemiracle commented on be/src/main/java/todolist/controller/CardController.java
> +    @Autowired
`@Autowired` 에 대해 학습하고, 장점과 단점이 무엇인지 생각해봅시다. 동작 방식도 서술해주세요.
[참고할 만한 링크](https://madplay.github.io/post/why-constructor-injection-is-better-than-field-injection)

2022-04-11 23:59 UTC, jypthemiracle commented on be/src/main/java/todolist/controller/CardController.java
> +        cardService.updateCard(id, requestCardDto);
`addCard` 에서는 return 하는데, 여기서는 하지 않는 이유가 있나요?

2022-04-11 23:59 UTC, jypthemiracle commented on be/src/main/java/todolist/domain/Card.java
> +        content = requestCardDto.getContent();
아직 완성이 되지 않았군요 ㅎㅎ

2022-04-11 23:59 UTC, jypthemiracle commented on be/src/main/java/todolist/dto/ResponseCardDto.java
> +    public Long getId() {
Lombok을 사용하지 않는 결정을 하시고, 직접 getter를 만드셨네요!

2022-04-11 23:59 UTC, jypthemiracle commented on be/src/main/java/todolist/repository/CardMemoryRepository.java
> +        return store.stream().filter(card -> card.getId() == id).findAny().orElseThrow(()-> new IllegalArgumentException());
라인 indentation을 읽기 쉬운 형태로 가져갑시다. 각각의 Stream 내부 함수 별로 쪼개면 됩니다.
```suggestion
        return store.stream().filter(card -> card.getId() == id)
                             .findAny()
                             .orElseThrow(()-> new IllegalArgumentException());
```

2022-04-11 23:59 UTC, jypthemiracle commented on be/src/main/java/todolist/repository/CardMemoryRepository.java
> +        return store.stream().filter(card -> card.getId() == id).findAny().orElseThrow(()-> new IllegalArgumentException());
**도전 과제**: Exception을 throw하는데, 현재 시점에서는 어떠한 오류인지 클라이언트 입장에서는 알 수 있는 길이 없습니다. 명시적으로 exception을 던져주기 위해서는 어떻게 해야 할까요? 가장 간단하게는 원인 메시지를 명시하는 방법이 있을 것이고, 더 나아가서는 Custom Exception을 만들어 메시지를 리턴할 수도 있겠고 이에 따라서 HTTP Code를 별도로 부여하여 클라이언트에 내려줄 수도 있을 것 같습니다.

2022-04-11 23:59 UTC, jypthemiracle commented on be/src/main/java/todolist/repository/CardMemoryRepository.java
> +        return Collections.unmodifiableList(store);
해당 Collections의 라이브러리인 `unmodifiableList()` 를 사용한 이유는 무엇인가요? 해당 라이브러리를 사용했을 때의 장단점은 무엇일까요?

2022-04-11 23:59 UTC, jypthemiracle commented on be/src/main/java/todolist/repository/TodoRepository.java
> +    T findById(Long id);
함수의 리턴 값은 Optional을 처리한 상태에서 반환하는 것이 좋다고 합니다. 왜 그럴까요?

2022-04-11 23:59 UTC, jypthemiracle commented on be/src/main/java/todolist/service/CardService.java
> +    @Autowired
앞에서도 이야기했지만, `@Autowired` 가 최선일까요? 만약 아니라면, 개선할 수 있는 방법은 없을까요?

2022-04-11 23:59 UTC, jypthemiracle commented on be/src/main/java/todolist/service/CardService.java
> +            if (result.containsKey(section)) {
다음의 사항을 준수합시다.
1. 한 메서드에 오직 한 단계의 들여쓰기만 한다.
2. else 예약어를 쓰지 않는다.
3. 한 함수에 15줄을 넘기지 않는다.

왜 이 사항을 준수하는 것이 좋다고 말하는 걸까요? 한 번 생각해보시고 답변을 달아주세요.

[참고할 만한 링크](https://www.youtube.com/watch?v=FSte4ht7jII)

2022-04-11 23:59 UTC, jypthemiracle commented on be/src/main/java/todolist/service/CardService.java
> +                result.put(section, new ArrayList<>(Arrays.asList(card)));
Map 구조를 Service 클래스에서 명시적으로 가지고 있도록 하는 것이 과연 좋은 설계일까요?
그리고, card를 get하고 put하는 행위 자체를 Service 클래스에서 명시적으로 진행하는 것이 확장 가능한 설계가 가능한 방법일까요? 한 번 생각해보시고, 답변을 달아주세요.

2022-04-11 23:59 UTC, jypthemiracle commented on be/src/test/java/todolist/service/CardServiceTest.java
> +        RequestCardDto cardDto = new RequestCardDto("해야할 일", "제목", "내용");
테스트가 `RequestCardDto`로 리팩토링하고 나서도 잘 작동하는군요! 이전의 코드리뷰가 잘 반영되어 있는 점 칭찬합니다.

2022-04-12 00:00 UTC, jypthemiracle commented
우리가 슬랙으로 토의한 내용 휘발되지 않게 제가 정리하겠습니다. 여기에.
## 문
> 기존의 CardDto를 RequestDto, ResponseDto로 나누었습니다.
이 과정에서 각각의 RequestDto, ResponseDto에는 모든 필드를 파라미터로 받는 생성자와 getter 메서드를 작성했습니다.
하지만 RequestBody로 넘어온 데이터를 RequestDto 객체에 매핑하는 과정에서 아래와 같은 에러가 발생했습니다.
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `todolist.dto.RequestCardDto` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
찾아봤더니 ObjectMapper가 매핑하는 과정에서 default 생성자를 사용해 객체를 생성하고, getter나 setter, public field를 보고 프로퍼티 명을 찾아서 주입해준다는 사실을 알게 되었습니다. 위의 에러는 RequestDto 클래스에 default 생성자를 넣어줌으로써 해결했는데 이 과정에서 의문이 생겼습니다.
이전의 CardDto 클래스에도 default 생성자는 없고 파라미터를 받는 생성자와 getter 메서드가 있었는데 그때는 에러없이 매핑이 되었습니다.
위의 에러가 단순히 default 생성자가 없어서 발생한 에러라면 왜 CardDto를 사용할때는 에러가 발생하지 않았을까요?

## 답
1. 일반적인 상황에서는 default constructor가 필요합니다. 이를 전제하여 기본 생성자를 활용하여 Java Reflection을 통해 프로퍼티를 주입하는 과정을 거쳐서 DTO를 생성하기 때문입니다.
2. 하지만 @JsonProperty, @JsonAutoDetect 등을 사용한 Property 기반 클래스이거나, 생성자가 위임된 경우라면 필요하지 않습니다. 우리는 여기서 @Getter와 @Setter 를 사용하였기 때문에 Property 기반 클래스라고 해석할 수 있습니다.

[9:03](https://codesquad-members.slack.com/archives/D03A8V6ML95/p1649462612162209)
[https://velog.io/@conatuseus/RequestBody%EC%97%90-%EA%B8%B0%EB%B3%B8-%EC%83%9D%EC[…]EC%9E%90%EB%8A%94-%EC%99%9C-%ED%95%84%EC%9A%94%ED%95%9C%EA%B0%80](https://velog.io/@conatuseus/RequestBody%EC%97%90-%EA%B8%B0%EB%B3%B8-%EC%83%9D%EC%84%B1%EC%9E%90%EB%8A%94-%EC%99%9C-%ED%95%84%EC%9A%94%ED%95%9C%EA%B0%80)

그리고, ObjectMapper는 Setter와 Getter로 DTO의 필드를 가져옵니다. 이 때, 기본 생성자가 있을 때는 setter를 사용하지 않고 reflection을 사용해서 필드 값을 넣어주게 될 것입니다. ResponseDTO에 Setter를 제거한 케이스도, 다시 디버깅을 해 보시면서 어떻게 동작하는 지 확인해보시기 바랍니다.
참고: https://jojoldu.tistory.com/407

## 문
> 알려주신 블로그의 글을 보면서 저희도 디버깅을 해보았고, 모든 코드를 완벽하게 이해하지는 못했지만
내부에서 default 생성자가 있으면 default 생성자를 사용해서 매핑할 객체를 생성한다.
default 생성자가 없으면 property 기반 클래스인지 확인을 하고, property 관련 어노테이션이 적용된 클래스면 프로퍼티 기반으로 객체를 생성한다.
둘 다 해당하지 않으면 에러가 발생한다.
라는 사실들은 직접 눈으로 확인할 수 있었습니다.
저희가 이해한 내용을 바탕으로 @Getter, @Setter를 작성하면 Property기반 클래스이므로, 기본 생성자가 없어도 POST 요청을 정상적으로 받아올 것으로 예상했습니다.
하지만 다음과 같은 코드를 작성했을 때도 아래 사진처럼 전과 같은 에러가 발생했습니다. 저희가 이해한 내용이 맞다면 왜 @Getter,@Setter 를 작성했음에도 불구하고 기본 생성자가 없으면 정상적으로 매핑해주지 못하는 것일까요?

## 답
디버깅 하며 학습하시느라 수고 많으셨습니다. 포키님 환경과 달리, 제 쪽에서는 @Getter와 @Setter가 있는 상태 및 기본 생성자가 없는 경우에서 정상적으로 매핑 됩니다.

## 해결
* 인텔리제이 로컬의 폴더 자체를 삭제하고 다시 클론 받아왔더니 동작하였음.

2022-04-12 00:02 UTC, jypthemiracle requested changes

2022-04-12 00:02 UTC, jypthemiracle commented on be/src/main/java/todolist/controller/CardController.java
> +    public Map<String, List<Card>> getTodo() {
DTO로 명시된 Map 자료구조를 wrapping 할 수 없을까요? 만약 하시는 결정을 내리신다면, 이러한 설계가 좋은 점이 무엇일까요?

2022-04-12 01:24 UTC, merged

2022-04-12 15:26 UTC, Seokho-Ham commented on be/src/main/java/todolist/controller/CardController.java
> +        cardService.updateCard(id, requestCardDto);
데이터의 업데이트 요청에 대한 응답값은 필요하지 않을것 같아서 return을 하지 않도록 작성했습니다.
HttpResponseServlet에 상태코드와 메세지 정도만 추가하는것을 고려하고 있습니다.

2022-04-12 15:26 UTC, Seokho-Ham commented on be/src/main/java/todolist/controller/CardController.java
> +    @Autowired
학습해서 정리한 내용을 코멘트에 남기겠습니다.

2022-04-12 15:52 UTC, Seokho-Ham commented on be/src/main/java/todolist/service/CardService.java
> +            if (result.containsKey(section)) {
인덴트가 늘어나거나 길이가 늘어난다는것은 하나의 함수가 너무 많은 일을 하고 있는것으로 볼수도 있는것 같습니다.
하나의 메서드가 너무 많은 일을 하면 기능의 변경 혹은 확장 시 해당 메서드 내에서 수정이 필요한 곳을 발견하기도 힘들뿐더러 변경에 영향을 받는 부분들 또한 늘어납니다.

그래서 위에 말씀해주신 사항들을 준수해야한다고 생각되네요ㅎㅎ
객체지향 생활체조 원칙을 최대한 준수하려고 노력하겠습니다.

2022-04-12 15:55 UTC, seokho-ham commented on be/src/main/java/todolist/service/CardService.java
> +                result.put(section, new ArrayList<>(Arrays.asList(card)));
이 부분에 대해서 고민이 있었습니다.
처음에는 ResponseCardsDto라는 클래스를 만들어서 해당 객체가 스스로 분류작업을 하도록 하려고 했습니다.
하지만 카드를 section별로 분류하는 책임은 서비스가 가져야 하는 책임이 아닐까 하는 생각에 메서드를 서비스에 두었고, 그렇게 되면 Map을 단순히 감싸는 클래스가 될것같아서 지금의 코드가 나왔습니다.

글을 적고보니 이 로직은 응답값을 만들어내는 로직인데, ResponseCardsDto 객체가 가져도 될 것 같다는 생각이 드네요..ㅎ
시그리드의 의견도 궁금합니다!

2022-04-12 15:58 UTC, seokho-ham commented on be/src/main/java/todolist/controller/CardController.java
> +    public Map<String, List<Card>> getTodo() {
위의 코멘트에서 말씀드렸듯이 단순히 감싸도, 결국 반환하려면 Wrapper 클래스가 가지는 Map 필드를 꺼내와서 반환해야하는것 같아서 현재는 Map을 그대로 반환하도록 작성했습니다.

2022-04-12 16:01 UTC, seokho-ham commented
바쁘신 와중에도 시간내서 리뷰해주셔서 감사합니다 시그리드! 🙇🏻‍♂️
다음 pr에서는 요구되는 기능들을 최대한 구현해서 제출하겠습니다!

2022-04-12 16:03 UTC, Seokho-Ham commented on be/src/main/java/todolist/repository/TodoRepository.java
> +    T findById(Long id);
결과값을 사용하는 곳에서 Optional을 처리하는 코드를 추가적으로 작성해야한다는 단점이 있습니다.
또한 Optional 반환값 내에 값이 있다는 확신이 없는데, get()과 같은 메서드를 사용해서 에러가 발생할 수 있어서 처리한 상태로 반환하는게 좋을것 같습니다.

부족한 부분이나 고칠 부분이 있다면 알려주시면 감사하겠습니다!

2022-04-12 16:05 UTC, Seokho-Ham commented on be/src/main/java/todolist/repository/CardMemoryRepository.java
> +        return Collections.unmodifiableList(store);
현재는 메모리 레파지토리를 사용하고 있고, List 객체를 반환할때 외부에서 수정을 하지 못하도록 하기 위해서 `unmodifiableList' 를 사용했습니다.
`unmodifiableList' 은 읽기 전용 List를 생성해서 반환하기 때문에 외부에서 값을 추가하거나 삭제하지 못합니다. 
하지만 내부에 있는 객체 자체에 접근해서 값을 변경하는것까지는 제가 고려하지 못했던것 같습니다..ㅎ

2022-04-12 16:17 UTC, Seokho-Ham commented on be/src/main/java/todolist/controller/CardController.java
> +    @Autowired
@Autowired는 의존성 주입을 위해 스프링에게 정보를 제공하는 어노테이션입니다. 스프링은 해당 어노테이션이 붙은 의존 객체의 타입에 맞는 빈을 컨테이너에서 찾아서 주입합니다.

- 생성자가 하나일 경우 @Autowired 어노테이션을 생략할 수 있습니다. 
- 현재 코드에서는 의존성 주입을 한다는 것을 명시적으로 작성하기 위해서 생략하지 않고 사용했습니다.