[team_31][BE YAN-K] 1주차 금요일PR
codesquad-members-2022/todo-list pull request #93
Opened 2022-04-08 08:02 UTC by KTH-96

안녕하세요 왕민,  K,Yan 1주차 금요일 PR보내드립니다. 🫡 🫡

### 구현내용
- 카드리스트 조회 기능
- 카드 업데이트 및 이동시 로직 작성
- 쿼리 수정은 완료 했으나 인덱스 컬럼은 아직 추가하지 못하였습니다 :)
### 질문사항
- 카드들의 순서를 드래그 앤 드롭으로 카드 순서(위치 이동)을 하려 합니다. 이 때 인덱스 컬럼을 추가해 해당 내용을 테이블에 저장하려고 하는데요. 이 때 위치를 중간으로 옮기는 상황이 발생합니다. 만약에 5번째 카드가 1번째로 온다면 request요청이 5번 일어나는 상황에 있습니다 혹시 더 나은 방법이 있을까요?
- 해야하는 일, 하는중인 일, 완료한 일 을 구분하고 있는데 그 구분마다 프론트에서 랜더링을 한다고 했을때 저희 쪽에서 구분에 맞게 보내는게 좋을지 항상 전체적으로 넘겼을때 프론트 단에서 구분해서 적용하는게 리소스적으로 어떤게 이득일까요? 더 좋은 방법이 있으면 조언 부탁 드립니다 :)

2022-04-08 15:58 UTC, Min-92 reviewed
안녕하세요 왕민입니다.

코멘트 남겨 드린부분 고민해보시고 반영해주세요 :)

- 한번에 여러 카드의 상태를 변경할 수 있는 api를 제공하는건 어떨까요?
- 기능 요구사항에 따라 달라질것 같네요, 만약 카드 목록에 페이징을 적용한다면 어떻게 될까요?

2022-04-08 15:58 UTC, Min-92 commented on todo-list/src/main/java/com/todolist/project/domain/CardStatus.java
> +public enum CardStatus {
네이밍 좋네요 👍

2022-04-08 15:58 UTC, Min-92 commented on todo-list/src/main/java/com/todolist/project/domain/card/Card.java
> +    private Long id;
👍
primitive 타입 대신 wrapper class를 사용한 이유는 무엇일까요?

2022-04-08 15:58 UTC, Min-92 commented on todo-list/src/main/java/com/todolist/project/domain/card/Card.java
> +@Getter
앗 롬복 의존성 삭제가 아니라 롬복 사용을 선택하셨군요

2022-04-08 15:58 UTC, Min-92 commented on todo-list/src/main/java/com/todolist/project/domain/card/Card.java
> +@Getter
롬복이 아주 편한도구지만 초보자에겐 양날의 검이 될수 있습니다.
어떤 부작용이 발생할수 있을까요?

2022-04-08 15:58 UTC, Min-92 commented on todo-list/src/main/java/com/todolist/project/domain/card/CardRepository.java
> +    private final static String INSERT_CARD_SQL = "INSERT INTO card(title, contents, writer, created_date, card_status) VALUES (?,?,?,?,?)";
파라미터를 ? 로 넘기면 어떤 문제가 발생할 수 있을까요?
파라미터수가 수십개로 늘어난다면..?
이런 불편함을 개선할 방법을 찾아보세요 :)

2022-04-08 15:58 UTC, Min-92 commented on todo-list/src/main/java/com/todolist/project/domain/card/CardRepository.java
> +    }
stream을 사용한 이유가 있을까요?

2022-04-08 15:58 UTC, Min-92 commented on todo-list/src/main/java/com/todolist/project/domain/card/CardRepository.java
> +    }
추가로 Optional 객체를 그대로 리턴해주고있는데, 옵셔널 객체를 처리 없이 넘겨도 될까요?

2022-04-08 15:58 UTC, Min-92 commented on todo-list/src/main/java/com/todolist/project/domain/card/CardRepository.java
> +    public int add(CardAddDto cardAddDto){
레포지토리에 card를 저장하는데 card 객체를 저장해야할지, dto를 저장해야할지 고민해보세요 :)

2022-04-08 15:58 UTC, Min-92 commented on todo-list/src/main/java/com/todolist/project/domain/card/CardRepository.java
> +    private RowMapper<Card> cardRowMapper(){
요청이 들어올때마다 cardRowMapper가 생성될것같네요.
어떤 문제가 발생할까요?
더 나은방법이 있을지 찾아보세요 :)

2022-04-08 15:58 UTC, Min-92 commented on todo-list/src/main/java/com/todolist/project/service/CardService.java
> +        );
repository에 남긴 코멘트와 같은내용입니다.
optional 처리를 service레이어에서 해야할지 고민해보세요

2022-04-08 15:58 UTC, Min-92 commented on todo-list/src/main/java/com/todolist/project/service/CardService.java
> +    }
CardUpdateDto를 생성하는 메소드로 보이네요, 어떤 객체가 해당 책임을 가지고 있어야할지 고민해보세요 :)

2022-04-08 15:58 UTC, Min-92 commented on todo-list/src/main/java/com/todolist/project/service/CardService.java
> +    public List<Card> findAll() { return cardRepository.findAll(); }
다른 메소드와 다르게 한줄로 선언돼있네요, 컨벤션을 맞추는게 좋아보입니다.

2022-04-08 15:58 UTC, Min-92 commented on todo-list/src/main/java/com/todolist/project/web/CardController.java
> +    public List<Card> home() {
GET /card 의 동작이 home()일지 네이밍 고밍해보세요.
또한 메소드는 동작이므로 보통 동사로 시작합니다.

2022-04-08 15:58 UTC, Min-92 commented on todo-list/src/main/java/com/todolist/project/web/CardController.java
> +        return cardService.removeCard(id);
DELETE /card/id 👍
uri 만으로 동작을 잘 표현해주셨네요 :)

2022-04-08 15:58 UTC, Min-92 commented on todo-list/src/main/java/com/todolist/project/web/CardController.java
> +        return cardService.removeCard(id);
지금도 좋지만 uri에 단수, 복수 어떤걸 써야할지 좀 더 고민해보세요 :)

/cards/1
/card/1

2022-04-08 15:58 UTC, Min-92 commented on todo-list/src/main/java/com/todolist/project/web/CardController.java
> +        return cardService.updateCard(id, dto);
👍

2022-04-08 15:58 UTC, Min-92 commented on todo-list/src/main/java/com/todolist/project/web/dto/CardAddDto.java
> +    }
cardAddDto.cardCreatedTime()을 여러번 호출하면 어떤 문제가 있을까요?

2022-04-08 15:58 UTC, Min-92 commented on todo-list/src/main/java/com/todolist/project/web/dto/CardUpdateDto.java
> +    }
메소드 이름으로는 cardCreatedTime을 초기화 해줄걸로 보이네요.
이름과 동작에 대해서 한번 더 고민해보세요.

cardAddDto처럼 여러번 호출하면 어떤 문제가 발생할까요?

2022-04-08 15:58 UTC, Min-92 commented on todo-list/src/main/java/com/todolist/project/web/dto/CardAddDto.java
> +    }
클래스의 필드로 선언하지 않고, 메소드로 선언한 이유가 있을까요?

2022-04-08 15:58 UTC, Min-92 commented on todo-list/src/main/resources/schema.sql
> +    created_date DATETIME DEFAULT CURRENT_TIMESTAMP
👍

2022-04-08 16:00 UTC, Min-92 requested changes
request change로 상태 변경합니다.

2022-04-10 06:13 UTC, Min-92 commented
리뷰드린 내용 반영하고 머지하기에 시간이 안될듯 하여 머지합니다.
다음 피드백 드린부분 고려해보세요.

2022-04-10 06:13 UTC, merged

2022-04-11 02:04 UTC, KTH-96 commented on todo-list/src/main/java/com/todolist/project/domain/card/Card.java
> +    private Long id;
래퍼클래스가 기본타입을 객체로 사용할수 있기 때문에 지금 DB에는 사용 하지는 않지만 테이블에 Null이 필요한 경우가 있을 수도 있기때문에 래퍼클래스를 기본적으로 사용해야 하는걸로 생각했습니다 :)

2022-04-11 02:04 UTC, KTH-96 commented on todo-list/src/main/java/com/todolist/project/domain/card/Card.java
> +@Getter
무분별한 setter사용과 양방향 연관관계시 ToString 호출시 순환참조가 계속 발생할 수 있다로 찾아봤습니다. 
이 이유 외에 초보자가 잘 알지 못하는데 사용하는 경우 학습에 있어서 맹점이 있을수 있기때문에 말씀하시는걸까요??

2022-04-11 02:04 UTC, KTH-96 commented on todo-list/src/main/java/com/todolist/project/domain/card/CardRepository.java
> +    private final static String INSERT_CARD_SQL = "INSERT INTO card(title, contents, writer, created_date, card_status) VALUES (?,?,?,?,?)";
NamedParameterJdbcTemplate를 이용해서 BeanPropertySqlParameterSource를 사용해 객체와 매핑시키면 ?에 필요한 데이터를 넣는게 아니라 :변수명으로 원하는 부분에 써놓기만 하면 되는거 같습니다!

2022-04-11 02:04 UTC, KTH-96 commented on todo-list/src/main/java/com/todolist/project/domain/card/CardRepository.java
> +    }
로직을 담당하는 부분을 service에 넣으라고 알고있었는데 Optional처리 같은건 리퍼지토리 계층에서 하는게 좋을까요??

2022-04-11 02:04 UTC, KTH-96 commented on todo-list/src/main/java/com/todolist/project/domain/card/CardRepository.java
> +    public int add(CardAddDto cardAddDto){
dto는 데이터 전달만 해야 할거같습니다. service에서 repository로 넘어갈때 card로 넘기는게 좋아보입니다. :)

2022-04-11 02:04 UTC, KTH-96 commented on todo-list/src/main/java/com/todolist/project/domain/card/CardRepository.java
> +    private RowMapper<Card> cardRowMapper(){
메소드 안에서 만들어주어도 실행수에는 똑같을거 같고 혹시 멀티쓰레드 환경에서 문제가 발생할까요? 상상이 잘안갑니다 ㅠㅠ

2022-04-11 02:04 UTC, KTH-96 commented on todo-list/src/main/java/com/todolist/project/service/CardService.java
> +    }
CardUpdateDto객체 안에서 처리하는것이 좋아보입니다 감사합니다 :)

2022-04-11 02:04 UTC, KTH-96 commented on todo-list/src/main/java/com/todolist/project/web/CardController.java
> +    public List<Card> home() {
list로 변경하겠습니다. :)

2022-04-11 02:04 UTC, KTH-96 commented on todo-list/src/main/java/com/todolist/project/web/CardController.java
> +        return cardService.removeCard(id);
cards로 변경하겠습니다 :)

2022-04-11 02:04 UTC, KTH-96 commented on todo-list/src/main/java/com/todolist/project/web/dto/CardAddDto.java
> +    }
멀티쓰레드 환경일때 문제가 생길까요? 찾아봤는데 잘 모르겠습니다. ㅠㅠ

2022-04-11 02:04 UTC, KTH-96 commented on todo-list/src/main/java/com/todolist/project/web/dto/CardUpdateDto.java
> +    }
Card객체로 사용할 수 있도록 변경하겠습니다. :)

2022-04-11 02:04 UTC, KTH-96 commented on todo-list/src/main/java/com/todolist/project/web/dto/CardAddDto.java
> +    }
이거 변경해야겠네요 ㅠㅠ 감사합니다.

2022-04-11 04:34 UTC, Min-92 commented on todo-list/src/main/java/com/todolist/project/web/dto/CardAddDto.java
> +    }
cardAddDto의 createdTime을 조회할때마다 다른 결과를 응답하겠죠. 동일한 결과를 응답해야 하는 함수가 매번 다른 결과를 응답하면 문제가 됩니다.(순수함수) 
또 createTime은 함수가 아니라 필드에 저장되어야 할 성격으로 보이네요

2022-04-11 04:36 UTC, Min-92 commented on todo-list/src/main/java/com/todolist/project/domain/card/CardRepository.java
> +    }
해당 객체가 없을때  null을 반환하거나, 특정값을 반환하는것은 서비스 로직보단 저장소의 역할같아요

2022-04-11 04:42 UTC, Min-92 commented on todo-list/src/main/java/com/todolist/project/domain/card/CardRepository.java
> +    private RowMapper<Card> cardRowMapper(){
rowmapper를 미리 생성해두고 사용하는 방법을 생각해보세요 :)