[Team-05][Android] UI 리사이클러 뷰 및 다이얼로그 구현
codesquad-members-2022/todo-list pull request #98
Opened 2022-04-08 08:05 UTC by junseokseo9306

안녕하세요 앨런 :) 

저희가 구현한 내용은 다음과 같습니다

---
## RecyclerView Adapter구현
- 리사이클러 뷰에 어뎁터를 구현하였습니다

---
## 다이얼로그 프래그먼트 구현
- 다이얼로그 프레그 먼트를 생성하였습니다.
- 뷰모델에서 다이얼로그 프레그먼트에서 작성된 카드의 정보를 받아서 viewModel에 있는 라이브데이터로 넘겨주도록 구현하였습니다.
- 각각 CompleteDialogFragment, ProgressDialogFragment, TodoDialogFragment 3가지의 다이얼로그로 구성하여 각각의 리사이클러 뷰에 대응되도록 구현하였습니다

---
## ItemTouchHelper 
- 아이템 터치 헬퍼를 구현하여서 스와이프 했을때 삭제 버튼을 만드는 중이였습니다. 

![todo-list](https://user-images.githubusercontent.com/83396157/162390705-d2247146-fd73-4341-a227-4fdde7209c08.gif)

2022-04-09 07:32 UTC, sabgilhun requested changes
한, 조시 한주간 수고 많이하셨습니다.

어려운 기능인데 빠르게 진행하셨네요.

리뷰 달린 것들은 너무 시간이 오래걸린다고 생각되는 것은 코멘트로 패스하겠다고 말씀하고 넘어가셔도 됩니다.

프로젝트 완성 목표니까요. 파이팅입니다.

2022-04-09 07:32 UTC, sabgilhun commented on android/app/src/main/java/com/codesquad/aos/todolist/ui/MainActivity.kt
> +            binding.tvTodoBadgeCount.text = it.size.toString()
만약 페이징을 추가하실거라면, 해당 size는 서버로 부터 전체 사이즈를 받아오도록 수정이 필요해 보입니다.

2022-04-09 07:32 UTC, sabgilhun commented on android/app/src/main/java/com/codesquad/aos/todolist/ui/MainActivity.kt
>                      // binding.drawerLaytout?.open()
주석 달아주신 것처럼
`DrawerLayout.open()`의 함수 동작을 확인해보면, (`open()` 메서드 우클릭 -> Go To -> Implementation, 으로 구현 코드 확인 가능합니다.)

```
@Override
public void open() {
    openDrawer(GravityCompat.START);
}
```

위와 같아요. 실상은 `openDrawer(...)` 쓰고 있습니다.

또 `openDrawer(...)` 내부 코드를 살짝 보자면, `DrawerLayout` 자식 뷰 중, open할 방향의 `DrawerView(NavigationView)`를 찾고 그 view를 open하는 형태입니다.

다른 gravity 값을 넣어주면 찾지 못해 `IllegalArgumentException` 발생 시키드록 sdk를 구현해둔 것이고요.

이렇게 내부 코드를 보는 습관을 들이면 리서칭하는 시간을 줄일 수 있어요.

2022-04-09 07:32 UTC, sabgilhun commented on android/app/src/main/java/com/codesquad/aos/todolist/ui/MainActivity.kt
> +            // 닫는 부분도 close()로만 하면 에러 발생
여기도 open 처럼 한번 천천히 확인해보시면 이해하는데에 도움이 될거 같아요.

2022-04-09 07:32 UTC, sabgilhun commented on android/app/src/main/java/com/codesquad/aos/todolist/ui/MainActivity.kt
> +                supportFragmentManager, "DialogFragment"
`show(..., tag) ` 메서드의 경우 tag은 나중에 `supportFragmentManager.findFragmentByTag()`를 통해 특정 Fragment를 찾을때 사용되는 값입니다. 

이 경우 `TodoDialogFragment`, `ProgressDialogFragment`, `CompleteDialogFragment` 모두 동일한 tag 값을 넣어주고 있어서, 문제가 될 수 있습니다.

현재 `findFragmentByTag`를 사용하고 있진 않지만, 잘못된 사용법이니 고치는게 좋아보이네요.

2022-04-09 07:32 UTC, sabgilhun commented on android/app/src/main/java/com/codesquad/aos/todolist/ui/MainActivity.kt
> +                    paint.color = Color.parseColor("#FF0000")
이미 알고 계실지 모르겠지만 `@ColorInt`, `@ColorRes`에 대한 정리를 해보면, sdk 메서드 동작을 이해하는데에 도움이 될겁니다.

2022-04-09 07:32 UTC, sabgilhun commented on android/app/src/main/java/com/codesquad/aos/todolist/ui/TodoViewModel.kt
> +    val todoListLd: LiveData<MutableList<Card>> get() = _todoListLd
LiveData는 이벤트를 발생시키는 용도 외에도 값을 홀딩하는 역할도 해주기 때문에 아래와 같이 사용해도 무방합니다.

```
private val _todoListLd = MutableLiveData<MutableList<Card>>(mutableListOf()) << 생성자에 default 값도 넣어줄 수 있습니다.
val todoListLd: LiveData<MutableList<Card>> get() = _todoListLd

val list = _todoListLd.value
...
```

만약 지금 사용하고 계신 방법 그대로 사용하실거라면, 

`private var todolist = mutableListOf<Card>()` -> `private val todolist = mutableListOf<Card>()` 
list들은 variable이 아닌 value로 바꾸는 것이 좋아보이네요!

2022-04-09 07:32 UTC, sabgilhun commented on android/app/src/main/java/com/codesquad/aos/todolist/ui/adapter/LogCardListAdapter.kt
> +            }
DiffUtil 사용법을 잘 알고 계신것 같네요. 👍

2022-04-09 07:32 UTC, sabgilhun commented on android/app/src/main/java/com/codesquad/aos/todolist/ui/adapter/TodoCardListAdapter.kt
> +class TodoCardListAdapter : ListAdapter<Card, TodoCardListAdapter.CardViewHolder>(diffUtil) {
Todo, Progress, Complete 리스트에서 같은 Adapter를 사용하는 접근 좋아보이네요.

해당 카드들 UI 영역은 거의 비슷하게 그려질걸로 보입니다. 다만 동작은 조금 다를 것으로 예상되는데, 서로 다른 동작 혹은 서로 달라지는 UI는 외부에서 해당 Adapter의 동작을 설정할 수 있는 형태로 설계 해보시면 좋을것 같아요.

2022-04-09 07:32 UTC, sabgilhun commented on android/app/src/main/java/com/codesquad/aos/todolist/ui/dialog/CompleteDialogFragment.kt
> +        }
해당 동작 중에 묶어서 Util로 만들면 좋아보이는 부분이 있네요.

보통은 버전별 분기가 들어가는 코드들은 `XXXXCompat` 형태로 sdk에서 지원해주는데, 여기 동작은 없는걸로 보이네요.

한번 만들어보시는 것도 좋습니다.

어느 로직까지 공통 Util 메서드로 빼내야지 좋을지 한번 고민해보고 작업해보세요.

2022-04-09 07:32 UTC, sabgilhun commented on android/app/src/main/java/com/codesquad/aos/todolist/ui/dialog/ProgressDialogFragment.kt
> +            }
이 로직들이 Fragment에 있으면 좋을지, ViewModel에 있으면 좋을지 한번 고민해보세요.

저는 이런 형태로 접근할 것 같습니다.

Event(유저가 등록 입력) > 
ViewModel로 입력한 데이터 전달 > 
입력한 데이터에 맞게 데이터 적재(서버든 로컬DB든) > 
적재 완료 이벤트 View쪽으로 전달 > 
dissmiss()

2022-04-09 07:32 UTC, sabgilhun commented on android/app/src/main/res/layout-sw600dp-land/item_todo_card.xml
> +    android:elevation="0dp">
`CardView`에서 elevation을 수정하고 싶다면 `app:cardElevation`을 사용하시면 됩니다.

저도 항상 헷갈리는 부분인데 사람들은 다 비슷하네요. ㅎㅎ

2022-04-09 07:32 UTC, sabgilhun commented on backend/.gitignore
> +HELP.md
backend 코드들 이 PR에 포함이 되었습니다.

꼭 PR을 작성하기전에 FileChanged를 쭉 훑어 보시고 의도하지 않은 코드가 포함됐다면 수정하는 습관을 들이는게 좋습니다

2022-04-09 07:33 UTC, sabgilhun commented
backend 코드가 추가된것 때문에 컨플릭이 나고 있으니, 이건 꼭 수정해주세요 ~_~

2022-04-09 10:32 UTC, junseokseo9306 commented on backend/.gitignore
> +HELP.md
빠르게 처리해보도록 하겠습니다.

2022-04-09 10:49 UTC, junseokseo9306 commented on android/app/src/main/java/com/codesquad/aos/todolist/ui/dialog/ProgressDialogFragment.kt
> +            }
언급해 주신 부분을 가지고 레이어를 구성해 보겠습니다.

2022-04-10 09:42 UTC, merged

2022-04-13 05:07 UTC, hanchang97 commented on android/app/src/main/java/com/codesquad/aos/todolist/ui/TodoViewModel.kt
> +    val todoListLd: LiveData<MutableList<Card>> get() = _todoListLd
private var todolist = mutableListOf<Card>() -> private val todolist = mutableListOf<Card>() 형태로 수정완료 했습니다

2022-04-13 05:22 UTC, hanchang97 commented on android/app/src/main/res/layout-sw600dp-land/item_todo_card.xml
> +    android:elevation="0dp">
수정했습니다!