[Team 34] [Front] Millie & Hoi
codesquad-members-2022/todo-list pull request #99
Opened 2022-04-08 08:05 UTC by youryu0212

### 진행상황

2022-04-08 13:53 UTC, ocipap requested changes
리뷰 질문 내용을 보니 함수형 프로그래밍에 대한 고민이 많으신 것 같습니다!

함수형 프로그래밍에서의 순수함수는 사이드 이펙트 (부수 효과)가 없어야 합니다! 하지만 프론트엔드에서 부수효과를 없앨 수 있을까요??

```jsx
// 순수함수
const add = (a, b) => a + b;

// 부수효과 발생하는 함수
let b = 1;

const add = (a) => a + b; // 호출할 떄 마다 매번 결과가 달리집니다!

```

여기서 변수 b 에 해당하는 것이 제 생각에는 프론트에서의 돔입니다. 즉, 모든 로직을 순수하게 작성할 수 없습니다. 외부에 있는 돔이라는 값을 참조를 해야 로직을 풀어나갈 수 있기 떄문에요!

하지만 프론트에서 함수형 프로그래밍을 할 수 없다는 건 아닙니다! 부수효과를 일으키는 함수를 격리 시키는 방법 최소화 하거나, 로직 과정 중에 명확히 부수 효과를 일으킨다고 드러내는 방법이 있을 것 같아요!

서버로 부터 받은 값을 템플릿 함수로 변화하는 과정 ← 순수함수

템플릿 함수를 엘리먼트화 하는 과정 ← 순수함수

만들어진 엘리먼트에 이벤트를 붙이는 과정 ←부수효과

만들어진 엘리먼트를 특정 엘리먼트에 붙이는 과정 ← 부수효과

그렇다면 이런 구조가 나올 수도 있겠네요 

```jsx
(() => {
	const data = await 데이터 패치 함수();

	const tmpls = data.map(템플릿팅 함수);

	const elements = tmpls
		.map(엘리먼트 함수)
		.foreach(해당 엘리먼트에 붙는 이벤트) // 부수효과!!

	const 부모엘리먼트;

	// 특정 엘리먼트 붙이기
	elements.foreach(el => 부모엘리먼트.insertAdjacentHTML(~~~~, el)) // 부수효과 !!
	

	부모 엘리먼트 이벤트 함수(부모엘리먼트) // 부수효과

})()
```

각각의 과정을 좀 더 명확하게 함수명으로 드러내면 좋을 것 같습니다! 

사용하신 addNewCard 와 createCard 는 하는 동작은 명확하게 다른데 내부 구현을 보지 않으면 해당 함수의 역할을 가늠하기가 힘든 것 같아요!

그리고 event delegate 라는 키워드를 학습하셨다면, 좀 더 다양한 코드를 작성할 수 있을 것 같아서 가이드드립니다!

클로저에 관한 문의를 주셨는데, 조금은 단순하게 생각하셔도 좋을 것 같아요!

> 해당 메소드가 리턴한 엘리먼트로만 그 데이터에 접근하고 싶어서 입니다.

해당 목적의 이유를 설명해주시면 쓰레드 이어서 남겨드리도록 하겠습니다!
고생하셨습니다!!! 🔥🔥🔥🔥

2022-04-08 16:58 UTC, youryu0212 commented
> 

- 캡슐화와 정보은닉을 구현해 외부에서 해당 데이터를 접근할 수 있는 방법을 차단하고 싶다는 생각으로 한 질문입니다. 함수형 프로그래밍은 cs10때 한번 해본것 말고는 경험이 없어서 클로저를 활용해 본 경험이 적은데, 클래스를 사용하지 않고 스테이트를 어떻게 포함할 수 있을지 고민하다가, 해당 main 태그에서만 사용되는 데이터를 클로저로 묶어서 클래스처럼 사용할 수 있을 것 같았습니다.

- 기능 구현을 우선하다 보니 변수명에 다소 소홀했던 것 같습니다.
    - createMainElement → createMainObj : return element, getStor 프로퍼티(메소드)를 가진 객체
    - createCard → insertCardToColumn
        - insertCardsToColumns : index.js에서 forEach 동작하던 것을 카드 자체에서 반복할 수 있도록 구성
    - addNewCard → onAddBtnClick : +버튼을 클릭했을 때 발생할 이벤트 등록
        - handleAddBtnClick : + 버튼을 클릭했을 때 처리할 이벤트 핸들러
    
- 두번째 질문에 해당하는 내용은 코드를 리팩토링하면서 혼자 수정해 봤습니다. insertCardToColumn은 첫번째 인자에 해당하는 column에, 해당 칼럼 데이터를 조회하면서 카드를 주입해주는 함수입니다. 하지만 메인에는 여러 column이 존재할 수 있어서 기존에는 index.js에서 forEach로 반복 호출하는 방법과 한번에 처리해주는 방식을 고민했는데, 생각해보니 forEach로 순회하면서 하나씩 처리해 주는 함수를 반복 호출해주는 함수도 함께 만들면 index도 가벼워지고 더 효율적으로 활용 가능할 것 같아서 그렇게 구성했습니다.

- 질문 자체가 다소 잘못된 내용이 있었던 것 같습니다. 코드를 다시 읽어보니 promise가 리턴된 것은 클로저와 전혀 무관한 부분이었고 await를 빼먹어서 발생한 문제였기 때문에 코드를 다시 수정했습니다. 가능하다면 바뀐 코드로 리뷰해 주셨으면 좋겠습니다.

- newCard.js에 handlerAddBtnClick파일을 나름대로 이벤트 위임을 쓴다고 생각했는데 다시 한번 중요성을 상기했습니다. event delegate 키워드 추가 학습 해보겠습니다.

2022-04-10 02:55 UTC, ocipap commented on src/js/constants/constant.js
> +export const todoListUrl = `http://localhost:3000/todoListData`;
url 상수화는 좋은 것 같습니다!
보통 상수는 전부 대문자로 쓰는 관습이 있습니다!
TODO_LIST_URL

2022-04-10 03:02 UTC, ocipap commented on src/js/views/main.js
> +  })();
createMainObj 의 역할이 모호한 것 같네요.
동작으로 봐서는
- 데이터 fetch 후 데이터 저장
- main element 바인딩

이 두동작 후 해당 두 결과물을 object 로 합쳐주는 역할을 하는 것 같은데, 두 동작이 서로 연관이 없어 보여서 분리해도 좋을 것 같습니다!

2022-04-10 03:14 UTC, ocipap commented on src/js/views/main.js
> +  })();
추가로 createMainObj 라는 변수를 봤을때, 해당 함수에서 만들어내는 mainObj 라는 값을 명확하게 유추할 수 없을 것 같아요!
위에 분리 작업을 하면서 좀 더 명확한 이름을 사용해보시면 어떨까요??

2022-04-10 03:24 UTC, ocipap commented
> newCard.js에 handlerAddBtnClick파일을 나름대로 이벤트 위임을 쓴다고 생각했는데 다시 한번 중요성을 상기했습니다. event delegate 키워드 추가 학습 해보겠습니다.

넵! 아마 기능을 더 구현하다 보면 부모에 이벤트를 걸고 타겟인지 아닌지 검사해서 이벤트를 수행하는 패턴이 점점 늘어날 것 같아요!
만약 해당 코드가 2~3개 정도 늘어나면 하나의 유틸 함수로 작성해보시면 좋을 것 같습니다!

2022-04-10 03:25 UTC, ocipap commented
코멘트 확인 후 쓰레드 남겨주시고, 이후 머지하도록 하겠씁니다.

2022-04-10 07:26 UTC, youryu0212 commented
> 코멘트 확인 후 쓰레드 남겨주시고, 이후 머지하도록 하겠씁니다.

1. 상수명 대문자로 변경
2. createMainObj → 로직 분리
    - createMainElement : 메인 엘리먼트 생성
    - 페치 후 데이터 저장과 관리는 model/store.js에서 관리
3. store 
    - store 프로퍼티 : {}
    - getStore(element) : store[element] 리턴
    - getStoreAll() : store 프로퍼티 리턴
    - setStore(elementName, item) : store[elementName]에 item 저장
    
4. 컨트롤러 분리
- 엔트리포인트(index.js)에서 뷰를 생성한 뒤 컨트롤러에 전달
- 컨트롤러에서 모든 모델과 뷰를 관리하게 하여 의존성을 제거
- store.setStore 메소드를 이용해 뷰 단위 (현재 프로젝트에서는 main)로 데이터 관리

함수형에서는 MVC 형태가 힘들거라고 예단하여 깊게 고민하지 않았던 것 같습니다. 로직의 연관성, 동작의 분리에 대한 피드백을 받고 다시 코드를 읽어보니 M - V 분리가 가능할 것 같아서 진행했습니다. 

1. 뷰는 다른 뷰나 모델에 의존하지 않게 독립적으로 설계
2. 모델 역시 다른 뷰나 모델에 의존하지 않도록 설계
3. 뷰가 모델을 사용해야 하거나 변경해야 하는 모든 로직은 컨트롤러를 통해 수행

 세 가지 기준을 가지고 구현했는데 잘 지켜지고 있는지 모르겠습니다. 디자인 패턴이나 폴더구조 등은 모두 유지보수를 위함이기 때문에 이런 기준을 설정했습니다. 현재 상태의 구조가 괜찮은 것인지 잘 모르겠습니다. 구조가 나쁘다면 어떻게 개선해야 할 지 가이드를 받고 싶습니다.

 이벤트 핸들러와 등록을 뷰에 놔둬야 할지, 구분해야 할지 고민이 됩니다. 저번 미션을 할 때는 컨트롤러에 모든 이벤트 핸들러를 구성해 이벤트 등록도 컨트롤러에서 진행했었습니다. 그런데 그룹리뷰에서 ‘이벤트 핸들러는 컨트롤러에, 등록은 뷰에서 해야한다’는 의견이 나왔습니다. 저는 굳이 그렇게 하는 것 보다 로직을 모아두는게 더 유지보수에 쉬울 것 같아 지금은 모두 뷰에서 처리할 수 있게 구현했습니다. 뷰만 보고도 뷰에 어떤 이벤트가 있는지, 그 이벤트는 어떤 동작을 하는지 파악할 수 있게 하는게 더 좋다고 판단했기 때문입니다. 빠삐코의 견해를 듣고 싶습니다.

2022-04-11 06:15 UTC, ocipap commented
저는 개인적으로 필요로 인한 도입을 했을때 가장 큰 의미를 가진다고 생각합니다.
아직까지 작업한 페이지나 기능이 적은 상태에서는 나누는 이유에 대해 깊게 생각할 수 없을 것 같아요!

2022-04-11 06:20 UTC, merged